{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.9+41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+41.jar",
          "url": "uno-0.7.9+41.jar",
          "size": 261,
          "sha512": "77e6f263bf9b4d61f7feefd1fe00bf3f25397793a1328a1178287b9386ccd979f2f8361c6b5281d3cfb2a3cd666829e9189e9882781d7a794576536ec45f971b",
          "sha256": "cb0c2417a1e8d0446f227c6b0af39db97487224beccc622e1dd0f7da1edc08ac",
          "sha1": "44060ee286534d233896bb9ed008ce2d54370bc3",
          "md5": "528c4c9129c0bc7adff4c35a75b98e19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+41.jar",
          "url": "uno-0.7.9+41.jar",
          "size": 261,
          "sha512": "77e6f263bf9b4d61f7feefd1fe00bf3f25397793a1328a1178287b9386ccd979f2f8361c6b5281d3cfb2a3cd666829e9189e9882781d7a794576536ec45f971b",
          "sha256": "cb0c2417a1e8d0446f227c6b0af39db97487224beccc622e1dd0f7da1edc08ac",
          "sha1": "44060ee286534d233896bb9ed008ce2d54370bc3",
          "md5": "528c4c9129c0bc7adff4c35a75b98e19"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+41-all.jar",
          "url": "uno-0.7.9+41-all.jar",
          "size": 63593444,
          "sha512": "085d2221cc3a5e6b829bbecb98a154c7e9e71134768b89a92cfaadb7be04005462ac8ab4aadba793c85eb88e7ed4121540a848cf282e12556a5220161a463735",
          "sha256": "15e89a4a9e478591bff27b112f4653680f220d30af0d87e9bc4bb25d9082f710",
          "sha1": "0c63ad34dc86b7d30e1a63d1b100eb407f55e9e9",
          "md5": "b9c17bc2df2b173ac179f24a1be3979c"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-0.7.9+41-jdk8.jar",
          "url": "uno-0.7.9+41-jdk8.jar",
          "size": 261,
          "sha512": "26173f69bfaeb8dcb6b36761a0593a919a46e353eb99f5c3d57789d4337ee2a7afe53f4055aceb37fe257d55cd14ea1d2edcc252f3ae2c849da14fe7c2a4d5ed",
          "sha256": "6651dd42e67bff28234418de331778147e921682e5e48df87b0212857176858e",
          "sha1": "6676beef38e2da58152ce882313ab3f505995534",
          "md5": "fa49a030a833d31128177462514c3429"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+41"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+41-jdk8.jar",
          "url": "uno-0.7.9+41-jdk8.jar",
          "size": 261,
          "sha512": "26173f69bfaeb8dcb6b36761a0593a919a46e353eb99f5c3d57789d4337ee2a7afe53f4055aceb37fe257d55cd14ea1d2edcc252f3ae2c849da14fe7c2a4d5ed",
          "sha256": "6651dd42e67bff28234418de331778147e921682e5e48df87b0212857176858e",
          "sha1": "6676beef38e2da58152ce882313ab3f505995534",
          "md5": "fa49a030a833d31128177462514c3429"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+41-sources.jar",
          "url": "uno-0.7.9+41-sources.jar",
          "size": 261,
          "sha512": "2dc6178548b0c3dd10368a68575c3b857900def2cd09ce99de3e76b5f8c60cac58780b7e33467db2c66a9d19dda6fad61ba37fe739c05c643ae4ba3a2eeaf487",
          "sha256": "306fa808d68175c209181a6c0fa19d486f6fa6f4016d4f322a7a317ca136908f",
          "sha1": "1b0e623a93a7dd588d54c2a4e573aaecf6026124",
          "md5": "7b4e5093bf9ad0f12b8256856e03c16f"
        }
      ]
    }
  ]
}
