{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.2+15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "x4q6qzmixrhefnmup45j4aroha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gln-0.5.2+15.jar",
          "url": "gln-0.5.2+15.jar",
          "size": 967267,
          "sha512": "fcf31be45f5c40bffb9d41588eb1140c8c87f6b2b3498ceb6bb8ce9c0f4945e49b9f2dcd3023c454a851115bcb986eeacc5bb4c60319d25b7476cf9eb63f78e9",
          "sha256": "690bfc7c47757117e9533f578c2adbc29af3a195c46dece825dbe6fb3049ad37",
          "sha1": "9d8d29c1b665a8c74532b24453eb3a61c37a6411",
          "md5": "a9e51ad59d5650fab5817cc834f8006a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+33"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+15.jar",
          "url": "gln-0.5.2+15.jar",
          "size": 967267,
          "sha512": "fcf31be45f5c40bffb9d41588eb1140c8c87f6b2b3498ceb6bb8ce9c0f4945e49b9f2dcd3023c454a851115bcb986eeacc5bb4c60319d25b7476cf9eb63f78e9",
          "sha256": "690bfc7c47757117e9533f578c2adbc29af3a195c46dece825dbe6fb3049ad37",
          "sha1": "9d8d29c1b665a8c74532b24453eb3a61c37a6411",
          "md5": "a9e51ad59d5650fab5817cc834f8006a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+15-all.jar",
          "url": "gln-0.5.2+15-all.jar",
          "size": 12975401,
          "sha512": "bdf359f50a86d2ba3bca332450f836b9d6cdbc96c050e18fb77c618f177b20acc9ed9eeff8116dd703069e9848cedcddd1adc51953f14ea1d28ce8233bf9d2c5",
          "sha256": "c54542260125b0cc73922a217cf03b89529dcfce65775dc5877de92b5a5fb1bb",
          "sha1": "34b2770d755ed690ab296433a4ba1c911b976efc",
          "md5": "d25aa27fa2ccab6f5401b7b97d5c994b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+15-sources.jar",
          "url": "gln-0.5.2+15-sources.jar",
          "size": 263116,
          "sha512": "c9d01b07c09ae16598dc6ac9edf11401b2f91903ccbc1fa7aa9d136c72710705a754d479bb7ff0abecd967eaf7a66fe336f507fe5d412732e9dea632fd04b908",
          "sha256": "29cfeea485e55f8dc1133680df803f52f90a74d410e939f88d5e89d4d430fea7",
          "sha1": "d37f53538af92aa95f0bf22101facf8add393141",
          "md5": "31127eaa3c19e99ca788dfeac0d85023"
        }
      ]
    }
  ]
}
