{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.16.jar",
          "url": "uno-0.7.16.jar",
          "size": 261,
          "sha512": "f385312249e1b6e60b41140a8e557d9aa6a1a3ffbe2546fa62b9892ea1d6db8e1d228cbd7658be1744315ef9247915b66de21d94fc0910f32b35f070e0f7e6ef",
          "sha256": "7b3a745de9bf98c0655d8020951251ad4dffe7d00e49155a08770a87c27d9df4",
          "sha1": "3e78cbdcc778b6de80c9eb3117ebb1b11e1049b8",
          "md5": "8ea461764620e17718a98ac100f8c13c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.16.jar",
          "url": "uno-0.7.16.jar",
          "size": 261,
          "sha512": "f385312249e1b6e60b41140a8e557d9aa6a1a3ffbe2546fa62b9892ea1d6db8e1d228cbd7658be1744315ef9247915b66de21d94fc0910f32b35f070e0f7e6ef",
          "sha256": "7b3a745de9bf98c0655d8020951251ad4dffe7d00e49155a08770a87c27d9df4",
          "sha1": "3e78cbdcc778b6de80c9eb3117ebb1b11e1049b8",
          "md5": "8ea461764620e17718a98ac100f8c13c"
        }
      ]
    }
  ]
}
