{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "glm",
    "version": "0.9.9.1-3+27++29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+27.jar",
          "url": "glm-0.9.9.1-3+27.jar",
          "size": 2178981,
          "sha512": "dd17cd2cf63b490ecc09bcf146c594c89fcaa4865e515549e33aaf7a4875901f8c650118d036c36576203c9086008c198ad729d7830f648cb6f6ba8c9e8248af",
          "sha256": "eb35ec65bc2ca123c77517f02c71443e76375302fc85fa5dcc7c48f2d6c0a3d4",
          "sha1": "acfbb477b20d9ab51f8b33b589505d688f8a4178",
          "md5": "b04d08794550e463f9b8391ab306c3c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+27.jar",
          "url": "glm-0.9.9.1-3+27.jar",
          "size": 2178981,
          "sha512": "dd17cd2cf63b490ecc09bcf146c594c89fcaa4865e515549e33aaf7a4875901f8c650118d036c36576203c9086008c198ad729d7830f648cb6f6ba8c9e8248af",
          "sha256": "eb35ec65bc2ca123c77517f02c71443e76375302fc85fa5dcc7c48f2d6c0a3d4",
          "sha1": "acfbb477b20d9ab51f8b33b589505d688f8a4178",
          "md5": "b04d08794550e463f9b8391ab306c3c3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+27-all.jar",
          "url": "glm-0.9.9.1-3+27-all.jar",
          "size": 7307200,
          "sha512": "cb1f9566fcdd650313682773da165bd0712699369315e4a0646605a1ec24a3c8e47c97667c0506e7b8da571a78aeee21c834335d56fb59cc6f348465b6a0728a",
          "sha256": "5fdaee3f876361fdd481d763981b94c409997ba386c4c56abba75c42e12b039c",
          "sha1": "254fb66435d72af19b501ae87cdb287e3c65a4b8",
          "md5": "c7626ef19c388ea99e6c514ffb48f7c5"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+27-jdk8.jar",
          "url": "glm-0.9.9.1-3+27-jdk8.jar",
          "size": 2165057,
          "sha512": "5b8763a9bf7f2d1d4215ec12426ec8e3e70260d2b26aa9761f95059d1490b9050685e4f8558940eb362fc5d720d3ee841d22b37f5c75eec202936f2e49333de0",
          "sha256": "0474637a7d3cddaf5316034bc8fb215a4380cd694890b0c64645b65c766b3843",
          "sha1": "0085aefe776f37122643336a7eb8e600fa599773",
          "md5": "2159e5454252417541cbea3f95fdf7e5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-3+27"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+27-jdk8.jar",
          "url": "glm-0.9.9.1-3+27-jdk8.jar",
          "size": 2165057,
          "sha512": "5b8763a9bf7f2d1d4215ec12426ec8e3e70260d2b26aa9761f95059d1490b9050685e4f8558940eb362fc5d720d3ee841d22b37f5c75eec202936f2e49333de0",
          "sha256": "0474637a7d3cddaf5316034bc8fb215a4380cd694890b0c64645b65c766b3843",
          "sha1": "0085aefe776f37122643336a7eb8e600fa599773",
          "md5": "2159e5454252417541cbea3f95fdf7e5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-3+27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+27-sources.jar",
          "url": "glm-0.9.9.1-3+27-sources.jar",
          "size": 424754,
          "sha512": "4ccf5ef866e92eab2322a6d2238833420162dee9a64eacde79be8db0863605f17e71ede8f0fb3779934394477981d03adec8353da4eac871b8b3650e4ac7afc8",
          "sha256": "cd1a44b9b1236d0f44b1c6532b484418af6051a7f233397ce6a4e81d325d3cae",
          "sha1": "0f632d5b0239faf7b34d21c71c4b777b05f4c29a",
          "md5": "c35e735d75754b88b8d4a0516e76ed11"
        }
      ]
    }
  ]
}
