{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "unsigned",
    "version": "3.3.1+5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "unsigned-3.3.1+5.jar",
          "url": "unsigned-3.3.1+5.jar",
          "size": 47986,
          "sha512": "f17f9f38542ed1794db8e20591c293d599741a6262af12a5e697c87a3df948e76afd39d813aace4ad243f93c29a5fcead8cdfe35063ecc8f33f4248e22df8584",
          "sha256": "548fdd6da256e20f84fa5d176627d0866c01194b3744653d58a39529fdc7abe4",
          "sha1": "80cd66b166d624b3b4ad279db61ed2180d571d2e",
          "md5": "6902ffc77283ccdf9d91d163e8fdaefb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "unsigned-3.3.1+5.jar",
          "url": "unsigned-3.3.1+5.jar",
          "size": 47986,
          "sha512": "f17f9f38542ed1794db8e20591c293d599741a6262af12a5e697c87a3df948e76afd39d813aace4ad243f93c29a5fcead8cdfe35063ecc8f33f4248e22df8584",
          "sha256": "548fdd6da256e20f84fa5d176627d0866c01194b3744653d58a39529fdc7abe4",
          "sha1": "80cd66b166d624b3b4ad279db61ed2180d571d2e",
          "md5": "6902ffc77283ccdf9d91d163e8fdaefb"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "unsigned-3.3.1+5-jdk8.jar",
          "url": "unsigned-3.3.1+5-jdk8.jar",
          "size": 47857,
          "sha512": "012ddcd6de2c69ad49a181fbaf5822d244d1206bbafb08a7ab8269f4328c6b3bb363af5b6ee1f2ea0296176fef24c88acc1d3406d389da0eb065f6dfabd76304",
          "sha256": "e5d183f6c1dbb64e0de5a48fe4290ddf3233b2a12e8ac69f8b04e1552bcaf9b1",
          "sha1": "bb348cab32117078b7f2bc98db5efa22845a3b8d",
          "md5": "be730b8b67ee59a0fc55a6a0453e0dd4"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "unsigned",
          "version": "3.3.1+5"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "unsigned-3.3.1+5-jdk8.jar",
          "url": "unsigned-3.3.1+5-jdk8.jar",
          "size": 47857,
          "sha512": "012ddcd6de2c69ad49a181fbaf5822d244d1206bbafb08a7ab8269f4328c6b3bb363af5b6ee1f2ea0296176fef24c88acc1d3406d389da0eb065f6dfabd76304",
          "sha256": "e5d183f6c1dbb64e0de5a48fe4290ddf3233b2a12e8ac69f8b04e1552bcaf9b1",
          "sha1": "bb348cab32117078b7f2bc98db5efa22845a3b8d",
          "md5": "be730b8b67ee59a0fc55a6a0453e0dd4"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "unsigned",
          "version": "3.3.1+5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unsigned-3.3.1+5-sources.jar",
          "url": "unsigned-3.3.1+5-sources.jar",
          "size": 9478,
          "sha512": "3408abc198aa923d2aec158a5f26e7e35da836c512f4f73b746bddd2657bb23bbf962d473c0c766b06de16a672dae0af8c6ae59cc04b9b5becca8a27fbc18e6e",
          "sha256": "254cb544845fe40cce61ca69936b91011e7c53eb404f3dc92badc0067aedd7c6",
          "sha1": "bb1162aec719912d19758dd22b459b725ba38020",
          "md5": "a62a666ba4181d9c0abbd1e267dbbef2"
        }
      ]
    }
  ]
}
