{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zhovj4en2fczhcbhfi4x7xffgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+87.jar",
          "url": "commons-0.7.0+87.jar",
          "size": 366085,
          "sha512": "9a5bb4a577760bd8a4d779a06288da84fd7d1b077c5eb73c4d2b9d42f6ad05e808dee380fc805e3fa0dff54668ae34d75e2c9d72437c4e427679f0ca23ab15b2",
          "sha256": "e36c3c80ce262d35ace0ed84d82dac0e39448212bd833e8c6869a4a1ac1f1d2f",
          "sha1": "c4474a900b3bed6b2312045e50e9610d120acba9",
          "md5": "757a8f99d188e5444195f82432ea9da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+87"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+87.jar",
          "url": "commons-0.7.0+87.jar",
          "size": 366085,
          "sha512": "9a5bb4a577760bd8a4d779a06288da84fd7d1b077c5eb73c4d2b9d42f6ad05e808dee380fc805e3fa0dff54668ae34d75e2c9d72437c4e427679f0ca23ab15b2",
          "sha256": "e36c3c80ce262d35ace0ed84d82dac0e39448212bd833e8c6869a4a1ac1f1d2f",
          "sha1": "c4474a900b3bed6b2312045e50e9610d120acba9",
          "md5": "757a8f99d188e5444195f82432ea9da0"
        }
      ]
    }
  ]
}
