{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-vk",
    "version": "0.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-vk-0.7.10.jar",
          "url": "uno-vk-0.7.10.jar",
          "size": 4061,
          "sha512": "b5e0bc1d042b538f841a16c5e72da9282eafec5efbe02bb97de3967b2ed608962a750cd1ce095bfdbe1d9341981876b47276a1f1e963aa2110f8f352de731927",
          "sha256": "8f8b1d867de28ab02612c66a5d66d70a59254deb23e8ae7f02f0e26bfa3e1d26",
          "sha1": "e429a453945cf0d0dda9e3335cad3ead7ba90d47",
          "md5": "fc124f2d8d74f6c0d7c508e2ad3a3c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-vk-0.7.10.jar",
          "url": "uno-vk-0.7.10.jar",
          "size": 4061,
          "sha512": "b5e0bc1d042b538f841a16c5e72da9282eafec5efbe02bb97de3967b2ed608962a750cd1ce095bfdbe1d9341981876b47276a1f1e963aa2110f8f352de731927",
          "sha256": "8f8b1d867de28ab02612c66a5d66d70a59254deb23e8ae7f02f0e26bfa3e1d26",
          "sha1": "e429a453945cf0d0dda9e3335cad3ead7ba90d47",
          "md5": "fc124f2d8d74f6c0d7c508e2ad3a3c28"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-vk-0.7.10-jdk8.jar",
          "url": "uno-vk-0.7.10-jdk8.jar",
          "size": 3727,
          "sha512": "5ad377deab032e955101b57a0206bed75c9f2c2945a7921b25d6cdad2fac9f6c2be61c541ae17010ac85a249a94edd81954063aad4135c7456917a432c7dbad5",
          "sha256": "70eb2300046ace11d106f1dc20004995eef545d290f40b2f8c59d2faa6a3e639",
          "sha1": "9684099825d1fb9272a0e12931c774c6baf62eda",
          "md5": "2db3f398597c3e88d81f5994c9df4b67"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.10"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-vk-0.7.10-jdk8.jar",
          "url": "uno-vk-0.7.10-jdk8.jar",
          "size": 3727,
          "sha512": "5ad377deab032e955101b57a0206bed75c9f2c2945a7921b25d6cdad2fac9f6c2be61c541ae17010ac85a249a94edd81954063aad4135c7456917a432c7dbad5",
          "sha256": "70eb2300046ace11d106f1dc20004995eef545d290f40b2f8c59d2faa6a3e639",
          "sha1": "9684099825d1fb9272a0e12931c774c6baf62eda",
          "md5": "2db3f398597c3e88d81f5994c9df4b67"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-vk-0.7.10-sources.jar",
          "url": "uno-vk-0.7.10-sources.jar",
          "size": 1268,
          "sha512": "cc19dc0b2b68082663c94d658f00372bd5915103864ca340c3d61df6e9534868b6c9e193d0a290eb82bc5f55b52767e75b329722113d7aff0f441822532322d8",
          "sha256": "e969aace9bb4f73ea184902ac2640a00d8d3de11591160080e0533c182a08372",
          "sha1": "208da445d4153f644787ec2ab04b0e5f609bdb96",
          "md5": "e1c9209e1c6efe62bf822d1034822044"
        }
      ]
    }
  ]
}
