{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "dev",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dev-0.0.3.jar",
          "url": "dev-0.0.3.jar",
          "size": 25084,
          "sha512": "ac424d2518cc5fb0ee75cf0fa6ede6076f4a232cd0142dc3b8c5c62c28197397e9eff8b28e079b885286c7d8bf98520a006b692f4374de74f83628ef5293e447",
          "sha256": "8d17553ed7e7a249e1a8622b6a19664eabfc0fcbe837e596fbc951a187a39f98",
          "sha1": "9898b98b28e9b5d1a3c525aafed3dda1cade00a5",
          "md5": "150a5f3b7e12fe9b63d86bc38aecbc93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dev-0.0.3.jar",
          "url": "dev-0.0.3.jar",
          "size": 25084,
          "sha512": "ac424d2518cc5fb0ee75cf0fa6ede6076f4a232cd0142dc3b8c5c62c28197397e9eff8b28e079b885286c7d8bf98520a006b692f4374de74f83628ef5293e447",
          "sha256": "8d17553ed7e7a249e1a8622b6a19664eabfc0fcbe837e596fbc951a187a39f98",
          "sha1": "9898b98b28e9b5d1a3c525aafed3dda1cade00a5",
          "md5": "150a5f3b7e12fe9b63d86bc38aecbc93"
        }
      ]
    }
  ]
}
