{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+28.jar",
          "url": "commons-0.7.0+28.jar",
          "size": 325124,
          "sha512": "1ef147ed024aab52a3898aa69f76f320a78288e62e55916e121d3dce2c7017f2b3169060243ffa9670ebcf34e8b3bb7a20f1e259f73e44ed15d7a6f7000eb08d",
          "sha256": "7657a62c137029188fbee987c80177e2ba3c0632d894f3552f6ed94d518e0711",
          "sha1": "66750fb65ed495056d9c3a14fb1c3e50f75b4d1e",
          "md5": "6bcb7df73f169a5d103ff069bae5a377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+28"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+28"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+28.jar",
          "url": "commons-0.7.0+28.jar",
          "size": 325124,
          "sha512": "1ef147ed024aab52a3898aa69f76f320a78288e62e55916e121d3dce2c7017f2b3169060243ffa9670ebcf34e8b3bb7a20f1e259f73e44ed15d7a6f7000eb08d",
          "sha256": "7657a62c137029188fbee987c80177e2ba3c0632d894f3552f6ed94d518e0711",
          "sha1": "66750fb65ed495056d9c3a14fb1c3e50f75b4d1e",
          "md5": "6bcb7df73f169a5d103ff069bae5a377"
        }
      ]
    }
  ]
}
