{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.2.jar",
          "url": "kool-0.9.2.jar",
          "size": 265236,
          "sha512": "586030724e7e2a29b852b4f27a291c58d903af52e9e721a87fb14ea03cc84632f2a78394a06de60ce4fef6a2d5c48d43bf7541d74d2f2656391d314f47ea1a8a",
          "sha256": "33f670789bc66766a876a7a684ef34725a3be6ff125cba3794a11e734db784fd",
          "sha1": "0ac7d6e69a90cad332ae022d56dabebd8d378e73",
          "md5": "72bfbb8f4c34432affddfdcff8da4c9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.2.jar",
          "url": "kool-0.9.2.jar",
          "size": 265236,
          "sha512": "586030724e7e2a29b852b4f27a291c58d903af52e9e721a87fb14ea03cc84632f2a78394a06de60ce4fef6a2d5c48d43bf7541d74d2f2656391d314f47ea1a8a",
          "sha256": "33f670789bc66766a876a7a684ef34725a3be6ff125cba3794a11e734db784fd",
          "sha1": "0ac7d6e69a90cad332ae022d56dabebd8d378e73",
          "md5": "72bfbb8f4c34432affddfdcff8da4c9c"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kool-0.9.2-jdk8.jar",
          "url": "kool-0.9.2-jdk8.jar",
          "size": 264841,
          "sha512": "ae0195b71d72c582eb3f15cbf6ccffea1901f7bf70ebbc376167ff4428561ae343d770cf8866f94fb7086ef3457468084f840ced5bc25b99885a9b4fee5cc78c",
          "sha256": "667db16df2eb44231adc0a57ccdb515804d7776e316e6fb9c8673ce64bc5d4cb",
          "sha1": "df484df16d8a563f1cf8610147b559b3c9445274",
          "md5": "916270d5ea9f720cdbd0f88187dc2c9e"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "kool",
          "version": "0.9.2"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.2-jdk8.jar",
          "url": "kool-0.9.2-jdk8.jar",
          "size": 264841,
          "sha512": "ae0195b71d72c582eb3f15cbf6ccffea1901f7bf70ebbc376167ff4428561ae343d770cf8866f94fb7086ef3457468084f840ced5bc25b99885a9b4fee5cc78c",
          "sha256": "667db16df2eb44231adc0a57ccdb515804d7776e316e6fb9c8673ce64bc5d4cb",
          "sha1": "df484df16d8a563f1cf8610147b559b3c9445274",
          "md5": "916270d5ea9f720cdbd0f88187dc2c9e"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "kool",
          "version": "0.9.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.2-sources.jar",
          "url": "kool-0.9.2-sources.jar",
          "size": 47050,
          "sha512": "eb25cca7368b4ae6c28e3242b729b5c3aa6f469b38d4d443b8630d9910b92271b1ad372410b3e808099ca847f7dacf2fa0f93d720c957a1c785ea49caa15882d",
          "sha256": "f210378aeafd9b26d9d34380350ccfea50f11f525ab7aefcdd24498741a8bd26",
          "sha1": "45cb883c9615f88bb4d515af8f866bd1d7f33c14",
          "md5": "2adfb727edc830baaffdcb18401b9326"
        }
      ]
    }
  ]
}
