{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-awt",
    "version": "0.7.9+35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+35.jar",
          "url": "uno-awt-0.7.9+35.jar",
          "size": 20348,
          "sha512": "5cf1612aa353a36aaee3237eb424b129f635aad84acef2b3d1372b959393a90ea04b30695297fd2a4ff0e94a2ef1c042d1a5cdfd2220754a402a5d9b4018ed09",
          "sha256": "d7857918a01ba530d4bffc4be53e77db406bd9af566c2442a0ace8cf1dbf2de5",
          "sha1": "7a60c54421581d2864d850c8252278fa5fc06fae",
          "md5": "16f301c5a43a4d2a5e8451e4beafec0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+44"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+35"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+35.jar",
          "url": "uno-awt-0.7.9+35.jar",
          "size": 20348,
          "sha512": "5cf1612aa353a36aaee3237eb424b129f635aad84acef2b3d1372b959393a90ea04b30695297fd2a4ff0e94a2ef1c042d1a5cdfd2220754a402a5d9b4018ed09",
          "sha256": "d7857918a01ba530d4bffc4be53e77db406bd9af566c2442a0ace8cf1dbf2de5",
          "sha1": "7a60c54421581d2864d850c8252278fa5fc06fae",
          "md5": "16f301c5a43a4d2a5e8451e4beafec0a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+35-all.jar",
          "url": "uno-awt-0.7.9+35-all.jar",
          "size": 13186057,
          "sha512": "6fc1b1017df084b7c92f458b967d3b74edd4b17a6e8a809fbc8b7550188053130dff75b7ffb8812f023329ed79bf2a9bd85c633e8cbb6ef645a570eeeb089a56",
          "sha256": "6fdb62318573f01be0bda988d3e8aa2cad6b452499d859fc5c90ad7676eeb889",
          "sha1": "2e442322d039a1ec5fcf1b9c622b65d927a5bba8",
          "md5": "5620fe7418640697d24447ee1a302349"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+35-sources.jar",
          "url": "uno-awt-0.7.9+35-sources.jar",
          "size": 3974,
          "sha512": "f7d847832e7473fd6bd7bf9bb4a73ceb1f4f442dc3619054de00634f73972d5e68c8396f2fd9d3bad5d227157e2c1a7dcedf07aa827f32f63adb4b6b4a014f82",
          "sha256": "218428f1a1da7b06c99c399ad6ceec2cfc3898a0db0d065cc861a83706c8f6bb",
          "sha1": "c41b26cdacefb1a717f33c7ae5945b6ccb29a419",
          "md5": "8455571db15f6e0705818d03c44e9bea"
        }
      ]
    }
  ]
}
