{
  "formatVersion": "1.1",
  "component": {
    "group": "kx.build-logic",
    "module": "impl",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "impl-0.6.3.jar",
          "url": "impl-0.6.3.jar",
          "size": 157118,
          "sha512": "b30272d1b98be9722df0e48295e74778f47a356f415a278a3ac5d2fbee6f7ea7820a7026c8c200defa8d374e3fcd2d7b51af76a35fdc8bcb902b800a9e99444a",
          "sha256": "42893bb5c5df79edc5294580292b189a2ef47f38fb3deadcb1c94ad33bf594ef",
          "sha1": "0350c50bfa9d58e4caf535bf92cea3f48dc8a59e",
          "md5": "af6512ff37f4fef86b3353a0f8ae94e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "impl-0.6.3.jar",
          "url": "impl-0.6.3.jar",
          "size": 157118,
          "sha512": "b30272d1b98be9722df0e48295e74778f47a356f415a278a3ac5d2fbee6f7ea7820a7026c8c200defa8d374e3fcd2d7b51af76a35fdc8bcb902b800a9e99444a",
          "sha256": "42893bb5c5df79edc5294580292b189a2ef47f38fb3deadcb1c94ad33bf594ef",
          "sha1": "0350c50bfa9d58e4caf535bf92cea3f48dc8a59e",
          "md5": "af6512ff37f4fef86b3353a0f8ae94e4"
        }
      ]
    }
  ]
}
