{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+56.jar",
          "url": "commons-0.7.0+56.jar",
          "size": 359208,
          "sha512": "a30fda78c34554c2a0c4269c5f0cd5d7e69f3b9defd1f9be2629982a5e0650c22015ed65f07f8b0096e6d5e3436e9abd6a300c620e65ae4d02d61f923c2e94cf",
          "sha256": "ba728a947a205ce2c41b9ad763a5b3fce92c16da246bd6309d89373d751d6236",
          "sha1": "749a3a1f5549d1b8564aed0664126acc67e33e85",
          "md5": "00aee43b3b3ada43d71b1b1bd31f00dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+56"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+56.jar",
          "url": "commons-0.7.0+56.jar",
          "size": 359208,
          "sha512": "a30fda78c34554c2a0c4269c5f0cd5d7e69f3b9defd1f9be2629982a5e0650c22015ed65f07f8b0096e6d5e3436e9abd6a300c620e65ae4d02d61f923c2e94cf",
          "sha256": "ba728a947a205ce2c41b9ad763a5b3fce92c16da246bd6309d89373d751d6236",
          "sha1": "749a3a1f5549d1b8564aed0664126acc67e33e85",
          "md5": "00aee43b3b3ada43d71b1b1bd31f00dc"
        }
      ]
    }
  ]
}
