{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-gl",
    "version": "0.7.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.19.jar",
          "url": "uno-gl-0.7.19.jar",
          "size": 3205,
          "sha512": "e6eca193a3cfc2abbf7228a2b0a58f3437b3e588003a49f29105a60b349c256f07319210ed9795a8e383b0d9229ccbbe38ae00f2e1e452eaac90cfb63bd02fb3",
          "sha256": "f14db297f57e9e21ce67a56dee0816e23355805d7fd1be32aadb6a05832d62ee",
          "sha1": "c7f92f6cddc249949b4ce6cfe4c65e822ac17010",
          "md5": "8e870dadd49204d64db31546e03ab11d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.19"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.19.jar",
          "url": "uno-gl-0.7.19.jar",
          "size": 3205,
          "sha512": "e6eca193a3cfc2abbf7228a2b0a58f3437b3e588003a49f29105a60b349c256f07319210ed9795a8e383b0d9229ccbbe38ae00f2e1e452eaac90cfb63bd02fb3",
          "sha256": "f14db297f57e9e21ce67a56dee0816e23355805d7fd1be32aadb6a05832d62ee",
          "sha1": "c7f92f6cddc249949b4ce6cfe4c65e822ac17010",
          "md5": "8e870dadd49204d64db31546e03ab11d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-gl-0.7.19-sources.jar",
          "url": "uno-gl-0.7.19-sources.jar",
          "size": 1515,
          "sha512": "657a79d5e05f8a4c4b709b232f4d9ed60e0b5686e4066ec26b024c94fb2eeb2a4689e5a9723bb855a09139bcf65a778c9284d9b1b7c1424128523553c40624af",
          "sha256": "e378f24d4451198f0f3a73f4f0f4ed585565d6061b75e05f319b30cb59557157",
          "sha1": "81704da086a5abfeab014e806b7456348c7aa652",
          "md5": "680f3ddc2da046fbea9d54b5d459cf1d"
        }
      ]
    }
  ]
}
