{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-glfw",
    "version": "1.89.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.7.jar",
          "url": "imgui-glfw-1.89.7.jar",
          "size": 42952,
          "sha512": "1cccc6d2831ba49d321d2fa530dbeec35fb4577852c8882ae95a1085104768b319e8ee6ca7633d0dc1d6e96ab23ca38933a3a0074df49ade6961f7dccc2fbe64",
          "sha256": "d59958f0b31599e79716a84fd50ecfd82eaeecf9eb12ba7b5311870537944624",
          "sha1": "865482e4812f93b1e425b5c760c819f69f4a327d",
          "md5": "b358b35c3e2904ca494949943c121ff6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.7"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.7.jar",
          "url": "imgui-glfw-1.89.7.jar",
          "size": 42952,
          "sha512": "1cccc6d2831ba49d321d2fa530dbeec35fb4577852c8882ae95a1085104768b319e8ee6ca7633d0dc1d6e96ab23ca38933a3a0074df49ade6961f7dccc2fbe64",
          "sha256": "d59958f0b31599e79716a84fd50ecfd82eaeecf9eb12ba7b5311870537944624",
          "sha1": "865482e4812f93b1e425b5c760c819f69f4a327d",
          "md5": "b358b35c3e2904ca494949943c121ff6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-glfw-1.89.7-sources.jar",
          "url": "imgui-glfw-1.89.7-sources.jar",
          "size": 8852,
          "sha512": "4a57d13e1db66c0f589f1afd60c0b9b6ae79f8ddba9b06279a56225cbc110cc965d7b121236ba08b0db16c35af73259bbb1063af568170c9902d9c2ebfdd4132",
          "sha256": "c478c9681524220745c152468237ede311842f1188ede0626abb8c4c8fdcf40b",
          "sha1": "05ed8808fce0f26caab218cccfc8ce3959d09c8d",
          "md5": "1521a7883d23be3af2a184ce619d9116"
        }
      ]
    }
  ]
}
