{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "e62sehrv6ncbhie77xjqtphojy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+76.jar",
          "url": "commons-0.7.0+76.jar",
          "size": 348672,
          "sha512": "ac50ac5b14b61df1846f43266811f1657728b1b0da2d8cee3465e3cc6085cc2cab4805f28c6feff53b46ae58c908b3d5745db91c9110d407e63e7e513b17295d",
          "sha256": "2b68d53cf4592a0a770a121a80589e2b19b2945d6f76b6173874ea4885e52745",
          "sha1": "7d1b237ed4674af5918ab6bda777d577f4f0415b",
          "md5": "ccfd5e76949de49d480730a81f37b4da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+76"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+76.jar",
          "url": "commons-0.7.0+76.jar",
          "size": 348672,
          "sha512": "ac50ac5b14b61df1846f43266811f1657728b1b0da2d8cee3465e3cc6085cc2cab4805f28c6feff53b46ae58c908b3d5745db91c9110d407e63e7e513b17295d",
          "sha256": "2b68d53cf4592a0a770a121a80589e2b19b2945d6f76b6173874ea4885e52745",
          "sha1": "7d1b237ed4674af5918ab6bda777d577f4f0415b",
          "md5": "ccfd5e76949de49d480730a81f37b4da"
        }
      ]
    }
  ]
}
