{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-openjfx",
    "version": "1.79+04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "imgui-openjfx-1.79+04.jar",
          "url": "imgui-openjfx-1.79+04.jar",
          "size": 44115,
          "sha512": "9b70bf4f877a451969577d5d6d60be3535ccafa306595df05d799dca80f7f99ab7112987ecd3f93106a0a83e399a7a51768d3136e1cf314c790343982412317d",
          "sha256": "9de462feeb3ca16862ac48b0107ab11250050205b2983929168abe4554512db0",
          "sha1": "ed6a1eb199e996e52545f07cf4c8faaa5ca493f0",
          "md5": "902ed01fc08d4dd8557535fc353e4f0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+46"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.79+04"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "11"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "11"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-openjfx-1.79+04.jar",
          "url": "imgui-openjfx-1.79+04.jar",
          "size": 44115,
          "sha512": "9b70bf4f877a451969577d5d6d60be3535ccafa306595df05d799dca80f7f99ab7112987ecd3f93106a0a83e399a7a51768d3136e1cf314c790343982412317d",
          "sha256": "9de462feeb3ca16862ac48b0107ab11250050205b2983929168abe4554512db0",
          "sha1": "ed6a1eb199e996e52545f07cf4c8faaa5ca493f0",
          "md5": "902ed01fc08d4dd8557535fc353e4f0a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-openjfx-1.79+04-all.jar",
          "url": "imgui-openjfx-1.79+04-all.jar",
          "size": 36310158,
          "sha512": "648412ca139ab7ddee6adaab70dd38664e4ac8bd497670a259201cf1a2a80914e26166c7dcedb6b40befb985e70abc8fe15e00bbd90605ba2f37fcd2e55b5eae",
          "sha256": "93d32486734ab1855fbb19284a6a87e3c29bdc193a9fe027871089e443d59cb6",
          "sha1": "876dbe1efd2ba79752d4789d996df5862d3b8138",
          "md5": "6fc4a33a7872b3c8c7c8601a36818b3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-openjfx-1.79+04-sources.jar",
          "url": "imgui-openjfx-1.79+04-sources.jar",
          "size": 9271,
          "sha512": "6d6b70c8da576d9da84918c5773fa94abdeafc84206f236a9dd83d2b919ab0d8633f0ac3280d7bc4ba14597e4b04ad80bbab80d46d24dfac3818384cc4147225",
          "sha256": "e2c10095545b203dabaa95b0394f07dd5aff93094f18a16fcb9eb4db07d67398",
          "sha1": "d75b8b7147b8e41edbf09a75eba1bdb2b039848b",
          "md5": "d8ad84440b7c7c8a4ad580016fea2577"
        }
      ]
    }
  ]
}
