{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m4zrcqnvsbenvoprz6t7viu4ve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+99.jar",
          "url": "docs-0.7.0+99.jar",
          "size": 424997,
          "sha512": "57108b0f22ac1a81a94c0fdfdc93c1996b45492af37595ff02967ecd970ad02ee7ab3183aa81610323a89318de7ef9542ebadab2096275efa2eed75415068eb9",
          "sha256": "f8a356543936f65a04e50ff6e8b6defc19f5aa167b18a2bdc7ca5e7c7750ec28",
          "sha1": "c2183d8b32f9511f1877f724cb32893250baa6aa",
          "md5": "0f8d7c446a5fd508dfa8080ba9ab3468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+99.jar",
          "url": "docs-0.7.0+99.jar",
          "size": 424997,
          "sha512": "57108b0f22ac1a81a94c0fdfdc93c1996b45492af37595ff02967ecd970ad02ee7ab3183aa81610323a89318de7ef9542ebadab2096275efa2eed75415068eb9",
          "sha256": "f8a356543936f65a04e50ff6e8b6defc19f5aa167b18a2bdc7ca5e7c7750ec28",
          "sha1": "c2183d8b32f9511f1877f724cb32893250baa6aa",
          "md5": "0f8d7c446a5fd508dfa8080ba9ab3468"
        }
      ]
    }
  ]
}
