{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "v0.7.0-18-fcd9cbf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-v0.7.0-18-fcd9cbf.jar",
          "url": "commons-v0.7.0-18-fcd9cbf.jar",
          "size": 325144,
          "sha512": "82970a16a788c3a58f805d385e23b79b71672afddcbca598bd65dc9da66c8a9dd5c4ec7f8f05f15b1a55db5b489ce0b11a94fd6f9783f42983462423a8714302",
          "sha256": "c475bafabf686a999ad8e3517f4c1bdcff6ba567dc4e9da0b090bb78cdc390fe",
          "sha1": "12fa1ea020b991fd3a1665340fc7170c76a36f7f",
          "md5": "ad82032fc1cce7766bcdac3c4b3569a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-18-fcd9cbf"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "v0.7.0-18-fcd9cbf"
          }
        }
      ],
      "files": [
        {
          "name": "commons-v0.7.0-18-fcd9cbf.jar",
          "url": "commons-v0.7.0-18-fcd9cbf.jar",
          "size": 325144,
          "sha512": "82970a16a788c3a58f805d385e23b79b71672afddcbca598bd65dc9da66c8a9dd5c4ec7f8f05f15b1a55db5b489ce0b11a94fd6f9783f42983462423a8714302",
          "sha256": "c475bafabf686a999ad8e3517f4c1bdcff6ba567dc4e9da0b090bb78cdc390fe",
          "sha1": "12fa1ea020b991fd3a1665340fc7170c76a36f7f",
          "md5": "ad82032fc1cce7766bcdac3c4b3569a7"
        }
      ]
    }
  ]
}
