{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-gl",
    "version": "1.89.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.19"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.2.jar",
          "url": "imgui-gl-1.89.2.jar",
          "size": 47462,
          "sha512": "4996122cbd2eba8e9c6d41db9dcee3c51e39812c9f6b344ab8d8aef5e9c8150b4271eeeddd4fe76a087cf688fa1dacb6372696e85d2ce6a598627b906c1480f6",
          "sha256": "2ee7b27bdd19af40837f0b2c629ffeecc2a878184984a02f0f99bb9a06418b64",
          "sha1": "f9cc590576cc787e16b889216dddadd39f0aca8c",
          "md5": "67cdfdc209bc4fcb67e5e16e6c772f71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-glfw",
          "version": {
            "requires": "1.89.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.19"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.2.jar",
          "url": "imgui-gl-1.89.2.jar",
          "size": 47462,
          "sha512": "4996122cbd2eba8e9c6d41db9dcee3c51e39812c9f6b344ab8d8aef5e9c8150b4271eeeddd4fe76a087cf688fa1dacb6372696e85d2ce6a598627b906c1480f6",
          "sha256": "2ee7b27bdd19af40837f0b2c629ffeecc2a878184984a02f0f99bb9a06418b64",
          "sha1": "f9cc590576cc787e16b889216dddadd39f0aca8c",
          "md5": "67cdfdc209bc4fcb67e5e16e6c772f71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.89.2-sources.jar",
          "url": "imgui-gl-1.89.2-sources.jar",
          "size": 15261,
          "sha512": "dd54cc0186c205c71c95c0ff6901055d702963d3668e187386a9f81898ad16000ef80c53dc3580821354b72e17bfa630a3880703880664aa376f1fd4fe7ad06f",
          "sha256": "2d1952e78fae3b2e6ccf2e4e21486eece85889ce4a35cdca080ff67ae8d24c4a",
          "sha1": "66b969c3cc43e8337892fc806573e49e22534623",
          "md5": "fe11fe97aeabae48d08981bbd43fa5d0"
        }
      ]
    }
  ]
}
