{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.2+26++26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+26.jar",
          "url": "gln-0.5.2+26.jar",
          "size": 985426,
          "sha512": "1319de30c8a00305d5aba799ecfeee9c52254513ba0eb2bb6877295bf331a58b43a943c85c1d71b30570a65199ba05ecbd17426c6056caae516606e78bd68f5b",
          "sha256": "623da29f208a6ee897fa14b8ad906535aeb2243261fe07232ef14a298f68d337",
          "sha1": "3a0c12fb5bc0461554ca63313aec04e5744db424",
          "md5": "9dbffe9342ddf24ab433ff88c4b2a7c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+26.jar",
          "url": "gln-0.5.2+26.jar",
          "size": 985426,
          "sha512": "1319de30c8a00305d5aba799ecfeee9c52254513ba0eb2bb6877295bf331a58b43a943c85c1d71b30570a65199ba05ecbd17426c6056caae516606e78bd68f5b",
          "sha256": "623da29f208a6ee897fa14b8ad906535aeb2243261fe07232ef14a298f68d337",
          "sha1": "3a0c12fb5bc0461554ca63313aec04e5744db424",
          "md5": "9dbffe9342ddf24ab433ff88c4b2a7c4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+26-all.jar",
          "url": "gln-0.5.2+26-all.jar",
          "size": 12999472,
          "sha512": "7132ba8591b6080670a1ed6b9ec3eef45912e4b75d3d3182e3552ddf59bc3dd568299e417649da88ca437acf1207fc249cb6d483903feddb93f2af58de770aff",
          "sha256": "a20baf2a46d4d6b80c21610d51eeb9d04ab02e2797b367be715a2cbd80c64116",
          "sha1": "92e94ff3743d21fb41de9b8364405933cc63cce1",
          "md5": "e2596313d9c4734457f0c28becaf4396"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gln-0.5.2+26-jdk8.jar",
          "url": "gln-0.5.2+26-jdk8.jar",
          "size": 980386,
          "sha512": "0caf4a7df08ae9ab945adae854a0d19bc77752dfda4033d4d03811d627f6f0b0e4cfbb5bd50e17745e3250f06975dc70fd4604f3d79c4ab83071add86718bec6",
          "sha256": "adcb706cb354e2657ad7b547b97eb29a87258299bba7422077bb7a91eb282a6b",
          "sha1": "a3d688a115e97bea506e55dfc4b89e13d2347f82",
          "md5": "d7ca2e7bb31b56c1681587a8213b49fc"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.2+26"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+26-jdk8.jar",
          "url": "gln-0.5.2+26-jdk8.jar",
          "size": 980386,
          "sha512": "0caf4a7df08ae9ab945adae854a0d19bc77752dfda4033d4d03811d627f6f0b0e4cfbb5bd50e17745e3250f06975dc70fd4604f3d79c4ab83071add86718bec6",
          "sha256": "adcb706cb354e2657ad7b547b97eb29a87258299bba7422077bb7a91eb282a6b",
          "sha1": "a3d688a115e97bea506e55dfc4b89e13d2347f82",
          "md5": "d7ca2e7bb31b56c1681587a8213b49fc"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.2+26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+26-sources.jar",
          "url": "gln-0.5.2+26-sources.jar",
          "size": 263364,
          "sha512": "1973c096299c653f02ed621f060653453ee811a1f809045a984b63022af9f755c0031f0a97db2b00b72abdb6a9bd9b7f9666d27bda2ad109a452ab6e67fcb359",
          "sha256": "4540502a318dfa761b121d39c979d05a92840045e254c89f3b7a22f2cc7226d8",
          "sha1": "f0eab89b1bd460fb7f809cc82339e1007c870506",
          "md5": "b725a00b68edffe720412d3f9daadc8a"
        }
      ]
    }
  ]
}
