{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6j7pmn4rinen7ms75twgo2clru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+88.jar",
          "url": "lwjgl-0.7.0+88.jar",
          "size": 196037,
          "sha512": "fbec5e8958b7141e02547e321d53889a5a178b6650646ee1c91da1b43d3b53edf918e155d6939a963d2a4523af0f941778e65a97dd1d63fa98c1f46bb65117ff",
          "sha256": "f820ae163f8268250d638280217dc8d0ba288f95306c4d87b6adb1e90245bb3b",
          "sha1": "25b96cdac25b475f331fbd97532951fb134cb26f",
          "md5": "fff856d7c2aaaa9d8472ab334869917d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+88.jar",
          "url": "lwjgl-0.7.0+88.jar",
          "size": 196037,
          "sha512": "fbec5e8958b7141e02547e321d53889a5a178b6650646ee1c91da1b43d3b53edf918e155d6939a963d2a4523af0f941778e65a97dd1d63fa98c1f46bb65117ff",
          "sha256": "f820ae163f8268250d638280217dc8d0ba288f95306c4d87b6adb1e90245bb3b",
          "sha1": "25b96cdac25b475f331fbd97532951fb134cb26f",
          "md5": "fff856d7c2aaaa9d8472ab334869917d"
        }
      ]
    }
  ]
}
