{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-awt",
    "version": "0.7.9+52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+51"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+52.jar",
          "url": "uno-awt-0.7.9+52.jar",
          "size": 19166,
          "sha512": "f319ab9c62725c3909964818a8fe96c0ee833071e3b01d013f6793527cdd354f70ddb931afb6fd3b2241f92f0daab3662002de631e92343ea33aa509fded1c07",
          "sha256": "fb8c40aa5ce8d3d508db168d433f01785c02d5c00f6d49ed201ec35fa103e71b",
          "sha1": "2e8809c683318e4141d4cba20c57570b652500e9",
          "md5": "c427838d435d59d893ac0bb4402aca7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+51"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+52.jar",
          "url": "uno-awt-0.7.9+52.jar",
          "size": 19166,
          "sha512": "f319ab9c62725c3909964818a8fe96c0ee833071e3b01d013f6793527cdd354f70ddb931afb6fd3b2241f92f0daab3662002de631e92343ea33aa509fded1c07",
          "sha256": "fb8c40aa5ce8d3d508db168d433f01785c02d5c00f6d49ed201ec35fa103e71b",
          "sha1": "2e8809c683318e4141d4cba20c57570b652500e9",
          "md5": "c427838d435d59d893ac0bb4402aca7a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+52-all.jar",
          "url": "uno-awt-0.7.9+52-all.jar",
          "size": 13180525,
          "sha512": "1751774e0c61c8b134a2a3db93135f5e6a3e2b5414fed989b962a15fb2e120fa462f3f77e398feead718c5f1fb9022c201379b77f9cffb01d25b43c5872c6c64",
          "sha256": "f8ac4bd546f94cf0ad6370ba1b916659353a7d535f23870a044f4a0e13ba474f",
          "sha1": "82ef67a3c385fddbefa6cea85c958c940f736d2b",
          "md5": "442e3f25e4049240938b38bc3a657af4"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+52-jdk8.jar",
          "url": "uno-awt-0.7.9+52-jdk8.jar",
          "size": 18703,
          "sha512": "f78ba2d9731a903643b6d30ae477a23d0388bf61682a7b48002a91e282396ff0305c0acd174dc5ec7966a528eeff76c783b2b8d936dd3c0c3daf17d676e5173c",
          "sha256": "ec2eb2fe82203b15f2d81e0241204615d8ef32aff163fa22a767a88aaca152b3",
          "sha1": "aad8cddab4f286b20c88961392ac70701451811e",
          "md5": "7e79076c312dcbeae7d073987980682a"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+52"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+51"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+52-jdk8.jar",
          "url": "uno-awt-0.7.9+52-jdk8.jar",
          "size": 18703,
          "sha512": "f78ba2d9731a903643b6d30ae477a23d0388bf61682a7b48002a91e282396ff0305c0acd174dc5ec7966a528eeff76c783b2b8d936dd3c0c3daf17d676e5173c",
          "sha256": "ec2eb2fe82203b15f2d81e0241204615d8ef32aff163fa22a767a88aaca152b3",
          "sha1": "aad8cddab4f286b20c88961392ac70701451811e",
          "md5": "7e79076c312dcbeae7d073987980682a"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+52-sources.jar",
          "url": "uno-awt-0.7.9+52-sources.jar",
          "size": 3978,
          "sha512": "2da3141cf481b2edd85f7f42fb8a4a2a0905848fd7d34fad6bb3a3eee9f4fddeb3519109f6767c331339a4e43913a023087b2fbab9caa54bb256399953c3376d",
          "sha256": "bb3f3adb1afe3c17d53586b5513f29509e4e73a4648dacae82523045b18e79bd",
          "sha1": "5dd590e88c1c4dfb316b6c73762682b5fcb9a183",
          "md5": "83ba332c339245f851fa6f110b0b8b01"
        }
      ]
    }
  ]
}
