{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.14.jar",
          "url": "uno-0.7.14.jar",
          "size": 261,
          "sha512": "e8abbd29db27164c53b588077f9f8ea8cc72c2e93cce9b29dc860adce845134e679bd58facbefa4de28102b53c53fb77ab72f24f2c84dfbf94ed8afc56937bc0",
          "sha256": "b5e436b7334278c835c72b63a2c17742df7abc5dc3d74e8f3515194d5794759f",
          "sha1": "ecf566efce2142e2802b28318094c328f31058b0",
          "md5": "1b19216a7314fcb9ac370b35d87b44fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.14"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.14.jar",
          "url": "uno-0.7.14.jar",
          "size": 261,
          "sha512": "e8abbd29db27164c53b588077f9f8ea8cc72c2e93cce9b29dc860adce845134e679bd58facbefa4de28102b53c53fb77ab72f24f2c84dfbf94ed8afc56937bc0",
          "sha256": "b5e436b7334278c835c72b63a2c17742df7abc5dc3d74e8f3515194d5794759f",
          "sha1": "ecf566efce2142e2802b28318094c328f31058b0",
          "md5": "1b19216a7314fcb9ac370b35d87b44fa"
        }
      ]
    }
  ]
}
