{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+80",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3inx7swnifbjnb5nxw5ucvephi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+80.jar",
          "url": "commons-0.7.0+80.jar",
          "size": 348736,
          "sha512": "1f56a489ab1908aa9f578872f6f77b3bd392cb083ad1dabdd21f001312f0f57b67835cb19c08814b2c9dc65b7769fc3b714aef34a0beed98d2febe81400c858f",
          "sha256": "4c3882d66d69e94f326f0be245c6d4806dd6397218b509ca9716a9d579d5468a",
          "sha1": "423fda5b0cb34717d5ecb678be6526bbeda1c6e9",
          "md5": "c3d16e4a5f3d792e394e0bf9251ee859"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+80"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+80.jar",
          "url": "commons-0.7.0+80.jar",
          "size": 348736,
          "sha512": "1f56a489ab1908aa9f578872f6f77b3bd392cb083ad1dabdd21f001312f0f57b67835cb19c08814b2c9dc65b7769fc3b714aef34a0beed98d2febe81400c858f",
          "sha256": "4c3882d66d69e94f326f0be245c6d4806dd6397218b509ca9716a9d579d5468a",
          "sha1": "423fda5b0cb34717d5ecb678be6526bbeda1c6e9",
          "md5": "c3d16e4a5f3d792e394e0bf9251ee859"
        }
      ]
    }
  ]
}
