{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+89",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "j7nd6ix4sbbhxfkukaqbpxdunm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+89.jar",
          "url": "11-0.7.0+89.jar",
          "size": 328882,
          "sha512": "fbceaa4efa2570937f39451dcfebf7221baf4b0f9d44c02425ab319bc5f66d4c93bc80cd78f035cf5f28dd9f870ea105201ad8d37b7c539c7d6c34f403c58d18",
          "sha256": "52c4540ebbb05e942de15381a1e989ce29ffbc7f5f397d0ccf7b9c8f2b86e80b",
          "sha1": "c9b9829efc9a99c11c1eb56103d12ed377093950",
          "md5": "864deeabbe1c8975c5d63970936a3372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+89"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+89.jar",
          "url": "11-0.7.0+89.jar",
          "size": 328882,
          "sha512": "fbceaa4efa2570937f39451dcfebf7221baf4b0f9d44c02425ab319bc5f66d4c93bc80cd78f035cf5f28dd9f870ea105201ad8d37b7c539c7d6c34f403c58d18",
          "sha256": "52c4540ebbb05e942de15381a1e989ce29ffbc7f5f397d0ccf7b9c8f2b86e80b",
          "sha1": "c9b9829efc9a99c11c1eb56103d12ed377093950",
          "md5": "864deeabbe1c8975c5d63970936a3372"
        }
      ]
    }
  ]
}
