{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.72.jar",
          "url": "kool-0.9.72.jar",
          "size": 456828,
          "sha512": "55c0d9c1499f1a4f43d54f87d6ecb60399e1e14a5a0d802acc244eb24849aa296c1e59df482761e30e5c24ae1ad6763d8e68ca877de80e7dc33ce57c0f09e80f",
          "sha256": "e19a077a9ad16e3f5d4dea6dcc286202de90683ea2a63b0be3119ae5e4d1a450",
          "sha1": "e5dfb52a7ad4b94abd64c5c63757c834a8d12abe",
          "md5": "6966e9f547b5acb588dcb54595a4c893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.72.jar",
          "url": "kool-0.9.72.jar",
          "size": 456828,
          "sha512": "55c0d9c1499f1a4f43d54f87d6ecb60399e1e14a5a0d802acc244eb24849aa296c1e59df482761e30e5c24ae1ad6763d8e68ca877de80e7dc33ce57c0f09e80f",
          "sha256": "e19a077a9ad16e3f5d4dea6dcc286202de90683ea2a63b0be3119ae5e4d1a450",
          "sha1": "e5dfb52a7ad4b94abd64c5c63757c834a8d12abe",
          "md5": "6966e9f547b5acb588dcb54595a4c893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.72-sources.jar",
          "url": "kool-0.9.72-sources.jar",
          "size": 118569,
          "sha512": "bb0fec7f76d0904f3939b2f021fbf1badb84c8f917eb7ab9f9c5fcb1815c357cbedd6a1ec217124dccb0534de4d82d50e8d1b4a31064d746f6a7a403bb97d329",
          "sha256": "a35a5d8692a92e8e06cdb340514f49b79588c2a5a0505f3d0b318456b716e20a",
          "sha1": "d2e0525f2967eb57c43ab3e8a1c1359eb82cd186",
          "md5": "2b884a63a6522435dc4dd91991433966"
        }
      ]
    }
  ]
}
