{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "sj45ngsqonfilath2mfxghypdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+86.jar",
          "url": "11-0.7.0+86.jar",
          "size": 328880,
          "sha512": "aee951284134f6e3c8c5ca5de34b464dee56de507d210a78437bbf8098c0db1acfcf5a73ec5e3a9ed63c7f40fa658a8865e22012759d0bcb337690ee74617067",
          "sha256": "e7611559bd2d11cc59d4c1b0515ae78eddf5b11a188eb6d0d1337040c700db77",
          "sha1": "8940be00f963b5ecacb3e11c52b822166190462a",
          "md5": "942ba46497b4cdf2e1a0e82de050083f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+86"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+86.jar",
          "url": "11-0.7.0+86.jar",
          "size": 328880,
          "sha512": "aee951284134f6e3c8c5ca5de34b464dee56de507d210a78437bbf8098c0db1acfcf5a73ec5e3a9ed63c7f40fa658a8865e22012759d0bcb337690ee74617067",
          "sha256": "e7611559bd2d11cc59d4c1b0515ae78eddf5b11a188eb6d0d1337040c700db77",
          "sha1": "8940be00f963b5ecacb3e11c52b822166190462a",
          "md5": "942ba46497b4cdf2e1a0e82de050083f"
        }
      ]
    }
  ]
}
