{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "$0.7.0+39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-$0.7.0+39.jar",
          "url": "8-$0.7.0+39.jar",
          "size": 323602,
          "sha512": "858df3787a452dd47c82d97f380047e68a431deb11343a96dd31d1ce8abd48ab4a29537d0817814a52727f2131bf7f7f504981efc404291a37e9d3baefc3422a",
          "sha256": "1a9d36aa8b2c710da9bbeabc65f32f22ba6a2935b1493dfab7d3d3c7d4a1f987",
          "sha1": "217a23ddb80e79c4b90c5c509d70da7293e89c6d",
          "md5": "e7d712e1a3aa33ba4ab671a3f4163821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "$0.7.0+39"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "$0.7.0+39"
          }
        }
      ],
      "files": [
        {
          "name": "8-$0.7.0+39.jar",
          "url": "8-$0.7.0+39.jar",
          "size": 323602,
          "sha512": "858df3787a452dd47c82d97f380047e68a431deb11343a96dd31d1ce8abd48ab4a29537d0817814a52727f2131bf7f7f504981efc404291a37e9d3baefc3422a",
          "sha256": "1a9d36aa8b2c710da9bbeabc65f32f22ba6a2935b1493dfab7d3d3c7d4a1f987",
          "sha1": "217a23ddb80e79c4b90c5c509d70da7293e89c6d",
          "md5": "e7d712e1a3aa33ba4ab671a3f4163821"
        }
      ]
    }
  ]
}
