{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-gl",
    "version": "1.79+03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+03.jar",
          "url": "imgui-gl-1.79+03.jar",
          "size": 43484,
          "sha512": "d7e278d94548c88e5f0af78170b7670c6e1a2d6a17ba24266c8005d4300b2eb2324806cd429143bd2e9357e703cba86cb6b0577c5d849176354ed68c2c946af4",
          "sha256": "b5b57fe183157056032c021dec392b38f7ab0395b4c99ec47bf3e85df5309e95",
          "sha1": "9725ad3d2c7719edbf16517cdc7fc975c60e436b",
          "md5": "c33b81abc250d57443eb4d485abe128b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+46"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.79+03"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-glfw",
          "version": {
            "requires": "1.79+03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.79+03.jar",
          "url": "imgui-gl-1.79+03.jar",
          "size": 43484,
          "sha512": "d7e278d94548c88e5f0af78170b7670c6e1a2d6a17ba24266c8005d4300b2eb2324806cd429143bd2e9357e703cba86cb6b0577c5d849176354ed68c2c946af4",
          "sha256": "b5b57fe183157056032c021dec392b38f7ab0395b4c99ec47bf3e85df5309e95",
          "sha1": "9725ad3d2c7719edbf16517cdc7fc975c60e436b",
          "md5": "c33b81abc250d57443eb4d485abe128b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+03-all.jar",
          "url": "imgui-gl-1.79+03-all.jar",
          "size": 81168827,
          "sha512": "14cf7766a7adfc0db6b74610fbb9cb3f2ab9a78c0d1c6ec59d7a9bade1a402adc8df276ac7c96c48172201c1362cbaa282825e10737d50e788c1c4e7e569584a",
          "sha256": "efb9be301b5f323ac75471b3d7abe2789ea33ce3b5e5aaf6e7900d91934eef2f",
          "sha1": "42be43bcf71359f691bfe90915e9b9b6898bdb36",
          "md5": "78d184f774363de943f0222f4dcf1c5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+03-sources.jar",
          "url": "imgui-gl-1.79+03-sources.jar",
          "size": 14126,
          "sha512": "3129e8ef12e6bc8c3aee71beae935cfe9e097b7f11fd79d3c33246f4e772d08022d3f4145f409f38ca4108eaaf4bf781a98cbca5dfe41d56690b04319d7002a3",
          "sha256": "f22aa4649edff7a9b5d26c95ede7b68ec5d40fd0fd08f7a7e03b1f7872a61088",
          "sha1": "bf707367c70fa87f552f231fa26c4275961e2dc1",
          "md5": "e749b4a2c41f9a77bf8821ab38304036"
        }
      ]
    }
  ]
}
