{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.2+14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "whfppcrfrjgyfpuqgosn5egl6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gln-0.5.2+14.jar",
          "url": "gln-0.5.2+14.jar",
          "size": 967267,
          "sha512": "d9b5dfa43f2676eefdb7090755d8988c8fc3022e93d6f13c07d31531dd645d06bcb9c468e72403cadaa4d445d73a5cf07c2aef6cef026e21b9c7fa0d0a896bc1",
          "sha256": "a74200809ffb6761cd921bd2bded87034da22e46904c773408b201ecbb195c76",
          "sha1": "1a73bc70d24c11adac0228c00d812fb4f83450a8",
          "md5": "850a22d33425dac5b32c1ef5e29368a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+33"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+14.jar",
          "url": "gln-0.5.2+14.jar",
          "size": 967267,
          "sha512": "d9b5dfa43f2676eefdb7090755d8988c8fc3022e93d6f13c07d31531dd645d06bcb9c468e72403cadaa4d445d73a5cf07c2aef6cef026e21b9c7fa0d0a896bc1",
          "sha256": "a74200809ffb6761cd921bd2bded87034da22e46904c773408b201ecbb195c76",
          "sha1": "1a73bc70d24c11adac0228c00d812fb4f83450a8",
          "md5": "850a22d33425dac5b32c1ef5e29368a5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+14-all.jar",
          "url": "gln-0.5.2+14-all.jar",
          "size": 12975401,
          "sha512": "21e2fe8331b27367d68e757ea0f1a50aabf8c41e26f0fa751cbbe2846634510a8b70f63ff2866eda5e6207bc19f2e12148928dd782bdfe5e7699ce9b980c11d2",
          "sha256": "28bd171de4af2fadbf203edea957b8956785bcd28bd0e626475d859d364c8f6c",
          "sha1": "ff0876c139849348c5f1d59ecc892c903831a55e",
          "md5": "055b75bb5ef328434e8dc2aefad565ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+14-sources.jar",
          "url": "gln-0.5.2+14-sources.jar",
          "size": 263116,
          "sha512": "02af0a41162910dc225aace9d2ea71cd63f48cd91c58675698ed9ba8b4a07c13a8b866fd34cfbbf17262771dea40351469a6b7159f709f8c07f4115feddc1a10",
          "sha256": "e7eb6875cde78fb9b95e7cb7d37b1c0defc8af8970c8c9f35183c28265ea4138",
          "sha1": "21ae4b06c45e0ee06955f3c7683ff75d1ae746af",
          "md5": "ac40f19db3d38184c385e2d72ff55148"
        }
      ]
    }
  ]
}
