{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-gl",
    "version": "0.7.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.20.jar",
          "url": "uno-gl-0.7.20.jar",
          "size": 3446,
          "sha512": "83a8cf67dcc0134dee35d43ab1d119dd1c891224dea23224956e0c0d81b52864ddbf215d717e65e2fab4b28ceeb91b681d234f69133e2de58331f58da6b36379",
          "sha256": "973d634bf8f8aeb02faa7113f99e3020bb7b5254e1544047bd08bf9ee471e596",
          "sha1": "6a2c0beb81b279bc8d73001c8d13287842214fd1",
          "md5": "b809ad75b8ee073e976f4bb1c08f7d89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.20.jar",
          "url": "uno-gl-0.7.20.jar",
          "size": 3446,
          "sha512": "83a8cf67dcc0134dee35d43ab1d119dd1c891224dea23224956e0c0d81b52864ddbf215d717e65e2fab4b28ceeb91b681d234f69133e2de58331f58da6b36379",
          "sha256": "973d634bf8f8aeb02faa7113f99e3020bb7b5254e1544047bd08bf9ee471e596",
          "sha1": "6a2c0beb81b279bc8d73001c8d13287842214fd1",
          "md5": "b809ad75b8ee073e976f4bb1c08f7d89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-gl-0.7.20-sources.jar",
          "url": "uno-gl-0.7.20-sources.jar",
          "size": 1565,
          "sha512": "b87f1410b4b5ee39ccb8114f381b6ee3d05f79c100f64785a3dabc05e0915b3d1f9e868520a311ca32f286a39392f6fb25a3317fc6be805578c6e9301ae4af1d",
          "sha256": "9a853cf553b1a403ddab5f5b3344655fcaf29b6daa06e6df7daed30b5c63dc40",
          "sha1": "6744303c0f40caf5b23234652e4647f6685f0d0d",
          "md5": "dd980dc332ab9e45dd8624650a31b05a"
        }
      ]
    }
  ]
}
