{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.3+45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.3+45.jar",
          "url": "commons-0.7.3+45.jar",
          "size": 657137,
          "sha512": "f56a4adaa1999f3f3158b218c17518b752fa6eba94fd388500afd8b3fb7706681fb0a8c48fe997cbd12e41cb5f1562ec96252fefd0ed86766a77e0182a7f5302",
          "sha256": "46836c677de2e17ba3e2e1175fe09f41463d62180981c4bd8a48439aa6eee43c",
          "sha1": "d317566bdf9c6ed86a74001ce42284306491dd11",
          "md5": "e87ef07d8881e34c140cbcdbd83a4c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-plugin",
          "version": {
            "requires": "0.3.3+23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin"
        }
      ],
      "files": [
        {
          "name": "commons-0.7.3+45.jar",
          "url": "commons-0.7.3+45.jar",
          "size": 657137,
          "sha512": "f56a4adaa1999f3f3158b218c17518b752fa6eba94fd388500afd8b3fb7706681fb0a8c48fe997cbd12e41cb5f1562ec96252fefd0ed86766a77e0182a7f5302",
          "sha256": "46836c677de2e17ba3e2e1175fe09f41463d62180981c4bd8a48439aa6eee43c",
          "sha1": "d317566bdf9c6ed86a74001ce42284306491dd11",
          "md5": "e87ef07d8881e34c140cbcdbd83a4c42"
        }
      ]
    }
  ]
}
