{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+50.jar",
          "url": "8-0.7.0+50.jar",
          "size": 323605,
          "sha512": "9bfb7a05406d1a1404b9b09bd095c90216609f1f5b14c3fe70b278da32d8cbf4cb8674e898327b4f79bea46d410e74a5fb4e5423f763b00aa4733920634d0c22",
          "sha256": "55112102c592da47f8163606b626c6ab41a28d6932baacb0459aa5c0b44cce2f",
          "sha1": "84dce11817ca91e5358691b1f70ab402c9f20dd4",
          "md5": "2cc31a1b5cf744faf6ea5955c9a4800c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+50"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+50.jar",
          "url": "8-0.7.0+50.jar",
          "size": 323605,
          "sha512": "9bfb7a05406d1a1404b9b09bd095c90216609f1f5b14c3fe70b278da32d8cbf4cb8674e898327b4f79bea46d410e74a5fb4e5423f763b00aa4733920634d0c22",
          "sha256": "55112102c592da47f8163606b626c6ab41a28d6932baacb0459aa5c0b44cce2f",
          "sha1": "84dce11817ca91e5358691b1f70ab402c9f20dd4",
          "md5": "2cc31a1b5cf744faf6ea5955c9a4800c"
        }
      ]
    }
  ]
}
