{
  "formatVersion": "1.1",
  "component": {
    "group": "elect86",
    "module": "slurm.kts",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "slurm.kts-0.0.8.jar",
          "url": "slurm.kts-0.0.8.jar",
          "size": 72050,
          "sha512": "bc9347b21544baaf108eca0cc92478de611019c5dfbb2e14542e29d7bf48f5f7d45b6f17be65cc639175c2f6cb75b9c2d4d844bb9b8b32730d4d1839a042f400",
          "sha256": "003f3b205feea4c78e13d918ff89e9daaaefcc26eda1641d5cbc04bfb0278c7c",
          "sha1": "ee03b61bec86ed155180c636fea7e85581d614f7",
          "md5": "3404a56067407eb7bb2c19aff75aab7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "slurm.kts-0.0.8.jar",
          "url": "slurm.kts-0.0.8.jar",
          "size": 72050,
          "sha512": "bc9347b21544baaf108eca0cc92478de611019c5dfbb2e14542e29d7bf48f5f7d45b6f17be65cc639175c2f6cb75b9c2d4d844bb9b8b32730d4d1839a042f400",
          "sha256": "003f3b205feea4c78e13d918ff89e9daaaefcc26eda1641d5cbc04bfb0278c7c",
          "sha1": "ee03b61bec86ed155180c636fea7e85581d614f7",
          "md5": "3404a56067407eb7bb2c19aff75aab7e"
        }
      ]
    }
  ]
}
