{
  "formatVersion": "1.1",
  "component": {
    "group": "elect86",
    "module": "slurm.kts",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "slurm.kts-0.0.7.jar",
          "url": "slurm.kts-0.0.7.jar",
          "size": 72050,
          "sha512": "fc701d613e85c9651ca922b6871b9214a73b5a3e776bd2755624468005f7653c412f840673d1653d2d78155619717d7750a8058fa66697cd1948ba4c672d06bd",
          "sha256": "d4ec9c85cd839ff128d6a7083fcb55bb238210a8f7e191f10c1db8a0c5746898",
          "sha1": "514a4ecca4b42e77af502371f62f125e24079ec7",
          "md5": "5586f72fcac8ffa364453aeaee31944c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "slurm.kts-0.0.7.jar",
          "url": "slurm.kts-0.0.7.jar",
          "size": 72050,
          "sha512": "fc701d613e85c9651ca922b6871b9214a73b5a3e776bd2755624468005f7653c412f840673d1653d2d78155619717d7750a8058fa66697cd1948ba4c672d06bd",
          "sha256": "d4ec9c85cd839ff128d6a7083fcb55bb238210a8f7e191f10c1db8a0c5746898",
          "sha1": "514a4ecca4b42e77af502371f62f125e24079ec7",
          "md5": "5586f72fcac8ffa364453aeaee31944c"
        }
      ]
    }
  ]
}
