{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.0+17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lq5wu3fdcben3cxuimanhvufqu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.0+17.jar",
          "url": "kool-0.9.0+17.jar",
          "size": 271636,
          "sha512": "50316453dd15bd330e917690bd68e761d3185c32ed1239253fa9e81b867b3116821dc3799eb68282933c236ac78118a474bc3d0938f48ee767724f7f43b9370f",
          "sha256": "ecc07fdad311d4bbea0e3187c3eea361fc6a63a28fe0e0d2b21c4605dc94e1b8",
          "sha1": "0aad90552305cc8a3f2456a62c076c89bc268490",
          "md5": "52705a08eed319a93d291de3dab97b25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-source",
          "version": {
            "requires": "0.7.0+26"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.0+17.jar",
          "url": "kool-0.9.0+17.jar",
          "size": 271636,
          "sha512": "50316453dd15bd330e917690bd68e761d3185c32ed1239253fa9e81b867b3116821dc3799eb68282933c236ac78118a474bc3d0938f48ee767724f7f43b9370f",
          "sha256": "ecc07fdad311d4bbea0e3187c3eea361fc6a63a28fe0e0d2b21c4605dc94e1b8",
          "sha1": "0aad90552305cc8a3f2456a62c076c89bc268490",
          "md5": "52705a08eed319a93d291de3dab97b25"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.0+17-all.jar",
          "url": "kool-0.9.0+17-all.jar",
          "size": 2828002,
          "sha512": "1e8e34cd79ac9672d6e474c5e6b9921f8de65d156bd4a23782eb50f04afc76ca4209e1ab94fc916603907eac6e1d431989caa9761894f23544b079aee35ba545",
          "sha256": "777c5ef666ebd8d7364f8b295d0386729df41d03196c54ed20675db75aa40ee8",
          "sha1": "77e04c750d2c0877c5e7a1f6e13a934f4d116692",
          "md5": "acb10810175926531439e75ad8f6b642"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.0+17-sources.jar",
          "url": "kool-0.9.0+17-sources.jar",
          "size": 46834,
          "sha512": "523832ea5971cdba5dc9f3ed466f5268d4ea1801c6485f2e256c08631141fd82ff7e45aad3f1ad0b906e6a143699aca3d00433db41f67a8eb5435af06fd0bbcc",
          "sha256": "45ce472cdea89514039164969d653711f676026d00efbb980e8d037b492fa50a",
          "sha1": "80073ac445da0b015ac9f8684cc33ff512f2355d",
          "md5": "4610b45c89e5e47f5e3bee744c1cbd29"
        }
      ]
    }
  ]
}
