{
  "formatVersion": "1.1",
  "component": {
    "group": "elect86",
    "module": "slurm.kts",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "slurm.kts-0.0.11.jar",
          "url": "slurm.kts-0.0.11.jar",
          "size": 72117,
          "sha512": "1b910e62f5b6f9bc8b138938385fab19447f9e4624aac19ed014952ee7cdd4ec7f4411cddeee623ca18c338b0b98f625a1f7489b7816f831a267a92e9adceef3",
          "sha256": "a075f6cb7a43c9049b5d3ffb8da570c09413919ef9a91a3d98d7ff03f2947446",
          "sha1": "06e522e821de85ec2504b0ef7fc1bde725349a26",
          "md5": "13079a2a34b91f9f39b9a43015321016"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "slurm.kts-0.0.11.jar",
          "url": "slurm.kts-0.0.11.jar",
          "size": 72117,
          "sha512": "1b910e62f5b6f9bc8b138938385fab19447f9e4624aac19ed014952ee7cdd4ec7f4411cddeee623ca18c338b0b98f625a1f7489b7816f831a267a92e9adceef3",
          "sha256": "a075f6cb7a43c9049b5d3ffb8da570c09413919ef9a91a3d98d7ff03f2947446",
          "sha1": "06e522e821de85ec2504b0ef7fc1bde725349a26",
          "md5": "13079a2a34b91f9f39b9a43015321016"
        }
      ]
    }
  ]
}
