{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l6fgcibgjrfufokpdbegewhzmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+85.jar",
          "url": "8-0.7.0+85.jar",
          "size": 324839,
          "sha512": "10cc4d2a6edb6b76ac99041552f404487d11af12dd2522b4308aba322433678f39e5c13e853e4635efe9fefd3faa4d09565a8d61e5413ed3666effdcd4b57773",
          "sha256": "217149fce873ec74ccaffe251b55ae9a54c6a87977ce5f99b6d9994939ac6cdd",
          "sha1": "45c32eb9e66ca3968ab1d863fc5888da0479cb42",
          "md5": "4bfe5525d07606256b5f2dea59ad1b19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+85"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+85.jar",
          "url": "8-0.7.0+85.jar",
          "size": 324839,
          "sha512": "10cc4d2a6edb6b76ac99041552f404487d11af12dd2522b4308aba322433678f39e5c13e853e4635efe9fefd3faa4d09565a8d61e5413ed3666effdcd4b57773",
          "sha256": "217149fce873ec74ccaffe251b55ae9a54c6a87977ce5f99b6d9994939ac6cdd",
          "sha1": "45c32eb9e66ca3968ab1d863fc5888da0479cb42",
          "md5": "4bfe5525d07606256b5f2dea59ad1b19"
        }
      ]
    }
  ]
}
