{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.3.jar",
          "url": "gln-0.5.3.jar",
          "size": 984252,
          "sha512": "d0ea0fb6229ac0588e5639f84f0896dd6032fca14ef6a784992efb7e9593dff5af9d44c37c1793e2840cc031eaa38009452f0f4cadabc27cab6b4c2e3a1b4173",
          "sha256": "5b88826075a21462181a6a47ca153c0651209a95186905184bb03d67f2014b51",
          "sha1": "37724d7dba42e4c75a9baa3c68d832ac79e710b1",
          "md5": "e2bba82474943b4fc65a07825e861653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.3.jar",
          "url": "gln-0.5.3.jar",
          "size": 984252,
          "sha512": "d0ea0fb6229ac0588e5639f84f0896dd6032fca14ef6a784992efb7e9593dff5af9d44c37c1793e2840cc031eaa38009452f0f4cadabc27cab6b4c2e3a1b4173",
          "sha256": "5b88826075a21462181a6a47ca153c0651209a95186905184bb03d67f2014b51",
          "sha1": "37724d7dba42e4c75a9baa3c68d832ac79e710b1",
          "md5": "e2bba82474943b4fc65a07825e861653"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gln-0.5.3-jdk8.jar",
          "url": "gln-0.5.3-jdk8.jar",
          "size": 979130,
          "sha512": "cc8bd554c4f4cdfcce0056c52d5c2f1f27234cc705b0984881f42544bd2d9359ad3993c6bb2d5846d845d380f16d1d0fa3167be6f4c73e31c18031972154f768",
          "sha256": "2ba8bc6697385dc46ca9f321e940bee2b53115c00eefd81017b8f428f982a3e3",
          "sha1": "d5118fa7e76341d2cc3492a7b037991c178cfc57",
          "md5": "1fbe844f839bf0f2ca24416c87225406"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.3"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.3-jdk8.jar",
          "url": "gln-0.5.3-jdk8.jar",
          "size": 979130,
          "sha512": "cc8bd554c4f4cdfcce0056c52d5c2f1f27234cc705b0984881f42544bd2d9359ad3993c6bb2d5846d845d380f16d1d0fa3167be6f4c73e31c18031972154f768",
          "sha256": "2ba8bc6697385dc46ca9f321e940bee2b53115c00eefd81017b8f428f982a3e3",
          "sha1": "d5118fa7e76341d2cc3492a7b037991c178cfc57",
          "md5": "1fbe844f839bf0f2ca24416c87225406"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.3-sources.jar",
          "url": "gln-0.5.3-sources.jar",
          "size": 263395,
          "sha512": "bb41833952b91d74ab29304f6fb016a0b7ff11ee73e8a694f233eea055f393074c51d0537d6d390ed8d214be4ea68c8c718d1e097238d83f1d91302bd8dda7c6",
          "sha256": "17b7cb4efae15fa743b08558fa878d3c99b684b9bbb68532ef3c2c390257f681",
          "sha1": "9f27417cbc5cb86c906a0547c3fea50ebc863998",
          "md5": "2856ad6ac2f1f9b48d1fe1a5baa49495"
        }
      ]
    }
  ]
}
