{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "utils",
    "version": "0.7.3+48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "utils-0.7.3+48.jar",
          "url": "utils-0.7.3+48.jar",
          "size": 177648,
          "sha512": "65f8d896659a21a9a55e3fa50d8f5dd680ff9f0d835ffb33b7846c3eb0c6d1b412b8785fae8210dea13263e62fff6d65dfbbcb23ada1f33dbafaa4a8f719bb72",
          "sha256": "10b1022a12c246cc4942b63a8773ec6655cbb58f6f613c046bd3d032d440b61b",
          "sha1": "fca97d0ee3cf6a96698891ec6720e1fd6dde2f78",
          "md5": "56f935a7a98a03fee3389ee4f5f358fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "utils-0.7.3+48.jar",
          "url": "utils-0.7.3+48.jar",
          "size": 177648,
          "sha512": "65f8d896659a21a9a55e3fa50d8f5dd680ff9f0d835ffb33b7846c3eb0c6d1b412b8785fae8210dea13263e62fff6d65dfbbcb23ada1f33dbafaa4a8f719bb72",
          "sha256": "10b1022a12c246cc4942b63a8773ec6655cbb58f6f613c046bd3d032d440b61b",
          "sha1": "fca97d0ee3cf6a96698891ec6720e1fd6dde2f78",
          "md5": "56f935a7a98a03fee3389ee4f5f358fd"
        }
      ]
    }
  ]
}
