{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "kx",
    "version": "0.7.0+36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+36.jar",
          "url": "kx-0.7.0+36.jar",
          "size": 50126,
          "sha512": "c5f89598de6553875aa0609efc7eeefe3d39fe9ce335315c8155893aebfaf298849f6d992a5d70de538d278608b3558da8be3f82f8df35cc47112be4574871d0",
          "sha256": "bc29514c4614687947844268d94efbc2271c8887e2c59269af2dd06ddfdb997f",
          "sha1": "3ae5919ee2475756516184fdd33b27175509fe84",
          "md5": "71cd1b2790a17d8fa84bdadb5253b169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+36.jar",
          "url": "kx-0.7.0+36.jar",
          "size": 50126,
          "sha512": "c5f89598de6553875aa0609efc7eeefe3d39fe9ce335315c8155893aebfaf298849f6d992a5d70de538d278608b3558da8be3f82f8df35cc47112be4574871d0",
          "sha256": "bc29514c4614687947844268d94efbc2271c8887e2c59269af2dd06ddfdb997f",
          "sha1": "3ae5919ee2475756516184fdd33b27175509fe84",
          "md5": "71cd1b2790a17d8fa84bdadb5253b169"
        }
      ]
    }
  ]
}
