{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "vk",
    "version": "0.7.9+40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+40.jar",
          "url": "vk-0.7.9+40.jar",
          "size": 3710,
          "sha512": "f9faff7dcd51dd41fe9077541f3c709eea720a40795fbbbba40b3be0f31f41c85a816cb2fc40775ab7157f37f273e8d4c21fe9d30615b93d3bc01eb5b553058a",
          "sha256": "097c130fef219d99dfaa1004717577d44f28f5491e6116e13780a277e177a583",
          "sha1": "27e98389660c22fc7b9187c8496edafe2576e348",
          "md5": "a217317590dc324a9b111af025bd84e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+40.jar",
          "url": "vk-0.7.9+40.jar",
          "size": 3710,
          "sha512": "f9faff7dcd51dd41fe9077541f3c709eea720a40795fbbbba40b3be0f31f41c85a816cb2fc40775ab7157f37f273e8d4c21fe9d30615b93d3bc01eb5b553058a",
          "sha256": "097c130fef219d99dfaa1004717577d44f28f5491e6116e13780a277e177a583",
          "sha1": "27e98389660c22fc7b9187c8496edafe2576e348",
          "md5": "a217317590dc324a9b111af025bd84e3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vk-0.7.9+40-all.jar",
          "url": "vk-0.7.9+40-all.jar",
          "size": 63552754,
          "sha512": "305364620b9fc8c45c472a8e9d449d3631475e414d9b83b47a41de38d848c7e4a2153289f26e9bb79d33ce7cc922b76d4d4d64576122397a6a0dc22f427eb023",
          "sha256": "86eda0bc03cea8ea2b0ea1e539d0dda9a3278dc7bf377d2858583a11f2f7539e",
          "sha1": "3b61f9d1eca993edf5a1662c19d0c5d4f20bdd22",
          "md5": "42b90b70b181b51e090812fd31cfbd21"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vk-0.7.9+40-jdk8.jar",
          "url": "vk-0.7.9+40-jdk8.jar",
          "size": 3725,
          "sha512": "7e21a05fa782363195574375663576956c6fea02c940bd14b193a780b09776f941ca6f32e43c0e538ffecaec6c9323631adb7cc1a867395d2497186a2dc9a951",
          "sha256": "7656a7719a454f511b9ac1e63e2783b975615345cc058c4476ef199b98a345c3",
          "sha1": "ff641cb091684965b1c405d7e9cb6a4635f5917b",
          "md5": "5df7f8311fbe0e7e7bf7c47cf7c1f728"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.9+40"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+40-jdk8.jar",
          "url": "vk-0.7.9+40-jdk8.jar",
          "size": 3725,
          "sha512": "7e21a05fa782363195574375663576956c6fea02c940bd14b193a780b09776f941ca6f32e43c0e538ffecaec6c9323631adb7cc1a867395d2497186a2dc9a951",
          "sha256": "7656a7719a454f511b9ac1e63e2783b975615345cc058c4476ef199b98a345c3",
          "sha1": "ff641cb091684965b1c405d7e9cb6a4635f5917b",
          "md5": "5df7f8311fbe0e7e7bf7c47cf7c1f728"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.9+40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vk-0.7.9+40-sources.jar",
          "url": "vk-0.7.9+40-sources.jar",
          "size": 1268,
          "sha512": "09b23f8251936befbce68074f6690eca4021fef1003866aec937cc1ab9a7f74a1be13cf3fc242f0c2f6e0a3b5ce7d1399ffbefd5a3386f6b2fe7c247b6438cb4",
          "sha256": "f0c27c338bc3c221b5d60e7a6a13456a85aaeeacb8ab13dad37fa26ac6498d75",
          "sha1": "cf14ff5a88c11ac9630bcc3a87a70e7211e0e2ab",
          "md5": "1b82d5c7c74be21f1e5af28e07dc3131"
        }
      ]
    }
  ]
}
