{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+55.jar",
          "url": "commons-0.7.0+55.jar",
          "size": 359666,
          "sha512": "1069ee412530f4c8fb9796300fe2374ed2c871067e344b554db0e6ddc3703306b718b6c85e8be2c6878564d04f9a2b355f12868138977725cd75090c448900c1",
          "sha256": "b69c6def52cb4684727277c9f90134415b53eda594a032f5002724f00b822e8b",
          "sha1": "80298ea21cc11fa867b106a0adfa26438347b9b8",
          "md5": "9eb45bdc62a5f698ce4198ddf9e8e734"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+55"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+55.jar",
          "url": "commons-0.7.0+55.jar",
          "size": 359666,
          "sha512": "1069ee412530f4c8fb9796300fe2374ed2c871067e344b554db0e6ddc3703306b718b6c85e8be2c6878564d04f9a2b355f12868138977725cd75090c448900c1",
          "sha256": "b69c6def52cb4684727277c9f90134415b53eda594a032f5002724f00b822e8b",
          "sha1": "80298ea21cc11fa867b106a0adfa26438347b9b8",
          "md5": "9eb45bdc62a5f698ce4198ddf9e8e734"
        }
      ]
    }
  ]
}
