{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+83",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qysdlozpkbhnpgeevjjy63obhy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+83.jar",
          "url": "lwjgl-0.7.0+83.jar",
          "size": 189826,
          "sha512": "873a6eca1c0f38956a427355cc59cc5930e4b25dc76e7a3cdc3a944f270386718c71b4f8c8ce1e939b05f47c0838920b923b40eecd24c2b28fb591ac54b3dd63",
          "sha256": "0b5148ddd768dd0211212a886ea10d0d12cdb026baa1c0e68fc97cc9fbc2b950",
          "sha1": "8dea04956c41bddc38d20898eba45d0b2a6cf62e",
          "md5": "e1b093115036f0a32d19b1d3634535b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+83.jar",
          "url": "lwjgl-0.7.0+83.jar",
          "size": 189826,
          "sha512": "873a6eca1c0f38956a427355cc59cc5930e4b25dc76e7a3cdc3a944f270386718c71b4f8c8ce1e939b05f47c0838920b923b40eecd24c2b28fb591ac54b3dd63",
          "sha256": "0b5148ddd768dd0211212a886ea10d0d12cdb026baa1c0e68fc97cc9fbc2b950",
          "sha1": "8dea04956c41bddc38d20898eba45d0b2a6cf62e",
          "md5": "e1b093115036f0a32d19b1d3634535b9"
        }
      ]
    }
  ]
}
