{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m4zrcqnvsbenvoprz6t7viu4ve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+99.jar",
          "url": "commons-0.7.0+99.jar",
          "size": 356849,
          "sha512": "af19f708d5141e791aa221b9be981edda28c79e7f31951a6141163f6d725e5e585415548dc9be3aee79e676e726c42899e11578296277943f2816a1873464169",
          "sha256": "4e44231309919836d338c63296c9a70543e2ec12acd80c52b20c6b5e542379f0",
          "sha1": "276fbacfaac1c34cf278fda3dbf0ee6e1c9cd99b",
          "md5": "554681d0e54c3986855d537903757717"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+99"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+99.jar",
          "url": "commons-0.7.0+99.jar",
          "size": 356849,
          "sha512": "af19f708d5141e791aa221b9be981edda28c79e7f31951a6141163f6d725e5e585415548dc9be3aee79e676e726c42899e11578296277943f2816a1873464169",
          "sha256": "4e44231309919836d338c63296c9a70543e2ec12acd80c52b20c6b5e542379f0",
          "sha1": "276fbacfaac1c34cf278fda3dbf0ee6e1c9cd99b",
          "md5": "554681d0e54c3986855d537903757717"
        }
      ]
    }
  ]
}
