{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+53.jar",
          "url": "commons-0.7.0+53.jar",
          "size": 359552,
          "sha512": "f59f66f4eb1f8b8c8b9673af0802b1a7d8c43968b2946cf5f9d1cd6f40d66e58ca0e23956c0038a6aaecf69b76df5db0fe9e302f10acd0ff3a5725b7f9d466f1",
          "sha256": "b1b6838f3fed14703bce150ee3da041137922ea6b05da74061098a96d0fcd907",
          "sha1": "e8e9aa511db8d41172cc58c114e54f4ab45133ea",
          "md5": "9487bc85eb9d76ebb46d4c1820e5029b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+53"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+53.jar",
          "url": "commons-0.7.0+53.jar",
          "size": 359552,
          "sha512": "f59f66f4eb1f8b8c8b9673af0802b1a7d8c43968b2946cf5f9d1cd6f40d66e58ca0e23956c0038a6aaecf69b76df5db0fe9e302f10acd0ff3a5725b7f9d466f1",
          "sha256": "b1b6838f3fed14703bce150ee3da041137922ea6b05da74061098a96d0fcd907",
          "sha1": "e8e9aa511db8d41172cc58c114e54f4ab45133ea",
          "md5": "9487bc85eb9d76ebb46d4c1820e5029b"
        }
      ]
    }
  ]
}
