{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gli",
    "version": "0.8.3.0-16+24++24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+25"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+23"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+24.jar",
          "url": "gli-0.8.3.0-16+24.jar",
          "size": 331312,
          "sha512": "0f8f85630ef8fe79ce56c6f6ca0f46d8298f59643da1a10b3b3c6e4fffa681d4a084bf642a83156c502f0e442a2fcde70e105013bfdf05712fec9116bf03b14f",
          "sha256": "64ce78cbd5b2215d60d402a2227e3e9bd702392716524aa023594686059a3e09",
          "sha1": "1c08e2a2b406db57909327a7e410b91576f51b9c",
          "md5": "dbebdee7ee883c530134dc4f436b6808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+25"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+23"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+24.jar",
          "url": "gli-0.8.3.0-16+24.jar",
          "size": 331312,
          "sha512": "0f8f85630ef8fe79ce56c6f6ca0f46d8298f59643da1a10b3b3c6e4fffa681d4a084bf642a83156c502f0e442a2fcde70e105013bfdf05712fec9116bf03b14f",
          "sha256": "64ce78cbd5b2215d60d402a2227e3e9bd702392716524aa023594686059a3e09",
          "sha1": "1c08e2a2b406db57909327a7e410b91576f51b9c",
          "md5": "dbebdee7ee883c530134dc4f436b6808"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+24-all.jar",
          "url": "gli-0.8.3.0-16+24-all.jar",
          "size": 8632879,
          "sha512": "c91e754400af90a386d33f23e44cccc70b523a357a64ccb2a996a00a953ebbc8cdc42786ca40aac8785933647038dcb9984b9ac3287a8f8b0f3bf48bb43423d3",
          "sha256": "b76e361513685243b8ed107b776916196cb77196c958d2d6c3174836f2186e30",
          "sha1": "8eb378d560f79b29a4f4769003132209eb05f55f",
          "md5": "af27082ba1c87bc27b2d435b7bf14b92"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+24-jdk8.jar",
          "url": "gli-0.8.3.0-16+24-jdk8.jar",
          "size": 318600,
          "sha512": "d81de2b2db039b9fa698bae96678355ad0e56f9667a0522944ebdc8905698be8fa0c3653b4979d604b0c7ca7a75e7cd38f19b84152a11e50666dc91d52aad07b",
          "sha256": "6968715dc7493e2a48bc9c61337b91cfa983a39c7a9baaf0b0ea9053a025a2a4",
          "sha1": "2db2ab9f07cd742862c918477c6973871d5705fc",
          "md5": "e24d5f599d228bd2fb794201fe4cb88e"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gli",
          "version": "0.8.3.0-16+24"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+25"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+23"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+24-jdk8.jar",
          "url": "gli-0.8.3.0-16+24-jdk8.jar",
          "size": 318600,
          "sha512": "d81de2b2db039b9fa698bae96678355ad0e56f9667a0522944ebdc8905698be8fa0c3653b4979d604b0c7ca7a75e7cd38f19b84152a11e50666dc91d52aad07b",
          "sha256": "6968715dc7493e2a48bc9c61337b91cfa983a39c7a9baaf0b0ea9053a025a2a4",
          "sha1": "2db2ab9f07cd742862c918477c6973871d5705fc",
          "md5": "e24d5f599d228bd2fb794201fe4cb88e"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gli",
          "version": "0.8.3.0-16+24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+24-sources.jar",
          "url": "gli-0.8.3.0-16+24-sources.jar",
          "size": 67701,
          "sha512": "5b3cfd1e6fe9be7e24ab0fa006dc6d559bcceb9347c7a0b2f6661246e7cc0a228aa22c90fe89cd6da78fed2ae438e026e3bf46d598f03e08544a72319b68d2ad",
          "sha256": "a95e25c78049cdefe68d572db101555992e588e977269376b94817ccf9c75583",
          "sha1": "8003d9a2705431e2a9abac7bf0ea3eb61d24cf8b",
          "md5": "8175d892ca14911108720962cfe263d4"
        }
      ]
    }
  ]
}
