{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ycnn2xghkbaxhbwdpk7d2himr4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+77.jar",
          "url": "11-0.7.0+77.jar",
          "size": 327370,
          "sha512": "81ce8fe15fbb1078da89ab7ea10037e837226f989b375c6c83acfbfbc77a9af7b5f38995f6788c28397fe4a9eac6acd2d8d3a807075e15da5155565c526b60d8",
          "sha256": "0c9f7b6e03138b2a184b35152570ad2ab7afa671b3decc060db7651e228ea986",
          "sha1": "cec78bb4800fbda30bb3b5f6507b2772eb099c9d",
          "md5": "0e6751c2a504b4123eab2461afd0bf51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+77"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+77.jar",
          "url": "11-0.7.0+77.jar",
          "size": 327370,
          "sha512": "81ce8fe15fbb1078da89ab7ea10037e837226f989b375c6c83acfbfbc77a9af7b5f38995f6788c28397fe4a9eac6acd2d8d3a807075e15da5155565c526b60d8",
          "sha256": "0c9f7b6e03138b2a184b35152570ad2ab7afa671b3decc060db7651e228ea986",
          "sha1": "cec78bb4800fbda30bb3b5f6507b2772eb099c9d",
          "md5": "0e6751c2a504b4123eab2461afd0bf51"
        }
      ]
    }
  ]
}
