{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.73.jar",
          "url": "kool-0.9.73.jar",
          "size": 487907,
          "sha512": "eb5313202d57c17989d051268c8502d130fa413f82a0e6cf1814c25cba7ee70b5cd26f5a2886220213d975dafe68d78fb041ce709fad019cf380eaf8fecf3aa2",
          "sha256": "4ae73cebc50116fa9c7f695f496e47c380be0b7b01dc971972312a4df083a54d",
          "sha1": "9d476f3df09872c1432e2fee27f851a16e83d03e",
          "md5": "20a5d1292bd29220f449b1796cf9188d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-assimp",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bgfx",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nuklear",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-par",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-assimp",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-assimp",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bgfx",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-bgfx",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nanovg",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nuklear",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-nuklear",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-par",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-par",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2-SNAPSHOT"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.73.jar",
          "url": "kool-0.9.73.jar",
          "size": 487907,
          "sha512": "eb5313202d57c17989d051268c8502d130fa413f82a0e6cf1814c25cba7ee70b5cd26f5a2886220213d975dafe68d78fb041ce709fad019cf380eaf8fecf3aa2",
          "sha256": "4ae73cebc50116fa9c7f695f496e47c380be0b7b01dc971972312a4df083a54d",
          "sha1": "9d476f3df09872c1432e2fee27f851a16e83d03e",
          "md5": "20a5d1292bd29220f449b1796cf9188d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.73-sources.jar",
          "url": "kool-0.9.73-sources.jar",
          "size": 118569,
          "sha512": "eb9c5cf32a5ca6cc3d42f0112df3ae17ff44ce220e19f0939896128b53a54df5ca63119eb380cc777392abc909fd5e4d54d34788e04f3d3833c6b80e5853706b",
          "sha256": "b84ced1661a038c955f8de59e0bcae4bd2a8b0be2c013601038d148980c83a79",
          "sha1": "4f28321db3d34be0c7a238b5ed9beb2951447c5b",
          "md5": "8638ee1fde721e2abdef939a104712a8"
        }
      ]
    }
  ]
}
