{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-gl",
    "version": "1.79+04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+04.jar",
          "url": "imgui-gl-1.79+04.jar",
          "size": 43484,
          "sha512": "44a823531d744ea4745c89a973dd6c19542ace259d59e873dc695f794d20745b10f5c56d786ce230f13723e14c75de9b550622576b7b82ae1b59d98ac33780fd",
          "sha256": "b7c9aa28996c5ddb65fe5706a769e7e7137b7e5270a41a78f087cf73956616e1",
          "sha1": "41d63927e1685c8973b26a44043ccb616d619d09",
          "md5": "9942aacf13531e6c918855de119ab662"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+46"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.79+04"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-glfw",
          "version": {
            "requires": "1.79+04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.79+04.jar",
          "url": "imgui-gl-1.79+04.jar",
          "size": 43484,
          "sha512": "44a823531d744ea4745c89a973dd6c19542ace259d59e873dc695f794d20745b10f5c56d786ce230f13723e14c75de9b550622576b7b82ae1b59d98ac33780fd",
          "sha256": "b7c9aa28996c5ddb65fe5706a769e7e7137b7e5270a41a78f087cf73956616e1",
          "sha1": "41d63927e1685c8973b26a44043ccb616d619d09",
          "md5": "9942aacf13531e6c918855de119ab662"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+04-all.jar",
          "url": "imgui-gl-1.79+04-all.jar",
          "size": 81168827,
          "sha512": "09876974ab36ca96ff4ada2dabe34a30b7f5d2b2fefa53f2359793e536c015e5dffa8aaea18781945237d3033ec3a19c9b78a3cafa07f69a95ede7ffa5c0b0cf",
          "sha256": "56d3300491b84b9e572dc40b8729ef1d11e4249a3c79b23f36bf88267872370b",
          "sha1": "85557f432f86fc078fcc015628fef9fc3f02a3e1",
          "md5": "e91ee07e66409c79bb57726bffaab708"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.79+04-sources.jar",
          "url": "imgui-gl-1.79+04-sources.jar",
          "size": 14126,
          "sha512": "b082508b33f18977243e423c06210dc4c401358e34d8b25c02c602352edffbbfaec877742cf1e17c27a5ca23d76bb7386ec23c05aba84c1e05754ee3490158f1",
          "sha256": "5a21c7be6bb400bd4ed928919cfcc9c968e912c9875527a39c2a3cffeb2acb73",
          "sha1": "4ecd95a309787d7080096daf14e82af0b7d8e7d0",
          "md5": "27506c4f38c982eab580de587bdb08b6"
        }
      ]
    }
  ]
}
