{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+83",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qysdlozpkbhnpgeevjjy63obhy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+83.jar",
          "url": "commons-0.7.0+83.jar",
          "size": 365880,
          "sha512": "d2b446912461c9acc90f6c100c8ccab52cdcfa9b0023f5733b45bfdfa43575beb7af26834efb921523442e6c49af833dc850e754964d598379f452fcc42ecd47",
          "sha256": "a957a6858d3c9265a39b5e52548e4b6c3ce632ae9245c20c9bd8e618dcd0114e",
          "sha1": "8874c723132e06a42865e6ad012d42bb2c120d51",
          "md5": "bd3aa79c038eab27bb480d91f4550e7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+83"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+83.jar",
          "url": "commons-0.7.0+83.jar",
          "size": 365880,
          "sha512": "d2b446912461c9acc90f6c100c8ccab52cdcfa9b0023f5733b45bfdfa43575beb7af26834efb921523442e6c49af833dc850e754964d598379f452fcc42ecd47",
          "sha256": "a957a6858d3c9265a39b5e52548e4b6c3ce632ae9245c20c9bd8e618dcd0114e",
          "sha1": "8874c723132e06a42865e6ad012d42bb2c120d51",
          "md5": "bd3aa79c038eab27bb480d91f4550e7b"
        }
      ]
    }
  ]
}
