{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gli",
    "version": "0.8.3.0-16+03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "exzg2r2edraudj2pxjmxzmowqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+03.jar",
          "url": "gli-0.8.3.0-16+03.jar",
          "size": 327289,
          "sha512": "435329583b967fa48315ffd416b03649e1f3edf58c93c90786a2bffe797011f96dff7b176c3d609065ebe9889249b40f611b950b369f6d4a0bc45325faff307f",
          "sha256": "9e3ced5087ff565c019d2bee855afb04f6712da1fb12caaf994d12f716de17c8",
          "sha1": "73ec4c44caa1e14b91c458127efd136bdefedce9",
          "md5": "8f981845bde6f2b9626687dcd60db26d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+31"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+03.jar",
          "url": "gli-0.8.3.0-16+03.jar",
          "size": 327289,
          "sha512": "435329583b967fa48315ffd416b03649e1f3edf58c93c90786a2bffe797011f96dff7b176c3d609065ebe9889249b40f611b950b369f6d4a0bc45325faff307f",
          "sha256": "9e3ced5087ff565c019d2bee855afb04f6712da1fb12caaf994d12f716de17c8",
          "sha1": "73ec4c44caa1e14b91c458127efd136bdefedce9",
          "md5": "8f981845bde6f2b9626687dcd60db26d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+03-all.jar",
          "url": "gli-0.8.3.0-16+03-all.jar",
          "size": 8646028,
          "sha512": "58f75209989114639e8211979db965f25b0e228c000175d73c6965e48190493d7a7a823b6a6647856db1f9b766195bb2f9ebcee719d806795c62db45ca906084",
          "sha256": "0fcb946e638372960aeb24837044a791c8599800bd88e97ecdf46bd4fa5b813c",
          "sha1": "8dde4cb52dc7559dd7073598becb990a5b18bb7c",
          "md5": "a04c317ac73c7fdef78986a7e3830461"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+03-sources.jar",
          "url": "gli-0.8.3.0-16+03-sources.jar",
          "size": 67684,
          "sha512": "6a0b6506b6cb6967bcabe0701c219d0f146b2606f146c716a10616494950cb96eee7ff225cce7e66b6bf8004282f0720af231a180b42bc595052b1d7d2490668",
          "sha256": "64b8c534437769026878323351982da5dcf272f650e389f8447a7c80626ff0b2",
          "sha1": "157df63e1fca63b46dc8eecbfe767a221c1c8242",
          "md5": "d911379abeb92cf2594ff86d21c02cc3"
        }
      ]
    }
  ]
}
