{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.9+51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+51.jar",
          "url": "uno-0.7.9+51.jar",
          "size": 261,
          "sha512": "3ab52b43c85d4fcb58d146769f4d12fbac0db8a1db783eb1a23d6c0eed3bc6096ebca4941f6efc537f2e4a4d2e6c6742c3b95a79699c6b416a9b4f271bfcf5bd",
          "sha256": "6b20992f094d7ac2e14f6e2a37c700a91634761f2ae92169761401f16fa57ca8",
          "sha1": "3a45468eccfb1ff73a6f70bbe060382ed3ac3fea",
          "md5": "29ab972c1f6c756c2f835389b7793994"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+51"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+51.jar",
          "url": "uno-0.7.9+51.jar",
          "size": 261,
          "sha512": "3ab52b43c85d4fcb58d146769f4d12fbac0db8a1db783eb1a23d6c0eed3bc6096ebca4941f6efc537f2e4a4d2e6c6742c3b95a79699c6b416a9b4f271bfcf5bd",
          "sha256": "6b20992f094d7ac2e14f6e2a37c700a91634761f2ae92169761401f16fa57ca8",
          "sha1": "3a45468eccfb1ff73a6f70bbe060382ed3ac3fea",
          "md5": "29ab972c1f6c756c2f835389b7793994"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+51-all.jar",
          "url": "uno-0.7.9+51-all.jar",
          "size": 63593263,
          "sha512": "ce9d30dc26667f4825ecd79de1936eade8025c648119f3718181a6d42a0c54e0148e7f2e31fecf91c298309ff7a30667447eac80f4e06534b765fb0a8320e40a",
          "sha256": "b90453b2e75106eb0a41e657cfe28e00a03c962ff9995c8368e52fc30c68e9a1",
          "sha1": "d25b0c4a519da8165d9dc7d87a39869bc9175b5b",
          "md5": "e62568354c930d2ce2671021217c3657"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-0.7.9+51-jdk8.jar",
          "url": "uno-0.7.9+51-jdk8.jar",
          "size": 261,
          "sha512": "9a56d4c78c9ed0d267a36565ce34faa6f305f2b26f87d6606c78abdbc428b630eaf09f3193f4e1bd99ee90b71b8f83f4823a862813862adb6519a32be0cd67f4",
          "sha256": "a9f17543df104de14750560b258c226267015b19aaceb439d648aa3752529ee0",
          "sha1": "2425293f0398b3ba719cf37cb76f014ad37ec29a",
          "md5": "1da0821effa5fabb73dab47ecc64c478"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+51"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+51"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+51-jdk8.jar",
          "url": "uno-0.7.9+51-jdk8.jar",
          "size": 261,
          "sha512": "9a56d4c78c9ed0d267a36565ce34faa6f305f2b26f87d6606c78abdbc428b630eaf09f3193f4e1bd99ee90b71b8f83f4823a862813862adb6519a32be0cd67f4",
          "sha256": "a9f17543df104de14750560b258c226267015b19aaceb439d648aa3752529ee0",
          "sha1": "2425293f0398b3ba719cf37cb76f014ad37ec29a",
          "md5": "1da0821effa5fabb73dab47ecc64c478"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+51-sources.jar",
          "url": "uno-0.7.9+51-sources.jar",
          "size": 261,
          "sha512": "3ab52b43c85d4fcb58d146769f4d12fbac0db8a1db783eb1a23d6c0eed3bc6096ebca4941f6efc537f2e4a4d2e6c6742c3b95a79699c6b416a9b4f271bfcf5bd",
          "sha256": "6b20992f094d7ac2e14f6e2a37c700a91634761f2ae92169761401f16fa57ca8",
          "sha1": "3a45468eccfb1ff73a6f70bbe060382ed3ac3fea",
          "md5": "29ab972c1f6c756c2f835389b7793994"
        }
      ]
    }
  ]
}
