{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.2.jar",
          "url": "lwjgl-0.7.2.jar",
          "size": 166192,
          "sha512": "0751a81043a293fd916085897bd0fcae908060db9d5b4be73588a22f150ae117cac34f119197bde13a46da6ec9c7f5834fae3e69f8db5b367d65db477f0e91cb",
          "sha256": "2e8bc8a6a717515de000e78acda8170c67cb7f4da052f54cfe483117a725856c",
          "sha1": "c37f227577015ef24ae017aed9ca4eb48381b498",
          "md5": "29f9c41aa9ccec3abec344a5daa86198"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.2.jar",
          "url": "lwjgl-0.7.2.jar",
          "size": 166192,
          "sha512": "0751a81043a293fd916085897bd0fcae908060db9d5b4be73588a22f150ae117cac34f119197bde13a46da6ec9c7f5834fae3e69f8db5b367d65db477f0e91cb",
          "sha256": "2e8bc8a6a717515de000e78acda8170c67cb7f4da052f54cfe483117a725856c",
          "sha1": "c37f227577015ef24ae017aed9ca4eb48381b498",
          "md5": "29f9c41aa9ccec3abec344a5daa86198"
        }
      ]
    }
  ]
}
