{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+57.jar",
          "url": "commons-0.7.0+57.jar",
          "size": 358999,
          "sha512": "e83144254e0558ba0863780bd132b8d832c4f287c9989d79778b85f748c71e58698f7196268036366d3fd66f4bb22867418ce91943ab433d97f681d846cbb827",
          "sha256": "3b56030331e2436c8fb69f70bfef2185ef5a077ad0d073633159d0af427b73be",
          "sha1": "60751f6323fc3b9f8ac65a9a5d47021a0e5f9dae",
          "md5": "a60c48ecd86fd9db2a24f372d4ffd37e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+57"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+57.jar",
          "url": "commons-0.7.0+57.jar",
          "size": 358999,
          "sha512": "e83144254e0558ba0863780bd132b8d832c4f287c9989d79778b85f748c71e58698f7196268036366d3fd66f4bb22867418ce91943ab433d97f681d846cbb827",
          "sha256": "3b56030331e2436c8fb69f70bfef2185ef5a077ad0d073633159d0af427b73be",
          "sha1": "60751f6323fc3b9f8ac65a9a5d47021a0e5f9dae",
          "md5": "a60c48ecd86fd9db2a24f372d4ffd37e"
        }
      ]
    }
  ]
}
