{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "kx",
    "version": "0.7.0+92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vaamy6pnvjchlkckua4mzm73tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+92.jar",
          "url": "kx-0.7.0+92.jar",
          "size": 18928,
          "sha512": "fcf422f74e1db466d84c72db047a46d332c95cb818a385d843dd83de49c3157131cbd7bbf9a991659846995318d6a6d4aa78c129c5f2f86428986a3f4e5dbf32",
          "sha256": "d81af99d78d84d7df6b20a7e2a95f4bc601cf698af78a975dbc05082e98100b4",
          "sha1": "d6a4ded744030cdb427a874324c617e377f84f31",
          "md5": "9e802074c1f4746dc0618bc4eebada6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+92.jar",
          "url": "kx-0.7.0+92.jar",
          "size": 18928,
          "sha512": "fcf422f74e1db466d84c72db047a46d332c95cb818a385d843dd83de49c3157131cbd7bbf9a991659846995318d6a6d4aa78c129c5f2f86428986a3f4e5dbf32",
          "sha256": "d81af99d78d84d7df6b20a7e2a95f4bc601cf698af78a975dbc05082e98100b4",
          "sha1": "d6a4ded744030cdb427a874324c617e377f84f31",
          "md5": "9e802074c1f4746dc0618bc4eebada6d"
        }
      ]
    }
  ]
}
