{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.platform",
    "module": "plugin",
    "version": "v0.1.9-15-0a10bfd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin",
          "version": {
            "requires": "6.1.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin",
          "version": {
            "requires": "6.1.0"
          }
        }
      ]
    }
  ]
}
