{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.sample",
    "module": "prova",
    "version": "0.1(kotlin.String) -> kotlin.String",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "prova-0.1.jar",
          "url": "prova-0.1.jar",
          "size": 261,
          "sha512": "e7c5aa61cc72126a5658a97986e132bc401ff381a0e83afe3c631534e29e6265caeeeb9592b8b887fece385d7dc867eb6573b74ca56aa71af9cfcc25fe953101",
          "sha256": "83e92a4b92292f70848cf35b586d81dc2dd4dcffad51d97bd17d69b6ecb53f01",
          "sha1": "d933440683ddedd4a7cd7e543345ada665434bef",
          "md5": "d35ab0c122aed937d5676e604b0d2e35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "prova-0.1.jar",
          "url": "prova-0.1.jar",
          "size": 261,
          "sha512": "e7c5aa61cc72126a5658a97986e132bc401ff381a0e83afe3c631534e29e6265caeeeb9592b8b887fece385d7dc867eb6573b74ca56aa71af9cfcc25fe953101",
          "sha256": "83e92a4b92292f70848cf35b586d81dc2dd4dcffad51d97bd17d69b6ecb53f01",
          "sha1": "d933440683ddedd4a7cd7e543345ada665434bef",
          "md5": "d35ab0c122aed937d5676e604b0d2e35"
        }
      ]
    }
  ]
}
