{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-core",
    "version": "1.79+04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "imgui-core-1.79+04.jar",
          "url": "imgui-core-1.79+04.jar",
          "size": 17463358,
          "sha512": "f17f344f08dc95c62abb64640ac28bc3daf566b49efb91bb8133e2627902422f60827f672b67d91243cff3ec7d486232103e611aa4e02f91c4916127e6496904",
          "sha256": "729a010ce2751040ba4d1774d390cdc729ef4e698410da2fb75542c333dce905",
          "sha1": "0f0a5ed66fa262fcff906a6873b35b3592f73e48",
          "md5": "4537f309b88859f2c27d35d792928567"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+46"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-core-1.79+04.jar",
          "url": "imgui-core-1.79+04.jar",
          "size": 17463358,
          "sha512": "f17f344f08dc95c62abb64640ac28bc3daf566b49efb91bb8133e2627902422f60827f672b67d91243cff3ec7d486232103e611aa4e02f91c4916127e6496904",
          "sha256": "729a010ce2751040ba4d1774d390cdc729ef4e698410da2fb75542c333dce905",
          "sha1": "0f0a5ed66fa262fcff906a6873b35b3592f73e48",
          "md5": "4537f309b88859f2c27d35d792928567"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-core-1.79+04-all.jar",
          "url": "imgui-core-1.79+04-all.jar",
          "size": 30606586,
          "sha512": "040b90fa8cdc2c7e26c939a1a2395dd355de154e7d099c65e7571c5fd66136d218863266f6e7d8d8e509a7db9a7c637028142421a888c37c2c733dad9ddbf2a2",
          "sha256": "ed1a6699d436d8df2479181bdf8c03e247d525b53f57b82583652baf70007b4c",
          "sha1": "a488521b98f46da55013d83dfd927f9db5b939f0",
          "md5": "7a1f34bcd583a3a505aa8b314ff308cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-core-1.79+04-sources.jar",
          "url": "imgui-core-1.79+04-sources.jar",
          "size": 15944136,
          "sha512": "dd6ac4fbfe325e4d703e6d36679d469287762382db37bc8ed34248ab2cf482ff74a27d7912fb31192d9162c830f4fbe79407d21c56f7967520254deab5a275c9",
          "sha256": "fcadd80ea2d3416a9f7c0a0415e1b9606dec8df661907b242bd8fd9c555a4ee9",
          "sha1": "da5d57731fb112b655138cebe2e4b292e3200e26",
          "md5": "9a4bed9f9ee147d8882c88bc578557a0"
        }
      ]
    }
  ]
}
