{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+95",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lcfcuksm2jagjhl3nervg372re"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+95.jar",
          "url": "commons-0.7.0+95.jar",
          "size": 355750,
          "sha512": "38619fb463d5bd271661c392db77fa2b77d5c09558a5a73e20757b47a3a4b883d8ad321aa8d7e6b81ee4db46ada16617a7096deaec495b11dfde65881776837d",
          "sha256": "54826bf7d37bbe6d3fe61a5c443e6026906dfd365847499b5e04e6322002ed76",
          "sha1": "b4fac2bb7c9ddad7e4ea4f4881ef2fd071cecaf4",
          "md5": "596bc11afe89e3b2e1630aab7753ff2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+95"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+95.jar",
          "url": "commons-0.7.0+95.jar",
          "size": 355750,
          "sha512": "38619fb463d5bd271661c392db77fa2b77d5c09558a5a73e20757b47a3a4b883d8ad321aa8d7e6b81ee4db46ada16617a7096deaec495b11dfde65881776837d",
          "sha256": "54826bf7d37bbe6d3fe61a5c443e6026906dfd365847499b5e04e6322002ed76",
          "sha1": "b4fac2bb7c9ddad7e4ea4f4881ef2fd071cecaf4",
          "md5": "596bc11afe89e3b2e1630aab7753ff2f"
        }
      ]
    }
  ]
}
