{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6j7pmn4rinen7ms75twgo2clru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+88.jar",
          "url": "docs-0.7.0+88.jar",
          "size": 311941,
          "sha512": "faf2349917940767247b7ab68001d75dbdd7c3f3fbe3d3aa45e3e965d0afbfda9cc14a0fb0dc0abb7c6b128a77678c1a2856f6f418a1359c19120bfc00047b03",
          "sha256": "4852c77d240a64bfbdd2fc2a57a7c8fd79042eae25a8decf49f2d2cb93b9805f",
          "sha1": "115d4417dd877f48a3c7a80bfdab6452aa5af6c0",
          "md5": "243cab1f441c6dbe2103859608cf48e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+88.jar",
          "url": "docs-0.7.0+88.jar",
          "size": 311941,
          "sha512": "faf2349917940767247b7ab68001d75dbdd7c3f3fbe3d3aa45e3e965d0afbfda9cc14a0fb0dc0abb7c6b128a77678c1a2856f6f418a1359c19120bfc00047b03",
          "sha256": "4852c77d240a64bfbdd2fc2a57a7c8fd79042eae25a8decf49f2d2cb93b9805f",
          "sha1": "115d4417dd877f48a3c7a80bfdab6452aa5af6c0",
          "md5": "243cab1f441c6dbe2103859608cf48e4"
        }
      ]
    }
  ]
}
