{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.68.jar",
          "url": "kool-0.9.68.jar",
          "size": 263758,
          "sha512": "487c3a7ccfd648b970c8bf1e8a18d9563fc9a9e2b43ca53bf732d2a8df9c38971458e6d048df3caad76d27744fb70c293d478e625d629e73d2bd25b8ab1e708e",
          "sha256": "8971be24489575f14b8689682e268350c91af564341b12aa7fc2a2d59505dbde",
          "sha1": "a6f0101700c5fd5e6a0cd0389c9d3616c9f77092",
          "md5": "05173a83f4ccb87dbfbc6a3403fc8bfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.68.jar",
          "url": "kool-0.9.68.jar",
          "size": 263758,
          "sha512": "487c3a7ccfd648b970c8bf1e8a18d9563fc9a9e2b43ca53bf732d2a8df9c38971458e6d048df3caad76d27744fb70c293d478e625d629e73d2bd25b8ab1e708e",
          "sha256": "8971be24489575f14b8689682e268350c91af564341b12aa7fc2a2d59505dbde",
          "sha1": "a6f0101700c5fd5e6a0cd0389c9d3616c9f77092",
          "md5": "05173a83f4ccb87dbfbc6a3403fc8bfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.68-sources.jar",
          "url": "kool-0.9.68-sources.jar",
          "size": 46859,
          "sha512": "4f3f72d28b9af0ae01c2341e186178deac3842fe0429bf13ad8ca40f265f9c819e1a67d550fca695883ed9201a07c97f1515b95619a1f59b18734a122511f6ea",
          "sha256": "264c3de0f010939a1d29ceec8ad058aaf52a33cb327fd9f578a69c9f3ec0545f",
          "sha1": "93a7efa2b3c52f733cef6c46cbb82a199f13e42c",
          "md5": "2415614fa9cfa14bd54daa7db9497413"
        }
      ]
    }
  ]
}
