{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-awt",
    "version": "0.7.9+51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+51.jar",
          "url": "uno-awt-0.7.9+51.jar",
          "size": 19166,
          "sha512": "ac2d7cadb746bded47ca497fc23beec1a741386a49d0702f2a0e99d4b76e370e648adcc5b9a9fc0ca574b29e64c72443f7402cf51d15410752da94b53fedb73b",
          "sha256": "a546578bdd832bc1040121c85a76cbeb069a122647ffaa9da243ebdc8a0c10dd",
          "sha1": "673abfc37fbe6f4e9cdc3a4b3f966debab916ea8",
          "md5": "173ece306b95550115476e990689cf12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+51.jar",
          "url": "uno-awt-0.7.9+51.jar",
          "size": 19166,
          "sha512": "ac2d7cadb746bded47ca497fc23beec1a741386a49d0702f2a0e99d4b76e370e648adcc5b9a9fc0ca574b29e64c72443f7402cf51d15410752da94b53fedb73b",
          "sha256": "a546578bdd832bc1040121c85a76cbeb069a122647ffaa9da243ebdc8a0c10dd",
          "sha1": "673abfc37fbe6f4e9cdc3a4b3f966debab916ea8",
          "md5": "173ece306b95550115476e990689cf12"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+51-all.jar",
          "url": "uno-awt-0.7.9+51-all.jar",
          "size": 13180525,
          "sha512": "d5b303690438faa6242cdad4d96358363b892f763ed67dec553e91fe821455e0a7b6584a8b00c8e7410b8ba64758d142cb8612025b2bf8d0f8a8247a5f48f96d",
          "sha256": "0eb6720b919ba42d304de510eeaff4761df9f3210c22a62a7aa0cdfaa4c1e0a6",
          "sha1": "68b7a0cc974bf7aa869b79ad75bc32e2785efd03",
          "md5": "ef046a14f70ddf65404761372c9b4eff"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+51-jdk8.jar",
          "url": "uno-awt-0.7.9+51-jdk8.jar",
          "size": 18703,
          "sha512": "45d81f558c483e8778dc0ac2cc4ccdb8683a8827e01484bedbc5383e7bba3659dd285c0e2725f9b0d9ea71c31b6a20f095a9c77b13876bda43f97b111a6f8f53",
          "sha256": "ce70966e94b280fc40b2a7d2737cf16ee09565178c1cebe62ece570dd7c14787",
          "sha1": "973cbf8dfb9626c16ad90cf4b5ef764056e5f9f2",
          "md5": "9f802219d03a82914fe12dd654e9db2c"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+51"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+51"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+41"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+41"
          }
        }
      ],
      "files": [
        {
          "name": "uno-awt-0.7.9+51-jdk8.jar",
          "url": "uno-awt-0.7.9+51-jdk8.jar",
          "size": 18703,
          "sha512": "45d81f558c483e8778dc0ac2cc4ccdb8683a8827e01484bedbc5383e7bba3659dd285c0e2725f9b0d9ea71c31b6a20f095a9c77b13876bda43f97b111a6f8f53",
          "sha256": "ce70966e94b280fc40b2a7d2737cf16ee09565178c1cebe62ece570dd7c14787",
          "sha1": "973cbf8dfb9626c16ad90cf4b5ef764056e5f9f2",
          "md5": "9f802219d03a82914fe12dd654e9db2c"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-awt-0.7.9+51-sources.jar",
          "url": "uno-awt-0.7.9+51-sources.jar",
          "size": 3978,
          "sha512": "94efe694047175052f65b162a9c28ec9b0d5b362ea9b1afce2ff6254d4954aa64ad8a46789d6df206b50c3f1f48763df7de8dc8a4f2bb888905681dda77cf158",
          "sha256": "a5e2e4c2ee4fa8c2fc7365f1838e7a182c5c9619418edf919b2222837e09d249",
          "sha1": "b9bfc1c669a3366ac0aa141194ca22be396a1559",
          "md5": "2c3e7e5133ea0732a5c3e1858de7a893"
        }
      ]
    }
  ]
}
