{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "unsigned",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "unsigned-3.3.0.jar",
          "url": "unsigned-3.3.0.jar",
          "size": 48242,
          "sha512": "163c0162c1eea7f76d37a7a66a586fad64e2c4aa8b17bb2021790291a11d4c89b6ecd719509a0e4dea165619cf7b5f1b3f5b48558dd35858635eeda7e9615b8e",
          "sha256": "e483e56b0b257968ade1057c421f4ff72dbdafc2b8970a904d050548eec35e7a",
          "sha1": "9e7348a6775950a4551a14225086ac17bfb35104",
          "md5": "91e2fa3384029115f54ac180c70d956b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "unsigned-3.3.0.jar",
          "url": "unsigned-3.3.0.jar",
          "size": 48242,
          "sha512": "163c0162c1eea7f76d37a7a66a586fad64e2c4aa8b17bb2021790291a11d4c89b6ecd719509a0e4dea165619cf7b5f1b3f5b48558dd35858635eeda7e9615b8e",
          "sha256": "e483e56b0b257968ade1057c421f4ff72dbdafc2b8970a904d050548eec35e7a",
          "sha1": "9e7348a6775950a4551a14225086ac17bfb35104",
          "md5": "91e2fa3384029115f54ac180c70d956b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unsigned-3.3.0-all.jar",
          "url": "unsigned-3.3.0-all.jar",
          "size": 1793611,
          "sha512": "6f14c9e7318c06060537c9078fd471e7d444e30a9b7fcc38ab94defe75f4c71a41dce3c9f6db3370086e0ffdda48ee34658d1cd81a5f5b4a8850ebaa653247f8",
          "sha256": "5f6b91b1982fa2166c6a075b0b674cff7369387737d4195f712dd6d8c9d5ba13",
          "sha1": "2a35968a37968b10043ba12c27de7d4a04156f1c",
          "md5": "5026993d549b4936bae24cedbd081508"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unsigned-3.3.0-sources.jar",
          "url": "unsigned-3.3.0-sources.jar",
          "size": 9459,
          "sha512": "45911f8dd8add0141fef3e24ae502f11c5f292ef2667d680e17f1f2ebcdded03c47c499e0942112b6ec0137a14d7b0adf8f211135c5a3e2678bb6f7fa3b579aa",
          "sha256": "fae0e1cac7632f5bc4a72eca18c6ee8df91a0132b77963d7be867d643a686b5a",
          "sha1": "c65ecc50cb9fc22ee871198b77fff8c5aa33d230",
          "md5": "7a673d31f7255417783f1a5c0abc7165"
        }
      ]
    }
  ]
}
