{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "glm",
    "version": "0.9.9.1-3+24++25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+25"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+24.jar",
          "url": "glm-0.9.9.1-3+24.jar",
          "size": 2178928,
          "sha512": "d54e4e16f49e54179b178620fdd561c38ac92d224b9aca3a5e3da7a784d96b607dc370c6ff4ac1248317ddb9bec71a81f1dc3e138921974634f45573fec2ae7f",
          "sha256": "442ce248f12ad19ef7ca3067ecec09007fac20a074f9f704158a56e491cf3d1f",
          "sha1": "cd739ee27372ed44887e71b13e15803191251443",
          "md5": "bb2100d607f46bb0520838b20de31e97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+25"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+24.jar",
          "url": "glm-0.9.9.1-3+24.jar",
          "size": 2178928,
          "sha512": "d54e4e16f49e54179b178620fdd561c38ac92d224b9aca3a5e3da7a784d96b607dc370c6ff4ac1248317ddb9bec71a81f1dc3e138921974634f45573fec2ae7f",
          "sha256": "442ce248f12ad19ef7ca3067ecec09007fac20a074f9f704158a56e491cf3d1f",
          "sha1": "cd739ee27372ed44887e71b13e15803191251443",
          "md5": "bb2100d607f46bb0520838b20de31e97"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+24-all.jar",
          "url": "glm-0.9.9.1-3+24-all.jar",
          "size": 7307148,
          "sha512": "ac4f161956979690f375ff8ede433bb85d0569a3e83b8e87f59bcbd21c81ecf9ff808a1a83cbaad4410b71fa67d5aa4ea6d1f25b8426ef676dc4a3b1fbed2fa4",
          "sha256": "37ab90be09679dd39395705d33735ce7fe7a3e383d96ab654b16297eb2fa6dcb",
          "sha1": "79b178634a0f08251eb7e6cb5767bc3baab28004",
          "md5": "f60fcb08c53bc3a1f8db7065d7db0357"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+24-jdk8.jar",
          "url": "glm-0.9.9.1-3+24-jdk8.jar",
          "size": 2165057,
          "sha512": "3c79da06813d27a946a9005c8e443de613fcfa5fdc0cb80f75dc445c1fe3d936281a8f59e74d963f65fd70c33b11427189e5da4f01259507986eb6e1a4cff97f",
          "sha256": "aa37ae6923c881cf8b2a13e1bb37ac70d057b4ef52629ebdaf70f6d3a9ea2f8a",
          "sha1": "1a5878f4c3ef72b60e916fedbfc075a613e2b559",
          "md5": "1f54d92e50892d1649e67b79e454a340"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-3+24"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+25"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-3+24-jdk8.jar",
          "url": "glm-0.9.9.1-3+24-jdk8.jar",
          "size": 2165057,
          "sha512": "3c79da06813d27a946a9005c8e443de613fcfa5fdc0cb80f75dc445c1fe3d936281a8f59e74d963f65fd70c33b11427189e5da4f01259507986eb6e1a4cff97f",
          "sha256": "aa37ae6923c881cf8b2a13e1bb37ac70d057b4ef52629ebdaf70f6d3a9ea2f8a",
          "sha1": "1a5878f4c3ef72b60e916fedbfc075a613e2b559",
          "md5": "1f54d92e50892d1649e67b79e454a340"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-3+24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-3+24-sources.jar",
          "url": "glm-0.9.9.1-3+24-sources.jar",
          "size": 424754,
          "sha512": "56b95a5e5f3aeeea711194e3e1cf15d00a9c6cb0b57ba8a42030320fe317390547c29a3d3f5630acc4e141bceea60b36658f169b1d6ea77fd0cc70afb71553bc",
          "sha256": "26eea297bd6f140c0c5f36d02af6ccf51109f7518a66b9b92b66fde25171e05a",
          "sha1": "90cd2bff5408548611e17f9c378c9371d27df129",
          "md5": "17d91062e41a680d4ff85bbe5a0df696"
        }
      ]
    }
  ]
}
