{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+36.jar",
          "url": "commons-0.7.0+36.jar",
          "size": 325160,
          "sha512": "3d3ed617d9d342f0a3dca1cb2f8a82a6f857786646195042af4eb761f9d34369bda5065d410f98be97221f07c24fa63760326e4856a5f3abc3e8b4b7d39e303e",
          "sha256": "4b5e5dda07d82f16ad3440daf101680301494dd782aded54321958e2f57476af",
          "sha1": "d1718e22f4e920e3002c7aed905b97182d3802e5",
          "md5": "8c4dcac09414a32ba9ef30414ca9252d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+36"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+36"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+36.jar",
          "url": "commons-0.7.0+36.jar",
          "size": 325160,
          "sha512": "3d3ed617d9d342f0a3dca1cb2f8a82a6f857786646195042af4eb761f9d34369bda5065d410f98be97221f07c24fa63760326e4856a5f3abc3e8b4b7d39e303e",
          "sha256": "4b5e5dda07d82f16ad3440daf101680301494dd782aded54321958e2f57476af",
          "sha1": "d1718e22f4e920e3002c7aed905b97182d3802e5",
          "md5": "8c4dcac09414a32ba9ef30414ca9252d"
        }
      ]
    }
  ]
}
