{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "core",
    "version": "0.7.9+39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+39.jar",
          "url": "core-0.7.9+39.jar",
          "size": 140805,
          "sha512": "5a6220ce67ccb32c381920569fcf44654c3a1782e42d7b062e0ecbfe49c2d6ae3869334c53b93b23a6b4ea7a786d9b894bf44c1d21da0e8adcddb1d8485f1c47",
          "sha256": "0577048993d6e68818b1841597624f9557edbf848450441795caefc2e9c13971",
          "sha1": "5e74c0d57a7092e40e1ca96667de48ed6ec0128c",
          "md5": "673f9bb6baad708fdab1846635077e23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+39.jar",
          "url": "core-0.7.9+39.jar",
          "size": 140805,
          "sha512": "5a6220ce67ccb32c381920569fcf44654c3a1782e42d7b062e0ecbfe49c2d6ae3869334c53b93b23a6b4ea7a786d9b894bf44c1d21da0e8adcddb1d8485f1c47",
          "sha256": "0577048993d6e68818b1841597624f9557edbf848450441795caefc2e9c13971",
          "sha1": "5e74c0d57a7092e40e1ca96667de48ed6ec0128c",
          "md5": "673f9bb6baad708fdab1846635077e23"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.7.9+39-all.jar",
          "url": "core-0.7.9+39-all.jar",
          "size": 13140016,
          "sha512": "9fd14f87c3d9d35f245c9c0f886e8c6fd55c7530a785e6cb79d4b7814b4034db7f1ce39a3759f1ab5b2546ccb1069bb061dba5ca947b00117394623a9d4a812c",
          "sha256": "94ae133fc585983725f46f9444edf08bee32845597c128cb14cba23e61ca2576",
          "sha1": "f7f603fbd50fa6d4e2c9a453930bdb9470157eb2",
          "md5": "8e5b75a6b08deb12a7631acbae042344"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.7.9+39-jdk8.jar",
          "url": "core-0.7.9+39-jdk8.jar",
          "size": 140711,
          "sha512": "8a6795ba6624e1366f849a44ea3a5c55601e135784b9aec581694b281820b1ac3d58207186c64d4f670f7536aaac8dc398b1dc3a733b8ede917113daa3a859b4",
          "sha256": "2642ccca6964f84b15c3eae3cdcc90c00f77a925184373a8590303d333d7578f",
          "sha1": "95c83a8f810e18738bdfd3de4d212b3dac30191c",
          "md5": "89d5438f43fe061909989b8679ec0fe1"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+39"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+39-jdk8.jar",
          "url": "core-0.7.9+39-jdk8.jar",
          "size": 140711,
          "sha512": "8a6795ba6624e1366f849a44ea3a5c55601e135784b9aec581694b281820b1ac3d58207186c64d4f670f7536aaac8dc398b1dc3a733b8ede917113daa3a859b4",
          "sha256": "2642ccca6964f84b15c3eae3cdcc90c00f77a925184373a8590303d333d7578f",
          "sha1": "95c83a8f810e18738bdfd3de4d212b3dac30191c",
          "md5": "89d5438f43fe061909989b8679ec0fe1"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.7.9+39-sources.jar",
          "url": "core-0.7.9+39-sources.jar",
          "size": 37180,
          "sha512": "4fef34543eacb4d06100d1218cb7912d3e020f123e3a110a0c195e81f267188e5be85693c610edc11e17eadd1b1e171b4b066e3db117c45aaa3460aefacd1a11",
          "sha256": "02ced45d76bcdac2909f3002ec98476db22be72be19adcefb366e0a7bbcce1c5",
          "sha1": "10755cead15e999c31e6eca7a546e1c1ea4091fe",
          "md5": "2d879d6b08a222248b38cf5095566bfb"
        }
      ]
    }
  ]
}
