{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.10.jar",
          "url": "uno-0.7.10.jar",
          "size": 261,
          "sha512": "b51a767a29ef14a9efea24e10f7a53957a97c5cc1fbad5aab456efd70316459239f6a77dc7529ab11532a40c4e92c78eb75a45902785159199e1530be08c0357",
          "sha256": "8af0eaa33deb95b491575b4ec33e2b694ac2c703951e360c46c76d837f66f561",
          "sha1": "02762ef959922383fe51065571d15f1dc64cde93",
          "md5": "027c104680fd986607f4bb7b26b4d0d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.10.jar",
          "url": "uno-0.7.10.jar",
          "size": 261,
          "sha512": "b51a767a29ef14a9efea24e10f7a53957a97c5cc1fbad5aab456efd70316459239f6a77dc7529ab11532a40c4e92c78eb75a45902785159199e1530be08c0357",
          "sha256": "8af0eaa33deb95b491575b4ec33e2b694ac2c703951e360c46c76d837f66f561",
          "sha1": "02762ef959922383fe51065571d15f1dc64cde93",
          "md5": "027c104680fd986607f4bb7b26b4d0d8"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-0.7.10-jdk8.jar",
          "url": "uno-0.7.10-jdk8.jar",
          "size": 261,
          "sha512": "e04315f4bbed08878df49be409d5b6d0a66613c37f58e385a16e8ab1f7cd75b2bfb7d090d637a333874b95b74bf2d16629b075b1bb5d513351bfe59690619c7a",
          "sha256": "952f6140a4e206f00532e93e3a54e77c42185a3132fd54530aa4c4c7a35f7c7e",
          "sha1": "4224f757fa83c770f1a967079d9c6078b839f392",
          "md5": "d3d54763f549d2d39b274297964c325b"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.10"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.10"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.10-jdk8.jar",
          "url": "uno-0.7.10-jdk8.jar",
          "size": 261,
          "sha512": "e04315f4bbed08878df49be409d5b6d0a66613c37f58e385a16e8ab1f7cd75b2bfb7d090d637a333874b95b74bf2d16629b075b1bb5d513351bfe59690619c7a",
          "sha256": "952f6140a4e206f00532e93e3a54e77c42185a3132fd54530aa4c4c7a35f7c7e",
          "sha1": "4224f757fa83c770f1a967079d9c6078b839f392",
          "md5": "d3d54763f549d2d39b274297964c325b"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.10-sources.jar",
          "url": "uno-0.7.10-sources.jar",
          "size": 261,
          "sha512": "b51a767a29ef14a9efea24e10f7a53957a97c5cc1fbad5aab456efd70316459239f6a77dc7529ab11532a40c4e92c78eb75a45902785159199e1530be08c0357",
          "sha256": "8af0eaa33deb95b491575b4ec33e2b694ac2c703951e360c46c76d837f66f561",
          "sha1": "02762ef959922383fe51065571d15f1dc64cde93",
          "md5": "027c104680fd986607f4bb7b26b4d0d8"
        }
      ]
    }
  ]
}
