{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.platform",
    "module": "source-dynamic",
    "version": "0.3.3+17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "source-dynamic-0.3.3+17.jar",
          "url": "source-dynamic-0.3.3+17.jar",
          "size": 14250,
          "sha512": "f643d183a6aad8ec5e1a06bd1c02ba8e3790fc2cbb3ab6ae24e2aaa9ab8ad139e78866894b1dac3ad36e68297457d768d59b653460c2e29dc3bc0cea674a335a",
          "sha256": "e6a55c9ec7b8c3af872aa56e12f3636098b028bafb8d790172eb48c97c52d161",
          "sha1": "83e655ef11713a87216c2f4563af01576e348c02",
          "md5": "a4e9826fd7931d6cd1e5dc079c9b87c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "source-dynamic-0.3.3+17.jar",
          "url": "source-dynamic-0.3.3+17.jar",
          "size": 14250,
          "sha512": "f643d183a6aad8ec5e1a06bd1c02ba8e3790fc2cbb3ab6ae24e2aaa9ab8ad139e78866894b1dac3ad36e68297457d768d59b653460c2e29dc3bc0cea674a335a",
          "sha256": "e6a55c9ec7b8c3af872aa56e12f3636098b028bafb8d790172eb48c97c52d161",
          "sha1": "83e655ef11713a87216c2f4563af01576e348c02",
          "md5": "a4e9826fd7931d6cd1e5dc079c9b87c1"
        }
      ]
    }
  ]
}
