{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.2.jar",
          "url": "commons-0.7.2.jar",
          "size": 384322,
          "sha512": "09d7802310460242faf62d089d192a76609bbee33155435bd47d120b1c4650b176ff18b655db1078e6b3710667064134119255dc705f0c99fb6abe7070bdb2d0",
          "sha256": "94cd51195164f5988163e0576d969b6a4e9d8673cae81fdd15b2de8b111adb24",
          "sha1": "c6d27429e60074a66ed7d36cef15551f392826c8",
          "md5": "e53343fc7ca5a8a1473c2eaf5264741f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.3.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.2.jar",
          "url": "commons-0.7.2.jar",
          "size": 384322,
          "sha512": "09d7802310460242faf62d089d192a76609bbee33155435bd47d120b1c4650b176ff18b655db1078e6b3710667064134119255dc705f0c99fb6abe7070bdb2d0",
          "sha256": "94cd51195164f5988163e0576d969b6a4e9d8673cae81fdd15b2de8b111adb24",
          "sha1": "c6d27429e60074a66ed7d36cef15551f392826c8",
          "md5": "e53343fc7ca5a8a1473c2eaf5264741f"
        }
      ]
    }
  ]
}
