{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+80",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3inx7swnifbjnb5nxw5ucvephi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+80.jar",
          "url": "11-0.7.0+80.jar",
          "size": 327343,
          "sha512": "2285faa9c8b22af0ead631c2c181f73cb9fa4d10662d0b73d033bd8f72ed2f0ab62d7d166c277541f8754cf2102979f6b6856b7685e6c2b8d4c52140b488e092",
          "sha256": "a877abd63012960622924907da9810c6b808b2a5e381d6354ccd38957d73bd38",
          "sha1": "42d4026bb9ff777c83ff39d1e20903200fcea47a",
          "md5": "f42b60832ba181a357e1275dd766509d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+80"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+80.jar",
          "url": "11-0.7.0+80.jar",
          "size": 327343,
          "sha512": "2285faa9c8b22af0ead631c2c181f73cb9fa4d10662d0b73d033bd8f72ed2f0ab62d7d166c277541f8754cf2102979f6b6856b7685e6c2b8d4c52140b488e092",
          "sha256": "a877abd63012960622924907da9810c6b808b2a5e381d6354ccd38957d73bd38",
          "sha1": "42d4026bb9ff777c83ff39d1e20903200fcea47a",
          "md5": "f42b60832ba181a357e1275dd766509d"
        }
      ]
    }
  ]
}
