{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "v0.7.0-11-ab2e26f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-v0.7.0-11-ab2e26f.jar",
          "url": "lwjgl-v0.7.0-11-ab2e26f.jar",
          "size": 166154,
          "sha512": "161cce559730c1b2a45efe06e42507a314c0a53dcabcbd05af0ac968f79006c6d94d59e2f76508636ceed0d5528b3e156bbe62598c7ebdcb4670891e1215c305",
          "sha256": "76c3f0c398bd60287fefc0139f826952a504b99a870ddbd8d6001a74dc0e332f",
          "sha1": "49f08fc543e027270eaf000977d63b5c2e9de036",
          "md5": "9e6048507ea037f98ac3a7ee1951f431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-11-ab2e26f"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-v0.7.0-11-ab2e26f.jar",
          "url": "lwjgl-v0.7.0-11-ab2e26f.jar",
          "size": 166154,
          "sha512": "161cce559730c1b2a45efe06e42507a314c0a53dcabcbd05af0ac968f79006c6d94d59e2f76508636ceed0d5528b3e156bbe62598c7ebdcb4670891e1215c305",
          "sha256": "76c3f0c398bd60287fefc0139f826952a504b99a870ddbd8d6001a74dc0e332f",
          "sha1": "49f08fc543e027270eaf000977d63b5c2e9de036",
          "md5": "9e6048507ea037f98ac3a7ee1951f431"
        }
      ]
    }
  ]
}
