{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tbajfikvy5btlhrxxbdd5xgf4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+91.jar",
          "url": "lwjgl-0.7.0+91.jar",
          "size": 196037,
          "sha512": "81393abb3ccfc249d4912e63741d7ddfb3d0438d2ce126bffd4eca13eaa48b2f8b21a5ab0c5304d03e2489c13d0e17478b7353ab11ee3332856f5fc912244962",
          "sha256": "045f94944823287eaa605ad049b901f8fc5b1d7f2fb5ca069941cb6741130b3b",
          "sha1": "a3f3ff3bc085baadbe4fe7224557f44a1a9644d1",
          "md5": "08cce3a37b64c88f6a0cd0d0407173b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+91.jar",
          "url": "lwjgl-0.7.0+91.jar",
          "size": 196037,
          "sha512": "81393abb3ccfc249d4912e63741d7ddfb3d0438d2ce126bffd4eca13eaa48b2f8b21a5ab0c5304d03e2489c13d0e17478b7353ab11ee3332856f5fc912244962",
          "sha256": "045f94944823287eaa605ad049b901f8fc5b1d7f2fb5ca069941cb6741130b3b",
          "sha1": "a3f3ff3bc085baadbe4fe7224557f44a1a9644d1",
          "md5": "08cce3a37b64c88f6a0cd0d0407173b3"
        }
      ]
    }
  ]
}
