{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+34.jar",
          "url": "lwjgl-0.7.0+34.jar",
          "size": 166155,
          "sha512": "52a9eb9c3bf36d2b3e47fd521c432085303692c4bfdd7b6654348f7af8cb254ea47d3e6124f5f6e1d0bcd472f21e909a1d59004964e1a9b9092ac7be0eb5405f",
          "sha256": "d591ad757e8184a167b46eef40966e6f716468529e5e8f7a317eef8262f6080a",
          "sha1": "7a7d11ffa0d7c2eb6f1c13ef12916451d4c6e0ec",
          "md5": "85c4d0baa1c58ceccffee18df03b676a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+34"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+34.jar",
          "url": "lwjgl-0.7.0+34.jar",
          "size": 166155,
          "sha512": "52a9eb9c3bf36d2b3e47fd521c432085303692c4bfdd7b6654348f7af8cb254ea47d3e6124f5f6e1d0bcd472f21e909a1d59004964e1a9b9092ac7be0eb5405f",
          "sha256": "d591ad757e8184a167b46eef40966e6f716468529e5e8f7a317eef8262f6080a",
          "sha1": "7a7d11ffa0d7c2eb6f1c13ef12916451d4c6e0ec",
          "md5": "85c4d0baa1c58ceccffee18df03b676a"
        }
      ]
    }
  ]
}
