{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gli",
    "version": "0.8.3.0-21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-21.jar",
          "url": "gli-0.8.3.0-21.jar",
          "size": 332707,
          "sha512": "2bc658e184294507d0460fc22c0b511a1cb6df89bbb89cc7340f3aacccdb1515c439336cbf5789671da96232e99aa3f071678566068ad3c81f8db0422054b61b",
          "sha256": "ccb701f3b968bfa951edb57f2b2a539a2b5b51f130bd5b4ea6bad495e066191c",
          "sha1": "46cc44edc4e2e763e5e783f631e3e296abffe8cf",
          "md5": "cc42cd6d539616b129b7c5fb6762aef6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-21.jar",
          "url": "gli-0.8.3.0-21.jar",
          "size": 332707,
          "sha512": "2bc658e184294507d0460fc22c0b511a1cb6df89bbb89cc7340f3aacccdb1515c439336cbf5789671da96232e99aa3f071678566068ad3c81f8db0422054b61b",
          "sha256": "ccb701f3b968bfa951edb57f2b2a539a2b5b51f130bd5b4ea6bad495e066191c",
          "sha1": "46cc44edc4e2e763e5e783f631e3e296abffe8cf",
          "md5": "cc42cd6d539616b129b7c5fb6762aef6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-21-sources.jar",
          "url": "gli-0.8.3.0-21-sources.jar",
          "size": 68100,
          "sha512": "1efed48f1cfbd703afdb3637d434071fdc8cc5e3c44f94b77150ef0b89403aa3112cd2c63adfce40d7fd2c20cb5c82e773995304a789df3d9184f7f9784f9722",
          "sha256": "a639ef017d1c8e77431a566ea9f42e9e0d07055b58a1d81bd41d38b1cfa81fc3",
          "sha1": "ac8549e13c3dbb41417cd63002b84eff4a4d7fb4",
          "md5": "2c89d5aa6d8c1595a61972dd6a4cd690"
        }
      ]
    }
  ]
}
