{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+52.jar",
          "url": "11-0.7.0+52.jar",
          "size": 326123,
          "sha512": "043ab62268a03df6ea70006e2f1e03aab0012bc64621dbd15edb89d2f6c1b808475c947392ed6e8d9f393ff8903983a8a635a27b9dfab60d9b5f61ab579da045",
          "sha256": "43d4ada031042dcda4fc70368d75cb0f188c90ea5e2ac5753d6dcee5c04d79e6",
          "sha1": "00d2f1f59b1f65c95dc25dff6211ae3b4178ccf9",
          "md5": "f2cc65ae3dced20b666cb61db1b394a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+52"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+52.jar",
          "url": "11-0.7.0+52.jar",
          "size": 326123,
          "sha512": "043ab62268a03df6ea70006e2f1e03aab0012bc64621dbd15edb89d2f6c1b808475c947392ed6e8d9f393ff8903983a8a635a27b9dfab60d9b5f61ab579da045",
          "sha256": "43d4ada031042dcda4fc70368d75cb0f188c90ea5e2ac5753d6dcee5c04d79e6",
          "sha1": "00d2f1f59b1f65c95dc25dff6211ae3b4178ccf9",
          "md5": "f2cc65ae3dced20b666cb61db1b394a0"
        }
      ]
    }
  ]
}
