{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.platform",
    "module": "source",
    "version": "0.3.0+48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.2.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.2.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ]
    }
  ]
}
