{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "reipifdyfrewhmsv4nh3ss7kp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+94.jar",
          "url": "11-0.7.0+94.jar",
          "size": 328882,
          "sha512": "f902dc6cab8df33ecc09833e969115f46247525eef7dee9da2087200ae4ea22ef36bdde750fa7791c07e3e4e261fa4d025d7eb2ae519450741a0f4d0349ed80a",
          "sha256": "56449637bf9fc8915322d13341e4a94ce381796b8d5348bcc67d9b43406e139f",
          "sha1": "6461b66acd2b30f982a1fd9ddf4185b12c8cfe4c",
          "md5": "69fd97256679d1f0152a88bb9cce42a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+94"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+94.jar",
          "url": "11-0.7.0+94.jar",
          "size": 328882,
          "sha512": "f902dc6cab8df33ecc09833e969115f46247525eef7dee9da2087200ae4ea22ef36bdde750fa7791c07e3e4e261fa4d025d7eb2ae519450741a0f4d0349ed80a",
          "sha256": "56449637bf9fc8915322d13341e4a94ce381796b8d5348bcc67d9b43406e139f",
          "sha1": "6461b66acd2b30f982a1fd9ddf4185b12c8cfe4c",
          "md5": "69fd97256679d1f0152a88bb9cce42a9"
        }
      ]
    }
  ]
}
