{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+51.jar",
          "url": "lwjgl-0.7.0+51.jar",
          "size": 166838,
          "sha512": "b4b1df71e8138d524d043bd4a4982e0dbe38dbbc7fca5b29acdad67ac2172d39a3800f194dce2b32ccad662173fad61596c46520623ab611cb0af2f762b14f59",
          "sha256": "36640c1a78bf0394b6825d94f93a13a13ecb97680bfeccd3fa0d9952f1ee9d22",
          "sha1": "9d748e862550c2cf4964c6ef69f8d985743b1768",
          "md5": "26ae26c287722958243da92b000ec344"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+51.jar",
          "url": "lwjgl-0.7.0+51.jar",
          "size": 166838,
          "sha512": "b4b1df71e8138d524d043bd4a4982e0dbe38dbbc7fca5b29acdad67ac2172d39a3800f194dce2b32ccad662173fad61596c46520623ab611cb0af2f762b14f59",
          "sha256": "36640c1a78bf0394b6825d94f93a13a13ecb97680bfeccd3fa0d9952f1ee9d22",
          "sha1": "9d748e862550c2cf4964c6ef69f8d985743b1768",
          "md5": "26ae26c287722958243da92b000ec344"
        }
      ]
    }
  ]
}
