{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "reipifdyfrewhmsv4nh3ss7kp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+94.jar",
          "url": "commons-0.7.0+94.jar",
          "size": 355750,
          "sha512": "cce3dbaf109147703799ba1118e3b400a255e2e5432dd60d2ba4cb043dd35556d44746d58226e145c1e334cfa7efcf1ead18e0e8cb249fdee42e98a42e40a2a9",
          "sha256": "8cdfbfb2acf4255790c241ad48a4208d116180460c522cff002093e964506031",
          "sha1": "6a5b938d67d4274141606660f2b3a1ae52d9de87",
          "md5": "e90615112a4b6913065fb875256442f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+94"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+94.jar",
          "url": "commons-0.7.0+94.jar",
          "size": 355750,
          "sha512": "cce3dbaf109147703799ba1118e3b400a255e2e5432dd60d2ba4cb043dd35556d44746d58226e145c1e334cfa7efcf1ead18e0e8cb249fdee42e98a42e40a2a9",
          "sha256": "8cdfbfb2acf4255790c241ad48a4208d116180460c522cff002093e964506031",
          "sha1": "6a5b938d67d4274141606660f2b3a1ae52d9de87",
          "md5": "e90615112a4b6913065fb875256442f5"
        }
      ]
    }
  ]
}
