{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+59.jar",
          "url": "11-0.7.0+59.jar",
          "size": 326128,
          "sha512": "098978ffabec1a811d26e9e00a89aaa00c10114de47069a3ce09248e2ea6fd52274af2b49ff45f4616e21a5301c85639ea42a167a5554a5a660b6547da049ef7",
          "sha256": "4b319dcf5e80aacebf2e3114d69c4eaceac860712e23d8bad5e3cda089e55c74",
          "sha1": "cbe4bc5958293cf5e55f1411dc541d47f103825d",
          "md5": "75596e5c52e14daff5ddb84adff608a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+59"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+59.jar",
          "url": "11-0.7.0+59.jar",
          "size": 326128,
          "sha512": "098978ffabec1a811d26e9e00a89aaa00c10114de47069a3ce09248e2ea6fd52274af2b49ff45f4616e21a5301c85639ea42a167a5554a5a660b6547da049ef7",
          "sha256": "4b319dcf5e80aacebf2e3114d69c4eaceac860712e23d8bad5e3cda089e55c74",
          "sha1": "cbe4bc5958293cf5e55f1411dc541d47f103825d",
          "md5": "75596e5c52e14daff5ddb84adff608a5"
        }
      ]
    }
  ]
}
