{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.2.jar",
          "url": "11-0.7.2.jar",
          "size": 30058,
          "sha512": "67f452649e611261e2a7cf30048b948b924c969a25ec03259aa8829367c88d7f21155306c5c5c8b4e18916913c5f544a918637990a54eb55c6930fbd6a0dc094",
          "sha256": "0c3f742cf96db719f8f88a285ac151342488aae9e0872fd94363acefd39c260d",
          "sha1": "8c5278b82d970e4fe717cbd09f4c3256a41b9644",
          "md5": "a73b26b8b8cbbf056170fa56b8d8f26e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.2.jar",
          "url": "11-0.7.2.jar",
          "size": 30058,
          "sha512": "67f452649e611261e2a7cf30048b948b924c969a25ec03259aa8829367c88d7f21155306c5c5c8b4e18916913c5f544a918637990a54eb55c6930fbd6a0dc094",
          "sha256": "0c3f742cf96db719f8f88a285ac151342488aae9e0872fd94363acefd39c260d",
          "sha1": "8c5278b82d970e4fe717cbd09f4c3256a41b9644",
          "md5": "a73b26b8b8cbbf056170fa56b8d8f26e"
        }
      ]
    }
  ]
}
