{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+33.jar",
          "url": "commons-0.7.0+33.jar",
          "size": 325161,
          "sha512": "0e7cc9ab5fba851ef8d95b2cc931930817ae916c23888292250a31deb2687f9ca998481a2b933cbaa00a128c37e1ce94dce92fc7a9f24a882582cc9f6a5a2669",
          "sha256": "c3fef27233fa6804a2890b8044553f64e5b470883f78af71f2339e45f903053b",
          "sha1": "ffc78f18c9679523666c5f35d9e3baabb8d9fad2",
          "md5": "749859e984df948a25b401ce121c186d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+33"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+33"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+33.jar",
          "url": "commons-0.7.0+33.jar",
          "size": 325161,
          "sha512": "0e7cc9ab5fba851ef8d95b2cc931930817ae916c23888292250a31deb2687f9ca998481a2b933cbaa00a128c37e1ce94dce92fc7a9f24a882582cc9f6a5a2669",
          "sha256": "c3fef27233fa6804a2890b8044553f64e5b470883f78af71f2339e45f903053b",
          "sha1": "ffc78f18c9679523666c5f35d9e3baabb8d9fad2",
          "md5": "749859e984df948a25b401ce121c186d"
        }
      ]
    }
  ]
}
