{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno",
    "version": "0.7.9+35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+35.jar",
          "url": "uno-0.7.9+35.jar",
          "size": 261,
          "sha512": "62bfadce72fd815436a3c79c3adc0c4974aa4c3f29261e31d8c4d66a24a75b4bf035df555f61a59bc86fe7c77b5bab2cc15e1be7873c43f5f8e73bf0f9dbbaa0",
          "sha256": "eeb2b2f1354626449037f748ad01580faf734df4d156f6ba37fe6395fcf96971",
          "sha1": "719556d582a4384f071807635d4db57eb8e5fef7",
          "md5": "739c7b57dd305ace883ed282117b93de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+35.jar",
          "url": "uno-0.7.9+35.jar",
          "size": 261,
          "sha512": "62bfadce72fd815436a3c79c3adc0c4974aa4c3f29261e31d8c4d66a24a75b4bf035df555f61a59bc86fe7c77b5bab2cc15e1be7873c43f5f8e73bf0f9dbbaa0",
          "sha256": "eeb2b2f1354626449037f748ad01580faf734df4d156f6ba37fe6395fcf96971",
          "sha1": "719556d582a4384f071807635d4db57eb8e5fef7",
          "md5": "739c7b57dd305ace883ed282117b93de"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+35-all.jar",
          "url": "uno-0.7.9+35-all.jar",
          "size": 1745908,
          "sha512": "f6d03f24daf197eddc5fe126ca868bacc619a0972a48e056475c155cd5a039f70b1f5ffba4dfe22751d1d87feaa65668ac12322a685490b73bd95b59d1a163dc",
          "sha256": "d0e9cf6f85fb6ee80953ea3e958006c6a49494acdfab0ab6352719c9d1c1c3a8",
          "sha1": "5081049a076ccae28c44c74683bdbf2bde1b8846",
          "md5": "d35585b538e63fd4d557e5b8f1dfd392"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-0.7.9+35-jdk8.jar",
          "url": "uno-0.7.9+35-jdk8.jar",
          "size": 261,
          "sha512": "9dc7e42ecf623b21a1d0fd0e7b7fadcaafd9c488269c17b9718eef1e4e6d37fbb28586cdd24133b691813bdae7564eacc4bfaee035f7ff227dc83fe6e9b9b8d4",
          "sha256": "a7558329680149193b9e8c1fc5650602b3b39fe3644ba10c86a0566b5c6b84b9",
          "sha1": "ee5a606d16886b5d84192c42a39e6c4c916b8e62",
          "md5": "f7441dfd0d58a020e9429804ce4ea7fc"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+35"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "uno-0.7.9+35-jdk8.jar",
          "url": "uno-0.7.9+35-jdk8.jar",
          "size": 261,
          "sha512": "9dc7e42ecf623b21a1d0fd0e7b7fadcaafd9c488269c17b9718eef1e4e6d37fbb28586cdd24133b691813bdae7564eacc4bfaee035f7ff227dc83fe6e9b9b8d4",
          "sha256": "a7558329680149193b9e8c1fc5650602b3b39fe3644ba10c86a0566b5c6b84b9",
          "sha1": "ee5a606d16886b5d84192c42a39e6c4c916b8e62",
          "md5": "f7441dfd0d58a020e9429804ce4ea7fc"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "uno",
          "version": "0.7.9+35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-0.7.9+35-sources.jar",
          "url": "uno-0.7.9+35-sources.jar",
          "size": 261,
          "sha512": "62bfadce72fd815436a3c79c3adc0c4974aa4c3f29261e31d8c4d66a24a75b4bf035df555f61a59bc86fe7c77b5bab2cc15e1be7873c43f5f8e73bf0f9dbbaa0",
          "sha256": "eeb2b2f1354626449037f748ad01580faf734df4d156f6ba37fe6395fcf96971",
          "sha1": "719556d582a4384f071807635d4db57eb8e5fef7",
          "md5": "739c7b57dd305ace883ed282117b93de"
        }
      ]
    }
  ]
}
