{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+28.jar",
          "url": "11-0.7.0+28.jar",
          "size": 326106,
          "sha512": "2f7309bf2b34c7a969691188c90dfaa993227dad9192452a6416d0382382b84092968b576fb07e4fcbdc0c0b3e39168ae5e0015602c4bf38a68af19708cf6eab",
          "sha256": "43e75f98eae39fdc2788b12eabc41424079d415d085e1236e49ec7b077d79e94",
          "sha1": "e36b8ce523615b89c36ae384bec5794975972441",
          "md5": "1e988106b684c30fc65d4fbd2f582cb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+28"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+28"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+28.jar",
          "url": "11-0.7.0+28.jar",
          "size": 326106,
          "sha512": "2f7309bf2b34c7a969691188c90dfaa993227dad9192452a6416d0382382b84092968b576fb07e4fcbdc0c0b3e39168ae5e0015602c4bf38a68af19708cf6eab",
          "sha256": "43e75f98eae39fdc2788b12eabc41424079d415d085e1236e49ec7b077d79e94",
          "sha1": "e36b8ce523615b89c36ae384bec5794975972441",
          "md5": "1e988106b684c30fc65d4fbd2f582cb4"
        }
      ]
    }
  ]
}
