{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.2+25++25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+25.jar",
          "url": "gln-0.5.2+25.jar",
          "size": 985426,
          "sha512": "722bed915186b615e484af45086acf58a9b8ba026063aae830210276ea51c9ba06ec7e74e0aca38d5c5b10ce238de8e90aa0c9cafc8b9fa005c2445b144ddf7f",
          "sha256": "f91aa355c66c3ab8c61e8d2276ef0f8850e1cf9b9f96608b84b398817afa0230",
          "sha1": "df266b3a2238c500cc6622e8628412bd159efb03",
          "md5": "99a8d754936367eca97abb2bbee73743"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+25.jar",
          "url": "gln-0.5.2+25.jar",
          "size": 985426,
          "sha512": "722bed915186b615e484af45086acf58a9b8ba026063aae830210276ea51c9ba06ec7e74e0aca38d5c5b10ce238de8e90aa0c9cafc8b9fa005c2445b144ddf7f",
          "sha256": "f91aa355c66c3ab8c61e8d2276ef0f8850e1cf9b9f96608b84b398817afa0230",
          "sha1": "df266b3a2238c500cc6622e8628412bd159efb03",
          "md5": "99a8d754936367eca97abb2bbee73743"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+25-all.jar",
          "url": "gln-0.5.2+25-all.jar",
          "size": 12999472,
          "sha512": "0875bc7159297ab5a8f81d70babf8a54de1e0c871e2e10a3ee4b6c8b6a6fa28331f895c68845ef7c3786ade3e38d48704f2f29cca608721db231f12f47e492f1",
          "sha256": "a79d72d9c26f0f4fa28a716f57299d9e3d08e7cac802d2a8f8250a269196f057",
          "sha1": "8e9c18b71e437d75a8ace5b68e27fa2416bfc4c3",
          "md5": "01de9ae2dcc63967cf4367b40620ba32"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gln-0.5.2+25-jdk8.jar",
          "url": "gln-0.5.2+25-jdk8.jar",
          "size": 980386,
          "sha512": "481e47b1721cf7aa12fb7a6051b24b9414b1bae49c07ee1476e493656f80593f631e31935eb7ff2c60f546bf0d9f71a91f3d5c5bdf4f605ada28b40909d024fd",
          "sha256": "260719831f8970df734585bbe302a03ea89407e138da2839fc7ab1b7cf0f9ca6",
          "sha1": "c7ddc669df89acb113ba9b585051b792e86168f2",
          "md5": "7e92ff6c6241d1dc5ae2ae01646d243f"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.2+25"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+23"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+25-jdk8.jar",
          "url": "gln-0.5.2+25-jdk8.jar",
          "size": 980386,
          "sha512": "481e47b1721cf7aa12fb7a6051b24b9414b1bae49c07ee1476e493656f80593f631e31935eb7ff2c60f546bf0d9f71a91f3d5c5bdf4f605ada28b40909d024fd",
          "sha256": "260719831f8970df734585bbe302a03ea89407e138da2839fc7ab1b7cf0f9ca6",
          "sha1": "c7ddc669df89acb113ba9b585051b792e86168f2",
          "md5": "7e92ff6c6241d1dc5ae2ae01646d243f"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gln",
          "version": "0.5.2+25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+25-sources.jar",
          "url": "gln-0.5.2+25-sources.jar",
          "size": 263364,
          "sha512": "4054f0ffb67ab35c90c7d9c6f9dbbf0871e0e039c86569a7fa44d81b357b76f9d7e2e641d0a6f23bcc865ef131c88509a590a8bbe777e739dee922100918a245",
          "sha256": "24e8fa1b818c7ab1882f851bddffc210dd292111b7838f14723cba0ba6c8ed5f",
          "sha1": "ba6a0894da0137108ac4674f385cf8c5918f5d16",
          "md5": "c73f8f59ba858128eda59a8232908ddc"
        }
      ]
    }
  ]
}
