{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+81",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "tiuzhxc7zvgitlfslt6ot2yffu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+81.jar",
          "url": "11-0.7.0+81.jar",
          "size": 327343,
          "sha512": "58b819e0785d10161247bfb5db8fc24344fc79f11b1467e28e8143928ba4192632e47fe16eeb9420f2fa4141274d9c88d1cfc78838fd2f84aebf2068bd0c6ad3",
          "sha256": "6f4bfd41625d93adf22070d39c84ee1d6d2fd16f364c0bef5e48c0079b153d78",
          "sha1": "0a59a52247767731ccec9bcdc942856ce0ba0748",
          "md5": "c8e0b720790d0578a135719d799d568a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+81"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+81.jar",
          "url": "11-0.7.0+81.jar",
          "size": 327343,
          "sha512": "58b819e0785d10161247bfb5db8fc24344fc79f11b1467e28e8143928ba4192632e47fe16eeb9420f2fa4141274d9c88d1cfc78838fd2f84aebf2068bd0c6ad3",
          "sha256": "6f4bfd41625d93adf22070d39c84ee1d6d2fd16f364c0bef5e48c0079b153d78",
          "sha1": "0a59a52247767731ccec9bcdc942856ce0ba0748",
          "md5": "c8e0b720790d0578a135719d799d568a"
        }
      ]
    }
  ]
}
