{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-gl",
    "version": "1.89.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.7.jar",
          "url": "imgui-gl-1.89.7.jar",
          "size": 51627,
          "sha512": "a1ac74f22d474714a43ba20293157cf88f3359374455f6bbab34fadcd3e321732a1314380a4f028a43d2364a600dad07858f094c2d0419f6cfd2bd50a85c938e",
          "sha256": "397c1f7080dccc96fe66c17e0ead2836aa7ee18ca24a66f8569f18e24c1103e9",
          "sha1": "90ee46a67c62efd85335d6aaa991b4d939a9c745",
          "md5": "408174a1a34bc8ad32dfcba5d8869674"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.7"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-glfw",
          "version": {
            "requires": "1.89.7"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.7.jar",
          "url": "imgui-gl-1.89.7.jar",
          "size": 51627,
          "sha512": "a1ac74f22d474714a43ba20293157cf88f3359374455f6bbab34fadcd3e321732a1314380a4f028a43d2364a600dad07858f094c2d0419f6cfd2bd50a85c938e",
          "sha256": "397c1f7080dccc96fe66c17e0ead2836aa7ee18ca24a66f8569f18e24c1103e9",
          "sha1": "90ee46a67c62efd85335d6aaa991b4d939a9c745",
          "md5": "408174a1a34bc8ad32dfcba5d8869674"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.89.7-sources.jar",
          "url": "imgui-gl-1.89.7-sources.jar",
          "size": 15801,
          "sha512": "2ec14fb66fc5ed54a3f0e494256cfbc33aeb6c7578b3a9af5686883cecd1b18815eb6c04078ada721e56497c43e6b7c705d6ed58519efc50e63146f428c9d3de",
          "sha256": "422170815f3e1982899692c96fc5d11b471933565be0bf2abc62d2ef1d332991",
          "sha1": "804e25911a558ac20db4ba8a8b521d685c65389a",
          "md5": "ee9d0b33abcb66b1992d1138dbaea83c"
        }
      ]
    }
  ]
}
