{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.5.jar",
          "url": "kool-0.9.5.jar",
          "size": 264152,
          "sha512": "b4cb0e26e03831113c648bbddb398e05eead5a526727969bb72803d5eca44ce87f884b88c0ef6c8088c76de866527acc3ce37d35c1d294f321cac3115cb4ca9b",
          "sha256": "3e43783091b09bbe94636e04b9f28889b6361e096cc8cc7b2df9bd88c576d771",
          "sha1": "85d25a9a52fa317de5f7f122cac5dfeb989a4839",
          "md5": "167cf3c7ff4f36fc04709ac12f583eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-runner-junit5",
          "version": {
            "requires": "5.5.2"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.5.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.5.jar",
          "url": "kool-0.9.5.jar",
          "size": 264152,
          "sha512": "b4cb0e26e03831113c648bbddb398e05eead5a526727969bb72803d5eca44ce87f884b88c0ef6c8088c76de866527acc3ce37d35c1d294f321cac3115cb4ca9b",
          "sha256": "3e43783091b09bbe94636e04b9f28889b6361e096cc8cc7b2df9bd88c576d771",
          "sha1": "85d25a9a52fa317de5f7f122cac5dfeb989a4839",
          "md5": "167cf3c7ff4f36fc04709ac12f583eb5"
        }
      ]
    }
  ]
}
