{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "v0.7.0-17-a48819c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-v0.7.0-17-a48819c.jar",
          "url": "commons-v0.7.0-17-a48819c.jar",
          "size": 325144,
          "sha512": "1c6740c3a244e9fddb7a37e25dee6fba35b76ba95e76ecd32a5d645d8d6dd20cadc76dcf4c18d908ee9f3698b48f57931ca9ae66ac2e94d6139acf3c589d18cf",
          "sha256": "ca1108f9d766c55e4a1cf0798fa837cc72fe12007307b6c38099635cb709a29a",
          "sha1": "e03030778d8458efd60825d9aab950b3137aa283",
          "md5": "0f584b595fa4dd6db0db390834c12288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-17-a48819c"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "v0.7.0-17-a48819c"
          }
        }
      ],
      "files": [
        {
          "name": "commons-v0.7.0-17-a48819c.jar",
          "url": "commons-v0.7.0-17-a48819c.jar",
          "size": 325144,
          "sha512": "1c6740c3a244e9fddb7a37e25dee6fba35b76ba95e76ecd32a5d645d8d6dd20cadc76dcf4c18d908ee9f3698b48f57931ca9ae66ac2e94d6139acf3c589d18cf",
          "sha256": "ca1108f9d766c55e4a1cf0798fa837cc72fe12007307b6c38099635cb709a29a",
          "sha1": "e03030778d8458efd60825d9aab950b3137aa283",
          "md5": "0f584b595fa4dd6db0db390834c12288"
        }
      ]
    }
  ]
}
