{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+25.jar",
          "url": "docs-0.7.0+25.jar",
          "size": 234506,
          "sha512": "2316b505bbfd4ebd1d4393a1691f35ff9afecb2e8879fd76e76a298a57b6541b677aaaa896a996c6ca67b670aeb6e91b2364f12c409d0e21ad97b295f8176bba",
          "sha256": "64844cefdc273b0c7d7ad3a167f4c71ae7f6a95fb7dfbfc07338f8b74aabe86f",
          "sha1": "90a4a0963833ed4e030e5e9bc85f58bc73a426c2",
          "md5": "3a11ef309797ccc782fceaba14b9d5ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+25.jar",
          "url": "docs-0.7.0+25.jar",
          "size": 234506,
          "sha512": "2316b505bbfd4ebd1d4393a1691f35ff9afecb2e8879fd76e76a298a57b6541b677aaaa896a996c6ca67b670aeb6e91b2364f12c409d0e21ad97b295f8176bba",
          "sha256": "64844cefdc273b0c7d7ad3a167f4c71ae7f6a95fb7dfbfc07338f8b74aabe86f",
          "sha1": "90a4a0963833ed4e030e5e9bc85f58bc73a426c2",
          "md5": "3a11ef309797ccc782fceaba14b9d5ff"
        }
      ]
    }
  ]
}
