{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-glfw",
    "version": "1.89.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.6.jar",
          "url": "imgui-glfw-1.89.6.jar",
          "size": 42944,
          "sha512": "1e3b64340aec8b82250bee49e342f3b58f3c188d0d2aaa0478d60031bbc9bd24e547f3f582624a78c01c1e3f8060f5f81248ed7e2237456ae859391839669f19",
          "sha256": "acbd75bf6f30e0574bc381cb7e682f5213f2215e9a52853ee2f4fd042cfd705a",
          "sha1": "41c69790693be45da62789c40e615dd5b34d60cf",
          "md5": "636542e4f436b77dd433c38742048cc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.6"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.6.jar",
          "url": "imgui-glfw-1.89.6.jar",
          "size": 42944,
          "sha512": "1e3b64340aec8b82250bee49e342f3b58f3c188d0d2aaa0478d60031bbc9bd24e547f3f582624a78c01c1e3f8060f5f81248ed7e2237456ae859391839669f19",
          "sha256": "acbd75bf6f30e0574bc381cb7e682f5213f2215e9a52853ee2f4fd042cfd705a",
          "sha1": "41c69790693be45da62789c40e615dd5b34d60cf",
          "md5": "636542e4f436b77dd433c38742048cc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-glfw-1.89.6-sources.jar",
          "url": "imgui-glfw-1.89.6-sources.jar",
          "size": 8719,
          "sha512": "5a5b155b64879fe4a9159e0033bed24f3769022948d22f8763a55cfde742c7be94930cefb27a25d493e600b2bca0fdfb2870baa2bc8cab37e257c4fbf261b708",
          "sha256": "033d06b3df85f1a97bd3a2f8a2f4a4ffc19ff8f1144f7173128acf71775e895f",
          "sha1": "41f8cb3d20bc762ae1aeb7df1379f825b53538ef",
          "md5": "019b7951e67b2838a1cda24ff7edfef7"
        }
      ]
    }
  ]
}
