{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "e62sehrv6ncbhie77xjqtphojy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+76.jar",
          "url": "11-0.7.0+76.jar",
          "size": 327343,
          "sha512": "7c864c12e6dfbedc1b9bb675cf4f18320d5c740eda8519a9cfb06cdc00e1000175b7747e74c9c7ad516bd68b05c06611afa51d7d24ae1a39fbeed450f36c2a8f",
          "sha256": "e84375123570d9982a3eba7a744a4b6b029b3a7eae98035f00fcda468c137c91",
          "sha1": "d8ef6c10df8c7592c3a5fb4243157623eafe5cd5",
          "md5": "9f150449228ace044d444d1296a567f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+76"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+76.jar",
          "url": "11-0.7.0+76.jar",
          "size": 327343,
          "sha512": "7c864c12e6dfbedc1b9bb675cf4f18320d5c740eda8519a9cfb06cdc00e1000175b7747e74c9c7ad516bd68b05c06611afa51d7d24ae1a39fbeed450f36c2a8f",
          "sha256": "e84375123570d9982a3eba7a744a4b6b029b3a7eae98035f00fcda468c137c91",
          "sha1": "d8ef6c10df8c7592c3a5fb4243157623eafe5cd5",
          "md5": "9f150449228ace044d444d1296a567f8"
        }
      ]
    }
  ]
}
