{
  "formatVersion": "1.1",
  "component": {
    "url": "../../unsigned/3.4.0/unsigned-3.4.0.module",
    "group": "kotlin.graphics",
    "module": "unsigned",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "unsigned.klib",
          "url": "unsigned-native-3.4.0.klib",
          "size": 247739,
          "sha512": "510140b5d36aa1a6777158daa12eb0432606469cb0d4c46bd2e0133bb3ac6a5f50d0440a2f64dc6f7e732fb46c5c49718e50814dcd18add0098f05e1be5f48b5",
          "sha256": "330e0ed9185fb46f8747ea7f4364209d2e6162a7ba07935add742fd77715ec23",
          "sha1": "3848b6732d70543e9ca0141d36bcc3cbc6dc3068",
          "md5": "9988fb441d49960b54bb5db0ea3a2836"
        }
      ]
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "unsigned-native-3.4.0-sources.jar",
          "url": "unsigned-native-3.4.0-sources.jar",
          "size": 33938,
          "sha512": "64083d53fa58c0e3e7f48fa592513434aaf36b13127f4064dce0587da1e072229467e3524f7957518128d940999d09472aadde806f2ce31ef3cbb9121c9d689e",
          "sha256": "8a1599d3305fea71dd67f5dc228d44e92a0eef177d882fefec5fd369b36bade9",
          "sha1": "9117d92e7918a85e2b46f3ff629102d42acc5eca",
          "md5": "893caa00af4f23fe3bc13b8ce64476f2"
        }
      ]
    }
  ]
}
