{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-gl",
    "version": "0.7.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.21.jar",
          "url": "uno-gl-0.7.21.jar",
          "size": 3446,
          "sha512": "c2a734d142d67ec41e0fd63e76dc571284094a4161ac0edac7eade673e4c08596b56d575fe12e53bfd238ada16617c4cee609021559fdfde9101fdda422ca2e6",
          "sha256": "531661e3ae05e838ec782432eb52e633dd2250ecd13eacd5c3bacce6d676c1ac",
          "sha1": "946cf60df80b257fe56c36fdf56b91eab7280d77",
          "md5": "1e508459ab51bf3a34c09fd6582b0dd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "uno-gl-0.7.21.jar",
          "url": "uno-gl-0.7.21.jar",
          "size": 3446,
          "sha512": "c2a734d142d67ec41e0fd63e76dc571284094a4161ac0edac7eade673e4c08596b56d575fe12e53bfd238ada16617c4cee609021559fdfde9101fdda422ca2e6",
          "sha256": "531661e3ae05e838ec782432eb52e633dd2250ecd13eacd5c3bacce6d676c1ac",
          "sha1": "946cf60df80b257fe56c36fdf56b91eab7280d77",
          "md5": "1e508459ab51bf3a34c09fd6582b0dd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-gl-0.7.21-sources.jar",
          "url": "uno-gl-0.7.21-sources.jar",
          "size": 1565,
          "sha512": "4e6785ac162fb29e6bcbc7de7fa6b8a50698f6d5535d9ff314dc688fb5b667fed2874fa7e4ee60cbdfa170dbeccf2e4a28fb7ec04b037df1304a2d48a4717c2d",
          "sha256": "88244b0b3638d687a4dd5147f765e1ff5937854358f39f655e95d292138a809b",
          "sha1": "3229d6a5f91254d4e878f7601d918d7b6ad356d5",
          "md5": "2d6a9dc1ee94087bc44e69cf66722960"
        }
      ]
    }
  ]
}
