{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "vkk",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.3.jar",
          "url": "vkk-0.3.3.jar",
          "size": 1540953,
          "sha512": "a4237e925b4a26fb50e3d191a5dee068905c5544b4ba52fb1d8117996eaea93469e04a035d13f39312bd14d303b1bfe7ae7b60e63d294fa81ca0e5884e071023",
          "sha256": "f9532f68d0ee04d12cd8ac376c8b14761f0c90aa87d6b93d208475b3b4bd49d9",
          "sha1": "45d38ec07df92895f201cd14b6e20949a40b3b14",
          "md5": "5e0b5fe49b312f7f8d0fb1106d641048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "spirvcrossj",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.3.jar",
          "url": "vkk-0.3.3.jar",
          "size": 1540953,
          "sha512": "a4237e925b4a26fb50e3d191a5dee068905c5544b4ba52fb1d8117996eaea93469e04a035d13f39312bd14d303b1bfe7ae7b60e63d294fa81ca0e5884e071023",
          "sha256": "f9532f68d0ee04d12cd8ac376c8b14761f0c90aa87d6b93d208475b3b4bd49d9",
          "sha1": "45d38ec07df92895f201cd14b6e20949a40b3b14",
          "md5": "5e0b5fe49b312f7f8d0fb1106d641048"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vkk-0.3.3-jdk8.jar",
          "url": "vkk-0.3.3-jdk8.jar",
          "size": 1534723,
          "sha512": "09dc2fbe0f5b8af80eaf55b7e05a364f91f44d9c232830616abd92a8df42a582327149a445c8bbdf3924a669d93b24d57ddad0d36e2c8788c673dd226224e249",
          "sha256": "4b521e52439909d1f512461e95c3dfd4ab57f0a678dfd0c2c9e9ad748590a504",
          "sha1": "44f13063c197fb01253e090913d02e3612c16683",
          "md5": "63e0feb4c328a5bd736925fc72930be5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vkk",
          "version": "0.3.3"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-4"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-17"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.3-jdk8.jar",
          "url": "vkk-0.3.3-jdk8.jar",
          "size": 1534723,
          "sha512": "09dc2fbe0f5b8af80eaf55b7e05a364f91f44d9c232830616abd92a8df42a582327149a445c8bbdf3924a669d93b24d57ddad0d36e2c8788c673dd226224e249",
          "sha256": "4b521e52439909d1f512461e95c3dfd4ab57f0a678dfd0c2c9e9ad748590a504",
          "sha1": "44f13063c197fb01253e090913d02e3612c16683",
          "md5": "63e0feb4c328a5bd736925fc72930be5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vkk",
          "version": "0.3.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vkk-0.3.3-sources.jar",
          "url": "vkk-0.3.3-sources.jar",
          "size": 450417,
          "sha512": "2781c553f6d1fdb981436da7dd56833977695ed1ba481514850cb7fd1b6183feb01eb624e8a1c9577571556f65f322e9fb3d357821a4c24354fc207ee4793397",
          "sha256": "5d7965c2ac3300bab085e2286f4db7017c405e4d6a663b9517a8d355008939a3",
          "sha1": "5720d4a467026ff5da012d1e35fda213279d56f6",
          "md5": "a462b606b09ca90310e160f4ed203606"
        }
      ]
    }
  ]
}
