{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+83",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qysdlozpkbhnpgeevjjy63obhy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+83.jar",
          "url": "docs-0.7.0+83.jar",
          "size": 311941,
          "sha512": "2141700fcabb0b4c262b1a252c31bb8b6a5b2fab77162be8fee7738dfccdd65858faf40ce6cacd02279f096b5b08ec6d5454489f3a07625a9a23872bba73a9ff",
          "sha256": "ee90c92f0d1a5b91647c074edf3c57fda06dc698249eac94d93f772c7eacee14",
          "sha1": "560e396ca708672f015ab5e967bdfb9ea8efa63b",
          "md5": "71c8c180320480e2bc3009e7a6b94e9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+83.jar",
          "url": "docs-0.7.0+83.jar",
          "size": 311941,
          "sha512": "2141700fcabb0b4c262b1a252c31bb8b6a5b2fab77162be8fee7738dfccdd65858faf40ce6cacd02279f096b5b08ec6d5454489f3a07625a9a23872bba73a9ff",
          "sha256": "ee90c92f0d1a5b91647c074edf3c57fda06dc698249eac94d93f772c7eacee14",
          "sha1": "560e396ca708672f015ab5e967bdfb9ea8efa63b",
          "md5": "71c8c180320480e2bc3009e7a6b94e9c"
        }
      ]
    }
  ]
}
