{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+40.jar",
          "url": "8-0.7.0+40.jar",
          "size": 323602,
          "sha512": "89dc2fb0a953499b8af47b62dd61a556c397a743b894e8dda130cdee207c8653bda2688a9d59c0b0ecf2fe61872b02a6308891721331b43b3eb8f42435c7c338",
          "sha256": "1767a6e0743a6b45ba2ad80824d3276cd225e35bd5407f788e1160fccc9369b8",
          "sha1": "237a48e12ea4b28e2a739cee2c97430ef231dae5",
          "md5": "127bd8003f8260206e009d2662ceef83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+40"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+40"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+40.jar",
          "url": "8-0.7.0+40.jar",
          "size": 323602,
          "sha512": "89dc2fb0a953499b8af47b62dd61a556c397a743b894e8dda130cdee207c8653bda2688a9d59c0b0ecf2fe61872b02a6308891721331b43b3eb8f42435c7c338",
          "sha256": "1767a6e0743a6b45ba2ad80824d3276cd225e35bd5407f788e1160fccc9369b8",
          "sha1": "237a48e12ea4b28e2a739cee2c97430ef231dae5",
          "md5": "127bd8003f8260206e009d2662ceef83"
        }
      ]
    }
  ]
}
