{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "uno-core",
    "version": "0.7.9+41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-core-0.7.9+41.jar",
          "url": "uno-core-0.7.9+41.jar",
          "size": 140805,
          "sha512": "a0be4fc2bde33d415e78d1b000733bd8e1f0cd5829c2481f0582c4a6db12b510c21e00c0aba50092b0e0555716807ee8a3208d04adc37bd2e739de9583c3848a",
          "sha256": "c030cec647ede63840c02cc7df4ddea1d81098ba64a318db6e8dbb0905f4c27f",
          "sha1": "ffdba1f4e858e7d9ab6bf6a1c07339e3b2f50613",
          "md5": "bbac9969285c9432e9567ca1ff862cc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-core-0.7.9+41.jar",
          "url": "uno-core-0.7.9+41.jar",
          "size": 140805,
          "sha512": "a0be4fc2bde33d415e78d1b000733bd8e1f0cd5829c2481f0582c4a6db12b510c21e00c0aba50092b0e0555716807ee8a3208d04adc37bd2e739de9583c3848a",
          "sha256": "c030cec647ede63840c02cc7df4ddea1d81098ba64a318db6e8dbb0905f4c27f",
          "sha1": "ffdba1f4e858e7d9ab6bf6a1c07339e3b2f50613",
          "md5": "bbac9969285c9432e9567ca1ff862cc4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-core-0.7.9+41-all.jar",
          "url": "uno-core-0.7.9+41-all.jar",
          "size": 13140016,
          "sha512": "608f93eabd77b5cef46f5f817bbd2daab80041e651065e897e7b61c18e0b645705d2742b6eaf5fa3eca5d6dc7e1b0aeb9dbf6198f491420e2059d3f45ac60899",
          "sha256": "7c94ac5d6f8441f1dff29eb7f788ffb4919d0f60f85d4dcc03316454e18dcb68",
          "sha1": "f2a1f6ea2b688c0674a57fbcdbd80f3eb604a085",
          "md5": "3d926c2639afdf981cfdfdc24586bd56"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uno-core-0.7.9+41-jdk8.jar",
          "url": "uno-core-0.7.9+41-jdk8.jar",
          "size": 140711,
          "sha512": "360e50c96578fb44a992b52c13aac42a4984f0ffdec4b4d03f33f5bb2d074a2456a98ec53377242c59d1bf3c6ce6a4beb6fdba512b5494eb220cef0447fb5471",
          "sha256": "1073417bffe9d2aea9c204a30a9007a178ea0f97f55b1412808fce1ec89ce815",
          "sha1": "2c4d1b95336bc2968f60dd3c4fcf64f8f2c29003",
          "md5": "3aeca0b4713b4cb62563720069fa35b4"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+41"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+40"
          }
        }
      ],
      "files": [
        {
          "name": "uno-core-0.7.9+41-jdk8.jar",
          "url": "uno-core-0.7.9+41-jdk8.jar",
          "size": 140711,
          "sha512": "360e50c96578fb44a992b52c13aac42a4984f0ffdec4b4d03f33f5bb2d074a2456a98ec53377242c59d1bf3c6ce6a4beb6fdba512b5494eb220cef0447fb5471",
          "sha256": "1073417bffe9d2aea9c204a30a9007a178ea0f97f55b1412808fce1ec89ce815",
          "sha1": "2c4d1b95336bc2968f60dd3c4fcf64f8f2c29003",
          "md5": "3aeca0b4713b4cb62563720069fa35b4"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uno-core-0.7.9+41-sources.jar",
          "url": "uno-core-0.7.9+41-sources.jar",
          "size": 37180,
          "sha512": "ec95b8e687ba3a8929ae97ace05f6f8ac58c23a135148fe64b5f9671c9e043ec9204846fd70c04ee38bff85625bde465f5d7d91f1f55b05b20a0710c69997ed5",
          "sha256": "85bd8a8d43a0923ff2c2d677d8d5df8f24bc68a4aa734b5ca742a2b8163452c4",
          "sha1": "ff5e6c2fa0d0b7e22d17793bdc175fc940431854",
          "md5": "0ef3573177518254792a893394665e33"
        }
      ]
    }
  ]
}
