{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "v0.7.0-4-4441c52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-v0.7.0-4-4441c52.jar",
          "url": "docs-v0.7.0-4-4441c52.jar",
          "size": 234506,
          "sha512": "9144401bf2833a6bb35fcdbfff8be340be35d4c8da1ed2e411cf1dbebb14ab94906746150ab3d79bb3e4237eac7c524ad3e1ee10097d0e8d059d38ab3034cf49",
          "sha256": "ed40190b3b1f0c50eb4cc65f473b6411eb133c75a85478cdedfe7ececd7f6e91",
          "sha1": "35414deb021267fe7322e43b704b6f0aca0513c8",
          "md5": "c281c029e7b72198b9e9ce4f48eba953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-4-4441c52"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-v0.7.0-4-4441c52.jar",
          "url": "docs-v0.7.0-4-4441c52.jar",
          "size": 234506,
          "sha512": "9144401bf2833a6bb35fcdbfff8be340be35d4c8da1ed2e411cf1dbebb14ab94906746150ab3d79bb3e4237eac7c524ad3e1ee10097d0e8d059d38ab3034cf49",
          "sha256": "ed40190b3b1f0c50eb4cc65f473b6411eb133c75a85478cdedfe7ececd7f6e91",
          "sha1": "35414deb021267fe7322e43b704b6f0aca0513c8",
          "md5": "c281c029e7b72198b9e9ce4f48eba953"
        }
      ]
    }
  ]
}
