{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+48.jar",
          "url": "8-0.7.0+48.jar",
          "size": 323596,
          "sha512": "c0c1e86f99eae96ec1538c8e9642ed59953cfa6160db1cfd7d2f1ebfb06777e2a0c64b7b547d4b4885ee8034265fe161bb5ddc9a7b3dad59d6c1270897b03577",
          "sha256": "c5b02c6ee80859db686a2c0b5489c7416a9869a831c547e57619b2d3e2a0108e",
          "sha1": "d1e1fc2b4b89989a5565f8a125712511c8879fae",
          "md5": "c19c447bded637d0f40aecc91c770e4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+48"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+48.jar",
          "url": "8-0.7.0+48.jar",
          "size": 323596,
          "sha512": "c0c1e86f99eae96ec1538c8e9642ed59953cfa6160db1cfd7d2f1ebfb06777e2a0c64b7b547d4b4885ee8034265fe161bb5ddc9a7b3dad59d6c1270897b03577",
          "sha256": "c5b02c6ee80859db686a2c0b5489c7416a9869a831c547e57619b2d3e2a0108e",
          "sha1": "d1e1fc2b4b89989a5565f8a125712511c8879fae",
          "md5": "c19c447bded637d0f40aecc91c770e4f"
        }
      ]
    }
  ]
}
