{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vaamy6pnvjchlkckua4mzm73tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+92.jar",
          "url": "commons-0.7.0+92.jar",
          "size": 355750,
          "sha512": "5b22242b698a6cc84926fe82403669d8a9ebd1cf45b5e338e4f0d148ee3b807ee2c51658d4e26ac1041faa7da5b9137dbab342e4360aa5aed197c5886855d8e4",
          "sha256": "9376e4f819eaffac535efaaa7ebba781a9a686c10c8ffaa974c2ea470e6e8459",
          "sha1": "648bb5261113226f71f2b1f390aece2628a13ec2",
          "md5": "202fb8f2ba5f8de203033207017ef6f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+92"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "dev",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+92.jar",
          "url": "commons-0.7.0+92.jar",
          "size": 355750,
          "sha512": "5b22242b698a6cc84926fe82403669d8a9ebd1cf45b5e338e4f0d148ee3b807ee2c51658d4e26ac1041faa7da5b9137dbab342e4360aa5aed197c5886855d8e4",
          "sha256": "9376e4f819eaffac535efaaa7ebba781a9a686c10c8ffaa974c2ea470e6e8459",
          "sha1": "648bb5261113226f71f2b1f390aece2628a13ec2",
          "md5": "202fb8f2ba5f8de203033207017ef6f6"
        }
      ]
    }
  ]
}
