{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-core",
    "version": "1.89.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-core-1.89.2.jar",
          "url": "imgui-core-1.89.2.jar",
          "size": 18614734,
          "sha512": "b911ad528f183cfa2d7eed4de646da1a8e0351d91f2deee9e5fdb738e1b89bb1ad4b69a3b91feb4074889d4b2ea8f5c0b188763f6bbbcc124dcb746f485aa98c",
          "sha256": "9c5e334e8372858ab323ff4c7e5c9644017246619ce0fcf3fc2c659e1627a397",
          "sha1": "2cfae0824603b00aea5a32fc7b2ee20b6e5c3d58",
          "md5": "f6e7ea8ecc3856be4c00f0638345864a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.github.livefront.sealed-enum",
          "module": "runtime",
          "version": {
            "requires": "f690fca874"
          }
        },
        {
          "group": "com.aayushatharva.brotli4j",
          "module": "brotli4j",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "com.aayushatharva.brotli4j",
          "module": "native-linux-x86_64",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-core-1.89.2.jar",
          "url": "imgui-core-1.89.2.jar",
          "size": 18614734,
          "sha512": "b911ad528f183cfa2d7eed4de646da1a8e0351d91f2deee9e5fdb738e1b89bb1ad4b69a3b91feb4074889d4b2ea8f5c0b188763f6bbbcc124dcb746f485aa98c",
          "sha256": "9c5e334e8372858ab323ff4c7e5c9644017246619ce0fcf3fc2c659e1627a397",
          "sha1": "2cfae0824603b00aea5a32fc7b2ee20b6e5c3d58",
          "md5": "f6e7ea8ecc3856be4c00f0638345864a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-core-1.89.2-sources.jar",
          "url": "imgui-core-1.89.2-sources.jar",
          "size": 16141947,
          "sha512": "479ea2d8d836b35875931a77de68f3c60537f46156efef00801cb2545aee23b980b8a56be9d30bf3878824ec36b699de9a97ddc9d299ca3980168a9f16c5c42f",
          "sha256": "a223118ae89fa92c8b1d0a73c7160d6a0b1a38687f327974381caae9c94ce87a",
          "sha1": "81ca64e2c5ddd8e8abf72edbb0084d062ead2a0b",
          "md5": "df33bc524f804d18982b59ad1d99f33f"
        }
      ]
    }
  ]
}
