{
  "formatVersion": "1.1",
  "component": {
    "group": "sciJava.catalogs",
    "module": "sciJava-catalogs",
    "version": "30.0.0+66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sciJava-catalogs-30.0.0+66.jar",
          "url": "sciJava-catalogs-30.0.0+66.jar",
          "size": 28238,
          "sha512": "548ea010e75454b18da99ad6b6afe908503b3ad86370b41386f67f7e6c5e5bc66ce368bed5ca659a9af16d6d2b1e462c91bc874f22fe95a915ef3145e9c45c75",
          "sha256": "72fdffc401812f7fc3d4908eb7cf924ce81713f7aae2c61f7e5c519fdc7c2abb",
          "sha1": "0467ee0842eb8918a15fcd6ac7f6934b7d97e7c1",
          "md5": "b37b9447ca2f92b1c53a120ea2810324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.4.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "sciJava-catalogs-30.0.0+66.jar",
          "url": "sciJava-catalogs-30.0.0+66.jar",
          "size": 28238,
          "sha512": "548ea010e75454b18da99ad6b6afe908503b3ad86370b41386f67f7e6c5e5bc66ce368bed5ca659a9af16d6d2b1e462c91bc874f22fe95a915ef3145e9c45c75",
          "sha256": "72fdffc401812f7fc3d4908eb7cf924ce81713f7aae2c61f7e5c519fdc7c2abb",
          "sha1": "0467ee0842eb8918a15fcd6ac7f6934b7d97e7c1",
          "md5": "b37b9447ca2f92b1c53a120ea2810324"
        }
      ]
    }
  ]
}
