{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "awt",
    "version": "0.7.9+40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "awt-0.7.9+40.jar",
          "url": "awt-0.7.9+40.jar",
          "size": 18793,
          "sha512": "bdbd0d5936f24cb2541125ff011701f9a29776e1686013bd6eaf8d49653043aab73db7bf8954a508dbee1adbba8db02f17647dbbd4543af7483f3bb559324b9c",
          "sha256": "4561e185138169ea91d4987f9b585ab70dff7c186742b4f754125ab81a4beb9b",
          "sha1": "f210a1150776fad1c6cc0384fb1d834a8018e5c9",
          "md5": "e7785761d9941b335173d24cc5789fb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "awt-0.7.9+40.jar",
          "url": "awt-0.7.9+40.jar",
          "size": 18793,
          "sha512": "bdbd0d5936f24cb2541125ff011701f9a29776e1686013bd6eaf8d49653043aab73db7bf8954a508dbee1adbba8db02f17647dbbd4543af7483f3bb559324b9c",
          "sha256": "4561e185138169ea91d4987f9b585ab70dff7c186742b4f754125ab81a4beb9b",
          "sha1": "f210a1150776fad1c6cc0384fb1d834a8018e5c9",
          "md5": "e7785761d9941b335173d24cc5789fb4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "awt-0.7.9+40-all.jar",
          "url": "awt-0.7.9+40-all.jar",
          "size": 13180706,
          "sha512": "837d29af8ed7bc8fe025c9c8e336bea35de34b1b94ac5f7dc32f90124ae291894292d2ea1c1aebfd34054992ff0089a7ea85a26e68f5d5567b39581b9e503cdf",
          "sha256": "aa187e4a93ac10a2dc56d2f27d8d9ca7799b5d48dd7d7c1dba65b5afd2795ed0",
          "sha1": "0b6e182e42bf0c5c0c4abf7e4de58c1e130dfdd6",
          "md5": "b48ef25c68e70692b28e9c5b0bb789f2"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "awt-0.7.9+40-jdk8.jar",
          "url": "awt-0.7.9+40-jdk8.jar",
          "size": 18700,
          "sha512": "1309d629fb2f0ff74ab78b76fc7d06a8ad2ba4fe5ceccbfed79ea71cfce3b90e3dbc13dca3e1df523f1d3f8ac51b265a45f8a229b6335244e0240cab57521342",
          "sha256": "7bfa3d7184c9b88d7ccfb10c4dee9e3d275a37f03c0a5f9ce219f5cf72660101",
          "sha1": "06836068fe661ebe408f11d59ecb17c7e6430d8c",
          "md5": "77aa0f67a013bb15e0fef209dca5e774"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+40"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+40"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jawt"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "awt-0.7.9+40-jdk8.jar",
          "url": "awt-0.7.9+40-jdk8.jar",
          "size": 18700,
          "sha512": "1309d629fb2f0ff74ab78b76fc7d06a8ad2ba4fe5ceccbfed79ea71cfce3b90e3dbc13dca3e1df523f1d3f8ac51b265a45f8a229b6335244e0240cab57521342",
          "sha256": "7bfa3d7184c9b88d7ccfb10c4dee9e3d275a37f03c0a5f9ce219f5cf72660101",
          "sha1": "06836068fe661ebe408f11d59ecb17c7e6430d8c",
          "md5": "77aa0f67a013bb15e0fef209dca5e774"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "awt",
          "version": "0.7.9+40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "awt-0.7.9+40-sources.jar",
          "url": "awt-0.7.9+40-sources.jar",
          "size": 3970,
          "sha512": "f7fbde7576fd056149a2def4faa869733e27aeacd08e1ff405c06f3831a167b274a723abada8e3dbc422979b5c1209926e2bc5c253faede21086651898583a95",
          "sha256": "6ad5c0feb009afc5879c0a12c1323f786354a33cccbbc9c2e165cc9f6098be59",
          "sha1": "e7e1c7d467a6f22fc746cc474425cf6292240296",
          "md5": "1835608ae589b7fd2365d6e3481572f8"
        }
      ]
    }
  ]
}
