{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "vk",
    "version": "0.7.9+39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+39.jar",
          "url": "vk-0.7.9+39.jar",
          "size": 3710,
          "sha512": "fb95e0d1f34b4839bcfc1883e5fef64c89431fa9186ed0c5e77c1a676e624c5ea6e117328c54cfd6f56ef36cedfa4883faff1be54b9f167ae0e4cc14f036fa67",
          "sha256": "e23f430d9d6615603a118d5d51717ee606c6b880523a3b026b1973baa1cd9c09",
          "sha1": "da42f80751e5a9813d8e343d887a142d6df67d1f",
          "md5": "9d8bcacfd7d25a7e48ae666f94ac1018"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+39"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+39.jar",
          "url": "vk-0.7.9+39.jar",
          "size": 3710,
          "sha512": "fb95e0d1f34b4839bcfc1883e5fef64c89431fa9186ed0c5e77c1a676e624c5ea6e117328c54cfd6f56ef36cedfa4883faff1be54b9f167ae0e4cc14f036fa67",
          "sha256": "e23f430d9d6615603a118d5d51717ee606c6b880523a3b026b1973baa1cd9c09",
          "sha1": "da42f80751e5a9813d8e343d887a142d6df67d1f",
          "md5": "9d8bcacfd7d25a7e48ae666f94ac1018"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vk-0.7.9+39-all.jar",
          "url": "vk-0.7.9+39-all.jar",
          "size": 63552754,
          "sha512": "27217f1f3ce78929907b7e77ba0c1457b7fce06829bdf982faeb149d042e0e3e52185550ee865a2e30a365168cb2a5ebda45d24c396fc3226cfcbe0ab84edcda",
          "sha256": "1498f606e29976ea561b5cfbfddc7a28c9dd5c5800eec4fb8f61ccbd6f5eae0b",
          "sha1": "18959cb126ae50b33b7c0a445a43372367aaddbf",
          "md5": "3eb40cd6d7d0159f5f4ba8a1611ff8b0"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vk-0.7.9+39-jdk8.jar",
          "url": "vk-0.7.9+39-jdk8.jar",
          "size": 3725,
          "sha512": "2c120b18e5363a3a769764d89d5ee72a36940b746d637aca583fb010817eae2343a485683da65ae597e4e21ed0be9855dc278539aaf2c51c571e3aa00905be44",
          "sha256": "3f120ad3a3f0fb39e6b6d8cf831f97c0286eb6d8be62886cb621d11ba293709a",
          "sha1": "eb80534d077d80d2de13ec014a89f5773a35da1d",
          "md5": "906f7996a1499ef07381e052d2378546"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.9+39"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "core",
          "version": {
            "requires": "0.7.9+39"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "vk-0.7.9+39-jdk8.jar",
          "url": "vk-0.7.9+39-jdk8.jar",
          "size": 3725,
          "sha512": "2c120b18e5363a3a769764d89d5ee72a36940b746d637aca583fb010817eae2343a485683da65ae597e4e21ed0be9855dc278539aaf2c51c571e3aa00905be44",
          "sha256": "3f120ad3a3f0fb39e6b6d8cf831f97c0286eb6d8be62886cb621d11ba293709a",
          "sha1": "eb80534d077d80d2de13ec014a89f5773a35da1d",
          "md5": "906f7996a1499ef07381e052d2378546"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vk",
          "version": "0.7.9+39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vk-0.7.9+39-sources.jar",
          "url": "vk-0.7.9+39-sources.jar",
          "size": 1268,
          "sha512": "0f4c689a536bcec874b945ad5e00fa618180bbea216644c83ba32739ffd71b4697eb2acb96036b69376e15d4b45655e1799dc62c58474c474814a6b2892bcd46",
          "sha256": "b19ed3f95c1a79c20ecc6e6d3464af125b443557c555432344dffcd39b6f9305",
          "sha1": "17977edfe6cdd8794824000b5114dadbde288eed",
          "md5": "29e54bdbc123b8890eec6aef474e4366"
        }
      ]
    }
  ]
}
