{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+36.jar",
          "url": "11-0.7.0+36.jar",
          "size": 326126,
          "sha512": "a46296bd490f8691f42933377a1b40ec337b8a5975173d4363ec261d545b09b6a4c775668b73a58f91eb2779e70f8467f324f5c012feccebfb460f06bb689e10",
          "sha256": "92dd6418e0211ed425ce3cce87f71c4f6abf25f616e3d15479d2f50d8c97998c",
          "sha1": "9b2cce57d5b501819840d56bb6ed4f357b4d3651",
          "md5": "608cbccb12db6b4c2c14a55cf40f89ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+36"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+36"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+36.jar",
          "url": "11-0.7.0+36.jar",
          "size": 326126,
          "sha512": "a46296bd490f8691f42933377a1b40ec337b8a5975173d4363ec261d545b09b6a4c775668b73a58f91eb2779e70f8467f324f5c012feccebfb460f06bb689e10",
          "sha256": "92dd6418e0211ed425ce3cce87f71c4f6abf25f616e3d15479d2f50d8c97998c",
          "sha1": "9b2cce57d5b501819840d56bb6ed4f357b4d3651",
          "md5": "608cbccb12db6b4c2c14a55cf40f89ff"
        }
      ]
    }
  ]
}
