{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "vkk",
    "version": "0.3.2+38++39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+37"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.2+38.jar",
          "url": "vkk-0.3.2+38.jar",
          "size": 1541460,
          "sha512": "920e6dcd673c3c6c50789dc4874c0d436eeec4ea0d7d7e3f1368b085eec661d7a165ebe327ce68d046278294364117da95ec72b274bcfa7ccd6a5f0d6eeaa33d",
          "sha256": "46bac2865e9eeb093ab260bb1cc7df2bb2809249b666e5de0a226bcaa68d253e",
          "sha1": "67b0ed413ac2d4c2016dd940629c12bbde919716",
          "md5": "2782da2d7ce29f6b03a90e805cbf456a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "spirvcrossj",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+37"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.2+38.jar",
          "url": "vkk-0.3.2+38.jar",
          "size": 1541460,
          "sha512": "920e6dcd673c3c6c50789dc4874c0d436eeec4ea0d7d7e3f1368b085eec661d7a165ebe327ce68d046278294364117da95ec72b274bcfa7ccd6a5f0d6eeaa33d",
          "sha256": "46bac2865e9eeb093ab260bb1cc7df2bb2809249b666e5de0a226bcaa68d253e",
          "sha1": "67b0ed413ac2d4c2016dd940629c12bbde919716",
          "md5": "2782da2d7ce29f6b03a90e805cbf456a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vkk-0.3.2+38-all.jar",
          "url": "vkk-0.3.2+38-all.jar",
          "size": 62034565,
          "sha512": "7c1d31225c30efbab31130bfd73e5599fb4e2793436ed56e969be27992a0eac74e823ea01f45d95fb659e75c0e1e5862beda1f2e2bda5ff9577d95dd5be2f84a",
          "sha256": "d3613df3907a4e288b889a3bb4c4f58a879bbce1cfd37ad7cd0d10cd31c2c301",
          "sha1": "b36b671999c3e641fbb8deb218c45cf2e50be246",
          "md5": "fc9251a10088ca19911b749cc5fa4e0c"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vkk-0.3.2+38-jdk8.jar",
          "url": "vkk-0.3.2+38-jdk8.jar",
          "size": 1535512,
          "sha512": "c83e0853ee043435e496083a11cb24a47e2409f616c015b3cbc9f6a637036607be1908f869f2e865354f613e894ddd5e6f581ad8083dd9c181cd3196d9c53934",
          "sha256": "e032709f0317f0baad16a5e703e52eaac2a7e236b2d099b6c775af97a8e7fd61",
          "sha1": "c11f58134a9fb4eeb758dfba02bb8c7f0d1bbe26",
          "md5": "df45017d9aaf920701b4534668dd5ac7"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vkk",
          "version": "0.3.2+38"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan"
        },
        {
          "group": "graphics.scenery",
          "module": "spirvcrossj",
          "version": {
            "requires": "0.6.0-1.1.106.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+37"
          }
        }
      ],
      "files": [
        {
          "name": "vkk-0.3.2+38-jdk8.jar",
          "url": "vkk-0.3.2+38-jdk8.jar",
          "size": 1535512,
          "sha512": "c83e0853ee043435e496083a11cb24a47e2409f616c015b3cbc9f6a637036607be1908f869f2e865354f613e894ddd5e6f581ad8083dd9c181cd3196d9c53934",
          "sha256": "e032709f0317f0baad16a5e703e52eaac2a7e236b2d099b6c775af97a8e7fd61",
          "sha1": "c11f58134a9fb4eeb758dfba02bb8c7f0d1bbe26",
          "md5": "df45017d9aaf920701b4534668dd5ac7"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "vkk",
          "version": "0.3.2+38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vkk-0.3.2+38-sources.jar",
          "url": "vkk-0.3.2+38-sources.jar",
          "size": 450144,
          "sha512": "55812dda124090ccefe1b13fcda31c6550cc5ae5c656f29cf0498916d3222947c1757e3dea921ee2751e29c0d824bb13f79061147b9f7d8b39b825330322ef24",
          "sha256": "6c818a57a7a231e168aecb5ac4bc0d1caf88bcaad640e7879cc0acbc519f60c5",
          "sha1": "e16243a289b9466190b8f73791bb0bd04a2dc317",
          "md5": "1d8d27b56833726c6ad9b9276e3d47ac"
        }
      ]
    }
  ]
}
