{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "lwjgl",
    "version": "0.7.0+98",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l47mnul6mfatlc25br32wyeerq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lwjgl-0.7.0+98.jar",
          "url": "lwjgl-0.7.0+98.jar",
          "size": 196192,
          "sha512": "50663ef85d2035e8e623db7fe7b5eb3471d9c88c08bc3ed7cb40b5247699daf6bad160e8abcd632302d1b8deda7e12adf985f31eb11ceedb5178c7cc5c8ffc05",
          "sha256": "d6b6bed3ecddaced4a5f038f3a4a31c202b5f917040c275204013ffc16f645a8",
          "sha1": "7ad22b46ef1b8654881c5632e80c7341234e5868",
          "md5": "e0f509347bf4a35f816cc14892b5412a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "lwjgl-0.7.0+98.jar",
          "url": "lwjgl-0.7.0+98.jar",
          "size": 196192,
          "sha512": "50663ef85d2035e8e623db7fe7b5eb3471d9c88c08bc3ed7cb40b5247699daf6bad160e8abcd632302d1b8deda7e12adf985f31eb11ceedb5178c7cc5c8ffc05",
          "sha256": "d6b6bed3ecddaced4a5f038f3a4a31c202b5f917040c275204013ffc16f645a8",
          "sha1": "7ad22b46ef1b8654881c5632e80c7341234e5868",
          "md5": "e0f509347bf4a35f816cc14892b5412a"
        }
      ]
    }
  ]
}
