{
  "formatVersion": "1.1",
  "component": {
    "group": "kx.build-logic",
    "module": "commons",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.6.3.jar",
          "url": "commons-0.6.3.jar",
          "size": 309621,
          "sha512": "c73cfa9f555343a8b7707cec551b58cf1ade427f7cbb2a706abe2799e884f346416c075b767c3691ab651793ebad935c9725ada99ee2d70120b41eec70005c80",
          "sha256": "dd4c7cf4fa5ca9abccf21b3f2f08febdcf492b5500e9b96dcafbce0e3c4ca60a",
          "sha1": "ec6c38315ab025a229d23b661eb4c34c95972189",
          "md5": "7b2b9012321167d1cc82aac134ca95c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kx.platform",
          "module": "plugin",
          "version": {
            "requires": "0.1.8"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kx.build-logic",
          "module": "impl",
          "version": {
            "requires": "0.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.6.3.jar",
          "url": "commons-0.6.3.jar",
          "size": 309621,
          "sha512": "c73cfa9f555343a8b7707cec551b58cf1ade427f7cbb2a706abe2799e884f346416c075b767c3691ab651793ebad935c9725ada99ee2d70120b41eec70005c80",
          "sha256": "dd4c7cf4fa5ca9abccf21b3f2f08febdcf492b5500e9b96dcafbce0e3c4ca60a",
          "sha1": "ec6c38315ab025a229d23b661eb4c34c95972189",
          "md5": "7b2b9012321167d1cc82aac134ca95c5"
        }
      ]
    }
  ]
}
