{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "glm",
    "version": "0.9.9.1-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-4.jar",
          "url": "glm-0.9.9.1-4.jar",
          "size": 2190367,
          "sha512": "0448362f5361a644ebb1d49af1b061b7953c381c173cd68df6d3df5558426f72ae4d70dc1d8896fa0666d8f5da30976f8a4d9f6c9d2a2d52d19f9bef7083884f",
          "sha256": "f8d8c9c1f76a32407f94ca68a7d05f8f63b7a162f3d98358c3b56d49d20d8b22",
          "sha1": "d7326e912a9d52beb264e9d5e99ec5ae7f9a0455",
          "md5": "1fd9efeb24478f08b93a48c50b61a80c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-4.jar",
          "url": "glm-0.9.9.1-4.jar",
          "size": 2190367,
          "sha512": "0448362f5361a644ebb1d49af1b061b7953c381c173cd68df6d3df5558426f72ae4d70dc1d8896fa0666d8f5da30976f8a4d9f6c9d2a2d52d19f9bef7083884f",
          "sha256": "f8d8c9c1f76a32407f94ca68a7d05f8f63b7a162f3d98358c3b56d49d20d8b22",
          "sha1": "d7326e912a9d52beb264e9d5e99ec5ae7f9a0455",
          "md5": "1fd9efeb24478f08b93a48c50b61a80c"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-4-jdk8.jar",
          "url": "glm-0.9.9.1-4-jdk8.jar",
          "size": 2176158,
          "sha512": "0cf4aa00b2f0a2aae7623ade34bda2155609b9d49d15c7313b54a27ebb7d544cf70a6a108995d7c20936dce54497291cd9ebd3e6386fb611a9c65c98df44b2f7",
          "sha256": "9013d8b6cf62b059e6c593d94796cfce9345e39160cf465c5f06dd50ced348d0",
          "sha1": "ef454f966be6c9cdcf28cad7a8da1b1f6895093e",
          "md5": "35a47f7b41b3dc64a6cfaea8cf9b50e9"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-4"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "glm-0.9.9.1-4-jdk8.jar",
          "url": "glm-0.9.9.1-4-jdk8.jar",
          "size": 2176158,
          "sha512": "0cf4aa00b2f0a2aae7623ade34bda2155609b9d49d15c7313b54a27ebb7d544cf70a6a108995d7c20936dce54497291cd9ebd3e6386fb611a9c65c98df44b2f7",
          "sha256": "9013d8b6cf62b059e6c593d94796cfce9345e39160cf465c5f06dd50ced348d0",
          "sha1": "ef454f966be6c9cdcf28cad7a8da1b1f6895093e",
          "md5": "35a47f7b41b3dc64a6cfaea8cf9b50e9"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "glm",
          "version": "0.9.9.1-4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glm-0.9.9.1-4-sources.jar",
          "url": "glm-0.9.9.1-4-sources.jar",
          "size": 424754,
          "sha512": "b0c1782ea1a4db3cad3a7eecfd7083528b0fdd7c28f1c6e71cd97830df18f8e4661fd5edbb56e9b7f25065709d0c3e1031d8698b24907e9c649bd8747f43127b",
          "sha256": "4e84cfd28a02452de7468e75cb1313fc4ac0c3ad7f05aa249a920f5420657e17",
          "sha1": "1e40466c368997c888689fdbfd9da533a6f6c9b0",
          "md5": "5076e165a5c7b6ac4f4532466146a69f"
        }
      ]
    }
  ]
}
