{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+41.jar",
          "url": "11-0.7.0+41.jar",
          "size": 326125,
          "sha512": "841bf36f30b97bfbeb31a6532edd78f000b205d641df6cdf8bb782569f7d2b5836dd5ba49aa1a9d8b0e7fef2fe878bda6d4950ea1685ddd1c9f8647eed64fa84",
          "sha256": "69420864ea87fd9a9aea3884a6b03b641b4d2e770b9b693d5f28232e81f1ae69",
          "sha1": "8ca7cb6bbf771f115c9715805d1b8c36b20f13ea",
          "md5": "ee55e1fa8e1756b48b9449b04a6e36a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+41"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+41"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+41.jar",
          "url": "11-0.7.0+41.jar",
          "size": 326125,
          "sha512": "841bf36f30b97bfbeb31a6532edd78f000b205d641df6cdf8bb782569f7d2b5836dd5ba49aa1a9d8b0e7fef2fe878bda6d4950ea1685ddd1c9f8647eed64fa84",
          "sha256": "69420864ea87fd9a9aea3884a6b03b641b4d2e770b9b693d5f28232e81f1ae69",
          "sha1": "8ca7cb6bbf771f115c9715805d1b8c36b20f13ea",
          "md5": "ee55e1fa8e1756b48b9449b04a6e36a2"
        }
      ]
    }
  ]
}
