{
  "formatVersion": "1.1",
  "component": {
    "group": "sciJava.catalogs",
    "module": "sciJava-catalogs",
    "version": "30.0.0+62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sciJava-catalogs-30.0.0+62.jar",
          "url": "sciJava-catalogs-30.0.0+62.jar",
          "size": 28258,
          "sha512": "d117f284c3b5d34e861418aff96d5e09dd208bfb9568c3bf71becde9f39dd38ff4bebbabd148d95077bb96a963ac13502c06fe5ea255786c9e8937f747cd771f",
          "sha256": "3dfbe65f556fd3d0fd6fda05bfd2ccccc3fa6e2f2406ca7ef4e321372d22e054",
          "sha1": "1b22a7063b91040109a85c15205ed7bb73085389",
          "md5": "63e2810c5550cf72fa3247766afdd4bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.4.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "sciJava-catalogs-30.0.0+62.jar",
          "url": "sciJava-catalogs-30.0.0+62.jar",
          "size": 28258,
          "sha512": "d117f284c3b5d34e861418aff96d5e09dd208bfb9568c3bf71becde9f39dd38ff4bebbabd148d95077bb96a963ac13502c06fe5ea255786c9e8937f747cd771f",
          "sha256": "3dfbe65f556fd3d0fd6fda05bfd2ccccc3fa6e2f2406ca7ef4e321372d22e054",
          "sha1": "1b22a7063b91040109a85c15205ed7bb73085389",
          "md5": "63e2810c5550cf72fa3247766afdd4bf"
        }
      ]
    }
  ]
}
