{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zhovj4en2fczhcbhfi4x7xffgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+87.jar",
          "url": "11-0.7.0+87.jar",
          "size": 328879,
          "sha512": "36831f4d5f2acb24b00e42559a73c79eb73f632d1e08639be4386d43bd1f53504a9d63a3ad4c1fc286f64b6f00fad9c3f8b20778f984b3d67443873a21f856c5",
          "sha256": "b6d70fea090e88ff9a0c7fb3acc6cf4d89853b359a1acd410bce466792c6c51a",
          "sha1": "87b296bb34e55f1472c90bc52e43858c6d2054cd",
          "md5": "a704aa6b9329bceee442fdacf92da578"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+87"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+87.jar",
          "url": "11-0.7.0+87.jar",
          "size": 328879,
          "sha512": "36831f4d5f2acb24b00e42559a73c79eb73f632d1e08639be4386d43bd1f53504a9d63a3ad4c1fc286f64b6f00fad9c3f8b20778f984b3d67443873a21f856c5",
          "sha256": "b6d70fea090e88ff9a0c7fb3acc6cf4d89853b359a1acd410bce466792c6c51a",
          "sha1": "87b296bb34e55f1472c90bc52e43858c6d2054cd",
          "md5": "a704aa6b9329bceee442fdacf92da578"
        }
      ]
    }
  ]
}
