{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-glfw",
    "version": "1.89.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.2.jar",
          "url": "imgui-glfw-1.89.2.jar",
          "size": 34134,
          "sha512": "eff5a647832c0bf084373c77d0125ff06fdd4ab96e31335f6e996c82f7224943593cf759c61f2c17b75be5ccb2d569a84599542a4263b85995b8d3ff0b5e5142",
          "sha256": "dd93450a909d20c62bd20df2e99a200d5ac7ff7d416b2b186f5c9a7eb0a18eec",
          "sha1": "fdc90f5dc92743bf32509d6505a11302de24a085",
          "md5": "53ab9d9d9ab2fbd342b728ab04825184"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.2.jar",
          "url": "imgui-glfw-1.89.2.jar",
          "size": 34134,
          "sha512": "eff5a647832c0bf084373c77d0125ff06fdd4ab96e31335f6e996c82f7224943593cf759c61f2c17b75be5ccb2d569a84599542a4263b85995b8d3ff0b5e5142",
          "sha256": "dd93450a909d20c62bd20df2e99a200d5ac7ff7d416b2b186f5c9a7eb0a18eec",
          "sha1": "fdc90f5dc92743bf32509d6505a11302de24a085",
          "md5": "53ab9d9d9ab2fbd342b728ab04825184"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-glfw-1.89.2-sources.jar",
          "url": "imgui-glfw-1.89.2-sources.jar",
          "size": 6804,
          "sha512": "838b51b46333b896d8cc4859ad70d58771649802d0a2684286de9e3e7d8baad914c2be3820c5eadc72730209d242f2495e9eacfe1c725d6be75018dd7fbd781f",
          "sha256": "ef172c650cb586b795d357ebdcb155ff8923ba98fd79266d06d4440141fdba31",
          "sha1": "d9e9e1c928bb015a2a349cbc5634e0719cd8d96b",
          "md5": "cbcd64a03124c683922a8d72521a5939"
        }
      ]
    }
  ]
}
