{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-glfw",
    "version": "1.89.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.2.jar",
          "url": "imgui-glfw-1.89.2.jar",
          "size": 36784,
          "sha512": "cabf7fbdd02fb56e52602ee886ad53654573c99886e8b7219e8bc2080ed6de63b7f900dff7f725071cd6107e703d5700c876cf2c82728027f207c6ca06f10590",
          "sha256": "455c77ec7ff3e949228548c38dce732f3dbe0e4f2b6f84c405f238f40116370e",
          "sha1": "8bb2d9c18e7b9aab390969744ac55f675177b1ab",
          "md5": "3871a5f27388ffc2416dc84140008db9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-glfw-1.89.2.jar",
          "url": "imgui-glfw-1.89.2.jar",
          "size": 36784,
          "sha512": "cabf7fbdd02fb56e52602ee886ad53654573c99886e8b7219e8bc2080ed6de63b7f900dff7f725071cd6107e703d5700c876cf2c82728027f207c6ca06f10590",
          "sha256": "455c77ec7ff3e949228548c38dce732f3dbe0e4f2b6f84c405f238f40116370e",
          "sha1": "8bb2d9c18e7b9aab390969744ac55f675177b1ab",
          "md5": "3871a5f27388ffc2416dc84140008db9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-glfw-1.89.2-sources.jar",
          "url": "imgui-glfw-1.89.2-sources.jar",
          "size": 7143,
          "sha512": "8ba3a094b3230400ec446cdf70e83a525de3c7c89fd568dd7ffe5a9a52cb846f6995461c705b7214ba68274d67c0171cac743c6c56fbc0709822212244c726d5",
          "sha256": "1052323023e1c8e79c318f27ef6d260c1b8cb9f63b25af83ce6e56b89369152f",
          "sha1": "17d693e5f8bc9de8da1deccad585692daf21aec0",
          "md5": "f24752693228c12ee0a35fbc9f6af965"
        }
      ]
    }
  ]
}
