{
  "formatVersion": "1.1",
  "component": {
    "group": "elect86",
    "module": "slurm.kts",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "slurm.kts-0.0.13.jar",
          "url": "slurm.kts-0.0.13.jar",
          "size": 72573,
          "sha512": "4018d7a741f1bc13b3ddbb01f63e22ddfd03fa4959ff964f356bb29ee63c8db2555e7d210432bf2358496daeb3957e48e2c828e9f8d774f6f69ebd75d09bdbf1",
          "sha256": "46bd4c4edbd1965906028eee26796d44201b4fe798f886059fd3784a60456915",
          "sha1": "316b6d9b1c2748ebd2e15ad7718f0652b17cfc74",
          "md5": "13255e3d767497ca516457282bac6e78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "slurm.kts-0.0.13.jar",
          "url": "slurm.kts-0.0.13.jar",
          "size": 72573,
          "sha512": "4018d7a741f1bc13b3ddbb01f63e22ddfd03fa4959ff964f356bb29ee63c8db2555e7d210432bf2358496daeb3957e48e2c828e9f8d774f6f69ebd75d09bdbf1",
          "sha256": "46bd4c4edbd1965906028eee26796d44201b4fe798f886059fd3784a60456915",
          "sha1": "316b6d9b1c2748ebd2e15ad7718f0652b17cfc74",
          "md5": "13255e3d767497ca516457282bac6e78"
        }
      ]
    }
  ]
}
