{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "platform-plugin",
    "version": "0.3.3+25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "kx.source-dynamic",
          "module": "kx.source-dynamic.gradle.plugin",
          "version": {
            "requires": "0.3.3+25"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "kx.source-dynamic",
          "module": "kx.source-dynamic.gradle.plugin",
          "version": {
            "requires": "0.3.3+25"
          }
        }
      ]
    }
  ]
}
