{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.3+49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.3+49.jar",
          "url": "commons-0.7.3+49.jar",
          "size": 657430,
          "sha512": "eee40a8513bc124c7cebec27c2d9c1e85af9189d2cd55620d95efbe621e9684f619055d50c136364062df1454f8ac4a4bb12adac0fd78a9eb860f730bdaec9a0",
          "sha256": "32578356292a757d37c4d6a14ea2db023c6569487192e9b790088a77ef9a399c",
          "sha1": "7ac15e9e9bef599542e495b354d7f1aaa77f8643",
          "md5": "0a1432339b11fb0eddd2b1ae4b6796f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-plugin",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin"
        }
      ],
      "files": [
        {
          "name": "commons-0.7.3+49.jar",
          "url": "commons-0.7.3+49.jar",
          "size": 657430,
          "sha512": "eee40a8513bc124c7cebec27c2d9c1e85af9189d2cd55620d95efbe621e9684f619055d50c136364062df1454f8ac4a4bb12adac0fd78a9eb860f730bdaec9a0",
          "sha256": "32578356292a757d37c4d6a14ea2db023c6569487192e9b790088a77ef9a399c",
          "sha1": "7ac15e9e9bef599542e495b354d7f1aaa77f8643",
          "md5": "0a1432339b11fb0eddd2b1ae4b6796f4"
        }
      ]
    }
  ]
}
