{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "v0.7.0-23-9d0ed24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-v0.7.0-23-9d0ed24.jar",
          "url": "commons-v0.7.0-23-9d0ed24.jar",
          "size": 325144,
          "sha512": "48b88e85f76fdc212bbd53d2ba32bb44706aec78b2697263d810b04b82b5662e0718bc1da630fba97368feababd69a4dd6c63bdc78cc87a08703a7d962cdae2e",
          "sha256": "598e2db02040c3e492b4408c9915f6cbffa3791b19caeb9f1b7d6266d39e7d14",
          "sha1": "656c268879dd41985852bb8b7c4d1bf99f4412a6",
          "md5": "6b83b20ff4d7f4c245a9e7ad90128ab5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-23-9d0ed24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "v0.7.0-23-9d0ed24"
          }
        }
      ],
      "files": [
        {
          "name": "commons-v0.7.0-23-9d0ed24.jar",
          "url": "commons-v0.7.0-23-9d0ed24.jar",
          "size": 325144,
          "sha512": "48b88e85f76fdc212bbd53d2ba32bb44706aec78b2697263d810b04b82b5662e0718bc1da630fba97368feababd69a4dd6c63bdc78cc87a08703a7d962cdae2e",
          "sha256": "598e2db02040c3e492b4408c9915f6cbffa3791b19caeb9f1b7d6266d39e7d14",
          "sha1": "656c268879dd41985852bb8b7c4d1bf99f4412a6",
          "md5": "6b83b20ff4d7f4c245a9e7ad90128ab5"
        }
      ]
    }
  ]
}
