{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.0+45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.0+45.jar",
          "url": "commons-0.7.0+45.jar",
          "size": 325635,
          "sha512": "612e3cb2003b452f4cb5a89cdd462bb61abc61b44fc671d273cb61a2b788cd55e72cc4cc490d0c2fc0bce138c22435968f16f9ce1ebbe7df955c8a9c945bc54f",
          "sha256": "da5fdabd891cc0b328423d261c716946b587c6a480e199d42405c2d63a3f39d5",
          "sha1": "58a0ebac21f40e5b0a455ba471068298f482b7be",
          "md5": "1ca69b6173dfbfabe081bce2c2e30dde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "0.7.0+45"
          }
        }
      ],
      "files": [
        {
          "name": "commons-0.7.0+45.jar",
          "url": "commons-0.7.0+45.jar",
          "size": 325635,
          "sha512": "612e3cb2003b452f4cb5a89cdd462bb61abc61b44fc671d273cb61a2b788cd55e72cc4cc490d0c2fc0bce138c22435968f16f9ce1ebbe7df955c8a9c945bc54f",
          "sha256": "da5fdabd891cc0b328423d261c716946b587c6a480e199d42405c2d63a3f39d5",
          "sha1": "58a0ebac21f40e5b0a455ba471068298f482b7be",
          "md5": "1ca69b6173dfbfabe081bce2c2e30dde"
        }
      ]
    }
  ]
}
