{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.2+21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cxe3evatcbhg5eqbk7emvsipsi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gln-0.5.2+21.jar",
          "url": "gln-0.5.2+21.jar",
          "size": 967267,
          "sha512": "12ba736dcbd0dfaea2f2c35b794f1e8d64ed991c6629fde6d4c1dca32e18d2178d487c545a432e5a5a2c43097970bcbca6a1833f4c27aaddd8b6c18076f965d1",
          "sha256": "0fd9a288dcd0534d9afd862d161ee1cea0dc8da6f2c55fae0086078e53281d7a",
          "sha1": "795c16af6e1d47ac17c2538b6f3b10b88121a185",
          "md5": "9471b1043492eebb75a9753cb0c302e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.2.8+39"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "excludes": [
            {
              "group": "kx.platform",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.2+21.jar",
          "url": "gln-0.5.2+21.jar",
          "size": 967267,
          "sha512": "12ba736dcbd0dfaea2f2c35b794f1e8d64ed991c6629fde6d4c1dca32e18d2178d487c545a432e5a5a2c43097970bcbca6a1833f4c27aaddd8b6c18076f965d1",
          "sha256": "0fd9a288dcd0534d9afd862d161ee1cea0dc8da6f2c55fae0086078e53281d7a",
          "sha1": "795c16af6e1d47ac17c2538b6f3b10b88121a185",
          "md5": "9471b1043492eebb75a9753cb0c302e2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+21-all.jar",
          "url": "gln-0.5.2+21-all.jar",
          "size": 12975401,
          "sha512": "3c8cfd290cf123c93fc9f352d104fbfbb44b6e755c3dd4e18927d0ba932bb8a4dfc234bab2e82da0fe4d937f9524967dab6097003c3606f997ffe3220fd34b0d",
          "sha256": "cd588772877e90923e8774c68bf2eb410722611aee43f2a8aa2732b96548c1cf",
          "sha1": "80690823f05b9255f397810f9cb2a9401841b6fd",
          "md5": "fcbcec5f0ed23816f3799799694921d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.2+21-sources.jar",
          "url": "gln-0.5.2+21-sources.jar",
          "size": 263116,
          "sha512": "ec78b0949943b6aebfd604591aca791c6e6746d7be6a93ae4330cb33c3a83265a39cc89fdd69eb54c603805362c07081d67e7d9ad9a8b4723d21c89c367d491b",
          "sha256": "e5067141f1bf822c1dae5402a4833a79c5fa394e55318cc8cfd30dede8c0a30b",
          "sha1": "032a07c94c66fbc9624ee797c6543aab54503a85",
          "md5": "c269081306520879d5f149b7802fcd30"
        }
      ]
    }
  ]
}
