{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "kx",
    "version": "0.7.0+99",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m4zrcqnvsbenvoprz6t7viu4ve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+99.jar",
          "url": "kx-0.7.0+99.jar",
          "size": 17730,
          "sha512": "dd3524eec85c5a22588eab4f0a2fd2592fab0f0955c06359d754824917104867c8a07a315aae4281b120c8b1e5d6214f892060bb018a7ca555db2d7b3bbc45d0",
          "sha256": "ee455651a20b94caa9fb13be68deb0b876771922ef8933841b78a12addb31abc",
          "sha1": "cd8366dd553833d7c4a96f7f52864599acd2b378",
          "md5": "cd6685e1327ef3030f6cd32ab4913c6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+99.jar",
          "url": "kx-0.7.0+99.jar",
          "size": 17730,
          "sha512": "dd3524eec85c5a22588eab4f0a2fd2592fab0f0955c06359d754824917104867c8a07a315aae4281b120c8b1e5d6214f892060bb018a7ca555db2d7b3bbc45d0",
          "sha256": "ee455651a20b94caa9fb13be68deb0b876771922ef8933841b78a12addb31abc",
          "sha1": "cd8366dd553833d7c4a96f7f52864599acd2b378",
          "md5": "cd6685e1327ef3030f6cd32ab4913c6c"
        }
      ]
    }
  ]
}
