{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gli",
    "version": "0.8.3.0-16+25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+52"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+25.jar",
          "url": "gli-0.8.3.0-16+25.jar",
          "size": 331313,
          "sha512": "00a793ef203663ddf2f6e4aa50117b3e3cdb00816c65d4ee1620326b5e67214a820532f8c7145497d6aec3ac402c89bee405e42f1f8e577b8e19e79617b2dcde",
          "sha256": "0030f69837bd4eb6348bde6a45e0bea26daa93121fb25427702e4950e1a01cd4",
          "sha1": "0edbee313d0f587f61a0ba483643af885b006487",
          "md5": "0051991fc0b86108f3a2f54b05d05f82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+52"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+25.jar",
          "url": "gli-0.8.3.0-16+25.jar",
          "size": 331313,
          "sha512": "00a793ef203663ddf2f6e4aa50117b3e3cdb00816c65d4ee1620326b5e67214a820532f8c7145497d6aec3ac402c89bee405e42f1f8e577b8e19e79617b2dcde",
          "sha256": "0030f69837bd4eb6348bde6a45e0bea26daa93121fb25427702e4950e1a01cd4",
          "sha1": "0edbee313d0f587f61a0ba483643af885b006487",
          "md5": "0051991fc0b86108f3a2f54b05d05f82"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+25-jdk8.jar",
          "url": "gli-0.8.3.0-16+25-jdk8.jar",
          "size": 318600,
          "sha512": "3cdd260c0ff1cde9b327a0799dbe37980658f4666b83077b25bea10dd4e36d3e3d33c2d96374a70242bf20683fa273788b5163ccab04f2d658100f24b1f7a869",
          "sha256": "19c6dc36a87202831ef0e7f883fa9f259a0f6a4854f1efa4a2b7ae11cad1533a",
          "sha1": "535767e5b5a451838bfa6996faa876f09bb85e1b",
          "md5": "7aadd6e9f714da972e70d1053a53f2c5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gli",
          "version": "0.8.3.0-16+25"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.3+24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-bmp",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-core",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-icns",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-iff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-jpeg",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-metadata",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pcx",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pdf",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pict",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-pnm",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-psd",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-sgi",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tga",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-thumbsdb",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "com.twelvemonkeys.imageio",
          "module": "imageio-tiff",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-awt",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-core",
          "version": {
            "requires": "0.7.9+52"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno-vk",
          "version": {
            "requires": "0.7.9+52"
          }
        }
      ],
      "files": [
        {
          "name": "gli-0.8.3.0-16+25-jdk8.jar",
          "url": "gli-0.8.3.0-16+25-jdk8.jar",
          "size": 318600,
          "sha512": "3cdd260c0ff1cde9b327a0799dbe37980658f4666b83077b25bea10dd4e36d3e3d33c2d96374a70242bf20683fa273788b5163ccab04f2d658100f24b1f7a869",
          "sha256": "19c6dc36a87202831ef0e7f883fa9f259a0f6a4854f1efa4a2b7ae11cad1533a",
          "sha1": "535767e5b5a451838bfa6996faa876f09bb85e1b",
          "md5": "7aadd6e9f714da972e70d1053a53f2c5"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "gli",
          "version": "0.8.3.0-16+25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gli-0.8.3.0-16+25-sources.jar",
          "url": "gli-0.8.3.0-16+25-sources.jar",
          "size": 67701,
          "sha512": "2312ace754785b3e321bd2d757b364489705930d039c323378bfc3c88f06d30a938e66831b580de944f76ec50cd062d3b787348c7fb372fb91e6d9e697c87b39",
          "sha256": "9add1ed6e21599567cd583afefe15e6f0ba7edda8d016877bd19102f034ce220",
          "sha1": "d64938bf055f3be2e6bea34f1fde31b84a6af5bd",
          "md5": "6fb5748796e8059ce91179e5c0bb4401"
        }
      ]
    }
  ]
}
