{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+28.jar",
          "url": "8-0.7.0+28.jar",
          "size": 323577,
          "sha512": "f465694e7fb4c37a1cb81f080fb94df34fef444f8a39a085ba8c093b739ee696b489c7f54f336b13b9050d82d798af7b5ad1178f2c557cb9f5d93cc9bd599f01",
          "sha256": "3a4ab1f14025a7d76fdae36a0f48e147aefa1d53c755c2f9f1f2f0f521a942ec",
          "sha1": "8c483da9b85eaef258b0d6eaf54c155a7eaf2cca",
          "md5": "dbd8d575737f938625f8ba3aaed579db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+28"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+28"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+28.jar",
          "url": "8-0.7.0+28.jar",
          "size": 323577,
          "sha512": "f465694e7fb4c37a1cb81f080fb94df34fef444f8a39a085ba8c093b739ee696b489c7f54f336b13b9050d82d798af7b5ad1178f2c557cb9f5d93cc9bd599f01",
          "sha256": "3a4ab1f14025a7d76fdae36a0f48e147aefa1d53c755c2f9f1f2f0f521a942ec",
          "sha1": "8c483da9b85eaef258b0d6eaf54c155a7eaf2cca",
          "md5": "dbd8d575737f938625f8ba3aaed579db"
        }
      ]
    }
  ]
}
