{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "core",
    "version": "0.7.9+35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+35.jar",
          "url": "core-0.7.9+35.jar",
          "size": 140805,
          "sha512": "69f1ea1383c246ff61ef02ae1eb25a8708b835a9c11e2c2a1e5859270440a876e95869546b3824139cc1c2996528cc52dc5ea9614d3cba82285602d3c8777977",
          "sha256": "83a5f9a4eea019f157909359dd702392d9c57c1f3c39591fe567e8960cacd3a2",
          "sha1": "2935f05e9e884001c570f04c26033e592b8dba1f",
          "md5": "e32e774d4bdb62e81e104aac034d2762"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+35.jar",
          "url": "core-0.7.9+35.jar",
          "size": 140805,
          "sha512": "69f1ea1383c246ff61ef02ae1eb25a8708b835a9c11e2c2a1e5859270440a876e95869546b3824139cc1c2996528cc52dc5ea9614d3cba82285602d3c8777977",
          "sha256": "83a5f9a4eea019f157909359dd702392d9c57c1f3c39591fe567e8960cacd3a2",
          "sha1": "2935f05e9e884001c570f04c26033e592b8dba1f",
          "md5": "e32e774d4bdb62e81e104aac034d2762"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.7.9+35-all.jar",
          "url": "core-0.7.9+35-all.jar",
          "size": 13140016,
          "sha512": "05159aa00b9b543e3ada068f5ff02d135f8175ba28ab7f5a22d2ea8bb8effe5ee7187751beb5a018767341deae6b02b4e09ae71c9833f62d34807bec5893fd74",
          "sha256": "227dade7b47b5aee2bd5401ee75e1c5696b5690db2867b696acdac85082a050f",
          "sha1": "ba148ed5e97ed1f269450a4aad6bc3916a265de9",
          "md5": "9e0d9dad66cae46bb0736d1bf8eb15da"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.7.9+35-jdk8.jar",
          "url": "core-0.7.9+35-jdk8.jar",
          "size": 140711,
          "sha512": "514d2c2a5997130d77f3b61df46f6eb53b329bdb86efc2911923fd995d27b8a47d08d4f072aa441bb6b260b0dca88cba42c1d4ae66a84d70026b06c656f10065",
          "sha256": "e3f2a2d6eb720f987aa5959fcc631055b4c91c1bc2d5fb304b19375c68cee755",
          "sha1": "2d0cc8e366b511246c67c17345540bed3f452fba",
          "md5": "925cf7572f5dbd4f76a0d39a8f6cffe0"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+35"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "source",
          "version": {
            "requires": "0.3.3+22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "unsigned"
        },
        {
          "group": "kotlin.graphics",
          "module": "kool"
        },
        {
          "group": "kotlin.graphics",
          "module": "glm"
        },
        {
          "group": "kotlin.graphics",
          "module": "gli"
        },
        {
          "group": "kotlin.graphics",
          "module": "gln"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "kotlin.graphics",
          "module": "unsigned",
          "version": {
            "requires": "3.3.1+3"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "kool",
          "version": {
            "requires": "0.9.0+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "glm",
          "version": {
            "requires": "0.9.9.1-3+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-16+24"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gln",
          "version": {
            "requires": "0.5.2+26"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "vkk",
          "version": {
            "requires": "0.3.2+38"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.9+35-jdk8.jar",
          "url": "core-0.7.9+35-jdk8.jar",
          "size": 140711,
          "sha512": "514d2c2a5997130d77f3b61df46f6eb53b329bdb86efc2911923fd995d27b8a47d08d4f072aa441bb6b260b0dca88cba42c1d4ae66a84d70026b06c656f10065",
          "sha256": "e3f2a2d6eb720f987aa5959fcc631055b4c91c1bc2d5fb304b19375c68cee755",
          "sha1": "2d0cc8e366b511246c67c17345540bed3f452fba",
          "md5": "925cf7572f5dbd4f76a0d39a8f6cffe0"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "core",
          "version": "0.7.9+35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.7.9+35-sources.jar",
          "url": "core-0.7.9+35-sources.jar",
          "size": 37180,
          "sha512": "73b6045bb1f332842d465e91cd49e88ea48667387554999c0099f0d30e06b8dd215634fc961146fe8d1cad24498b08aa45e65ac5ac48226d23a643ea244fa3d6",
          "sha256": "520b11a986c49985ebbe4c588f723f337c0d3f52901287fd290a96067465638b",
          "sha1": "4031ab7f4ae5fbbb04ba02b82f0d91504663566a",
          "md5": "8ed50617c98429a755d334f901dd48e7"
        }
      ]
    }
  ]
}
