{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "kool",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kool-0.9.3.jar",
          "url": "kool-0.9.3.jar",
          "size": 265246,
          "sha512": "6854b36950b3bee5b2c90ad7857b5e260a5b64c7f3e1bc2036840f22f1692aba70f426f3577e52ca9ae5bf9f299070d71848879fb80b0cbceda4902cd57f1f63",
          "sha256": "1506cf0aad76931cc8b9c94f684468453004d4ff9722449284f53a17defd1132",
          "sha1": "52895b9f65d36c58348bdfd7c659e1110217996f",
          "md5": "7fe81cf47bffdd6464c9a36cd023e175"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.3.jar",
          "url": "kool-0.9.3.jar",
          "size": 265246,
          "sha512": "6854b36950b3bee5b2c90ad7857b5e260a5b64c7f3e1bc2036840f22f1692aba70f426f3577e52ca9ae5bf9f299070d71848879fb80b0cbceda4902cd57f1f63",
          "sha256": "1506cf0aad76931cc8b9c94f684468453004d4ff9722449284f53a17defd1132",
          "sha1": "52895b9f65d36c58348bdfd7c659e1110217996f",
          "md5": "7fe81cf47bffdd6464c9a36cd023e175"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kool-0.9.3-jdk8.jar",
          "url": "kool-0.9.3-jdk8.jar",
          "size": 264841,
          "sha512": "dfb757528cd002c46067cd303d4f6a7c8615f2661f51e24c1a35ea62235dc1a6bdf7ae5bc96ea8b70186c9e589d95a93303089a2f6cf80c257bfa031786bd90a",
          "sha256": "bec14b54459f59171ff94166b3e582b8e16814bc4ab6de04cca28d0f463ac575",
          "sha1": "ceea3619c90f34981cd334f9a329c3e3d12f91fc",
          "md5": "32a043611e8e806f62bdbe95992bb31d"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "kool",
          "version": "0.9.3"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "platform-source",
          "version": {
            "requires": "0.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kool-0.9.3-jdk8.jar",
          "url": "kool-0.9.3-jdk8.jar",
          "size": 264841,
          "sha512": "dfb757528cd002c46067cd303d4f6a7c8615f2661f51e24c1a35ea62235dc1a6bdf7ae5bc96ea8b70186c9e589d95a93303089a2f6cf80c257bfa031786bd90a",
          "sha256": "bec14b54459f59171ff94166b3e582b8e16814bc4ab6de04cca28d0f463ac575",
          "sha1": "ceea3619c90f34981cd334f9a329c3e3d12f91fc",
          "md5": "32a043611e8e806f62bdbe95992bb31d"
        }
      ],
      "capabilities": [
        {
          "group": "kotlin.graphics",
          "name": "kool",
          "version": "0.9.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kool-0.9.3-sources.jar",
          "url": "kool-0.9.3-sources.jar",
          "size": 47050,
          "sha512": "a0fc963a35ca97bcb1f7f95710cfbc0353df56522aea93afb61b4a248d2557bfc5ece94b529ad2634689125c78cb89067996371b4a17b4e41f81fc458cac1e3a",
          "sha256": "1c0172396f056689cd2dd9b12c1eb3283cbd7edcc1ca883971c739312357f08d",
          "sha1": "97b1a4c5a3a8d0fb28b8870374603d94a589edd7",
          "md5": "8be94fd93397bcb7feb769bc259d32c5"
        }
      ]
    }
  ]
}
