{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+52.jar",
          "url": "8-0.7.0+52.jar",
          "size": 323595,
          "sha512": "9d4bb3ee91c2c4e2bb2c890fcc2c42957a1a3ba51ff6c671c76634c2cf2e667207961db0a1b1a8d813a8918f2367ac0aed1917b0443b162c0d079f75c625e7b6",
          "sha256": "48c6b0da4628113ffa69d95ae38d8c2369371abbf6f9802e03e7eaa58219e4d6",
          "sha1": "e9195e3c666bad130724404e344516e879329e42",
          "md5": "ee262b4fbd12573332d8dc0fa230750c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+52"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+52.jar",
          "url": "8-0.7.0+52.jar",
          "size": 323595,
          "sha512": "9d4bb3ee91c2c4e2bb2c890fcc2c42957a1a3ba51ff6c671c76634c2cf2e667207961db0a1b1a8d813a8918f2367ac0aed1917b0443b162c0d079f75c625e7b6",
          "sha256": "48c6b0da4628113ffa69d95ae38d8c2369371abbf6f9802e03e7eaa58219e4d6",
          "sha1": "e9195e3c666bad130724404e344516e879329e42",
          "md5": "ee262b4fbd12573332d8dc0fa230750c"
        }
      ]
    }
  ]
}
