{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+56.jar",
          "url": "docs-0.7.0+56.jar",
          "size": 234506,
          "sha512": "1d85b6b77cee63c782d19f0e522bf0c375a802d28743ad36efac48f811d681fe7dfc2af267a6d4d06ea1e7184b3c74f05ec5de5287c2ec36db79ab527233a1fa",
          "sha256": "53dc0c801b9fbecd26a72364ea7879137f5fe3ebe6f0e876fcf0b2510d036c0c",
          "sha1": "caad0db615795a05cb2bd201b4a3e257bcf79a85",
          "md5": "390cd4eff64980f1fc2ff660c327db33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+56.jar",
          "url": "docs-0.7.0+56.jar",
          "size": 234506,
          "sha512": "1d85b6b77cee63c782d19f0e522bf0c375a802d28743ad36efac48f811d681fe7dfc2af267a6d4d06ea1e7184b3c74f05ec5de5287c2ec36db79ab527233a1fa",
          "sha256": "53dc0c801b9fbecd26a72364ea7879137f5fe3ebe6f0e876fcf0b2510d036c0c",
          "sha1": "caad0db615795a05cb2bd201b4a3e257bcf79a85",
          "md5": "390cd4eff64980f1fc2ff660c327db33"
        }
      ]
    }
  ]
}
