{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2xopday4c5dmpgym4bxmgp342e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+79.jar",
          "url": "11-0.7.0+79.jar",
          "size": 327343,
          "sha512": "6ff1e60ccdcc0c08215294f23e35a537d2c1385aad2b7c9c34eeba835bd0bd9d09ef6c7534c1a4fd4312310012337e9b5371301f99250d749fa831a0f56eb5b4",
          "sha256": "2fe3cdbb8844033b4235b72821c0a43f3d89e7218f806b3dbadc630beb44e104",
          "sha1": "1ba8b02d3cfc6dc288becc8fb6bd4598d2470ddf",
          "md5": "064d2f811dfa48ab05cc490c4d76b069"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+79"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+79.jar",
          "url": "11-0.7.0+79.jar",
          "size": 327343,
          "sha512": "6ff1e60ccdcc0c08215294f23e35a537d2c1385aad2b7c9c34eeba835bd0bd9d09ef6c7534c1a4fd4312310012337e9b5371301f99250d749fa831a0f56eb5b4",
          "sha256": "2fe3cdbb8844033b4235b72821c0a43f3d89e7218f806b3dbadc630beb44e104",
          "sha1": "1ba8b02d3cfc6dc288becc8fb6bd4598d2470ddf",
          "md5": "064d2f811dfa48ab05cc490c4d76b069"
        }
      ]
    }
  ]
}
