{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "kx",
    "version": "0.7.0+51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+51.jar",
          "url": "kx-0.7.0+51.jar",
          "size": 18262,
          "sha512": "199139eac01a19f2da42c47a1ef71a600e08061e2aba9e6eb2f26abaa4493b105a1da4eb30bcf1ca8ea31f4db7069cab54fafe01c21c7efd935f26a6683c4dfb",
          "sha256": "2410ddbcba1a75e15dba015352072a1b75d5c5922af3a13e16e75463513ed46a",
          "sha1": "1276b8f830b6ba13df68ceff37986a2168c6783c",
          "md5": "32d7ea77b7bb79e9b8d68705dad78179"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kx-0.7.0+51.jar",
          "url": "kx-0.7.0+51.jar",
          "size": 18262,
          "sha512": "199139eac01a19f2da42c47a1ef71a600e08061e2aba9e6eb2f26abaa4493b105a1da4eb30bcf1ca8ea31f4db7069cab54fafe01c21c7efd935f26a6683c4dfb",
          "sha256": "2410ddbcba1a75e15dba015352072a1b75d5c5922af3a13e16e75463513ed46a",
          "sha1": "1276b8f830b6ba13df68ceff37986a2168c6783c",
          "md5": "32d7ea77b7bb79e9b8d68705dad78179"
        }
      ]
    }
  ]
}
