{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "reipifdyfrewhmsv4nh3ss7kp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+94.jar",
          "url": "docs-0.7.0+94.jar",
          "size": 423897,
          "sha512": "aedf64407d1e5db42c7c20af8621b50c9799c4595f155c2699548c5ebf94bd9ef2cd271e53af82af2d1614b4ae629719d7e5e1ff50d081c18a613227e0109322",
          "sha256": "ca33dc5141073718e520113e0b1402dde713bbd4700ec3708def0b551a70b45d",
          "sha1": "1cd2d4c2d6373849a8c6cbfb71e92ff41a6c83d6",
          "md5": "e41260b84ecc7402e1390766b07d69c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+94.jar",
          "url": "docs-0.7.0+94.jar",
          "size": 423897,
          "sha512": "aedf64407d1e5db42c7c20af8621b50c9799c4595f155c2699548c5ebf94bd9ef2cd271e53af82af2d1614b4ae629719d7e5e1ff50d081c18a613227e0109322",
          "sha256": "ca33dc5141073718e520113e0b1402dde713bbd4700ec3708def0b551a70b45d",
          "sha1": "1cd2d4c2d6373849a8c6cbfb71e92ff41a6c83d6",
          "md5": "e41260b84ecc7402e1390766b07d69c0"
        }
      ]
    }
  ]
}
