{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+82",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7lgq7pp63vcdpdcxbl2vivpf2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+82.jar",
          "url": "8-0.7.0+82.jar",
          "size": 324837,
          "sha512": "96b0691aab3273902e5b779145cd9b4c1bef8b9f982ac779c51a7aa33ce26b76044c558909cd53eba731507ebe58324ee68bd2fb1caf88cb6938f5e93007fa54",
          "sha256": "cfe7208f453cd4470cbe5ab43ef2a3ee8e42153f8471af86f4f85806aba2c3d8",
          "sha1": "871681f19efd949d192888dabfb09ccfb647b5e5",
          "md5": "8fb61668fb1d28f1635cae71022de76c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+82"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+82.jar",
          "url": "8-0.7.0+82.jar",
          "size": 324837,
          "sha512": "96b0691aab3273902e5b779145cd9b4c1bef8b9f982ac779c51a7aa33ce26b76044c558909cd53eba731507ebe58324ee68bd2fb1caf88cb6938f5e93007fa54",
          "sha256": "cfe7208f453cd4470cbe5ab43ef2a3ee8e42153f8471af86f4f85806aba2c3d8",
          "sha1": "871681f19efd949d192888dabfb09ccfb647b5e5",
          "md5": "8fb61668fb1d28f1635cae71022de76c"
        }
      ]
    }
  ]
}
