{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "gln",
    "version": "0.5.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.32.jar",
          "url": "gln-0.5.32.jar",
          "size": 1016836,
          "sha512": "a3e560a1ee6f73ebf17ea29616348c28dd0022e3f7383b2b8ab4c7bcf579c0dbeedf0163ef407d9603132ba250d40d435bbf17bacd5733fbd16fcd9cd08d53de",
          "sha256": "5a70800f707775c385aeee9e82db2b49ae8e07651950b91699e2a5e7bb2db2c9",
          "sha1": "2858c5c6d7da53bd80b96940c24330ed8fbe472b",
          "md5": "61d0c2c7b199db4e9be618a8a73743f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "gli",
          "version": {
            "requires": "0.8.3.0-22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-openal",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengles",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengles",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "gln-0.5.32.jar",
          "url": "gln-0.5.32.jar",
          "size": 1016836,
          "sha512": "a3e560a1ee6f73ebf17ea29616348c28dd0022e3f7383b2b8ab4c7bcf579c0dbeedf0163ef407d9603132ba250d40d435bbf17bacd5733fbd16fcd9cd08d53de",
          "sha256": "5a70800f707775c385aeee9e82db2b49ae8e07651950b91699e2a5e7bb2db2c9",
          "sha1": "2858c5c6d7da53bd80b96940c24330ed8fbe472b",
          "md5": "61d0c2c7b199db4e9be618a8a73743f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gln-0.5.32-sources.jar",
          "url": "gln-0.5.32-sources.jar",
          "size": 266037,
          "sha512": "c5683f35c2790b9e73c3e55a74d36e5977fc54c794558e69bcf8b1359bc9ef82f30bef07c0c5b4e0941ca68c6a89aeced70642db9219700ae5bad782bd09ec6e",
          "sha256": "4e0c0adb2281851c9e4940cfab2977a4eee1fe164118711c750557e629ed365f",
          "sha1": "887e3b601bdef3d18fac627098bf159bd2029718",
          "md5": "a97f27ddb05d35373b6959638e38dba1"
        }
      ]
    }
  ]
}
