{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "v0.7.0-15-f2689b7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-v0.7.0-15-f2689b7.jar",
          "url": "commons-v0.7.0-15-f2689b7.jar",
          "size": 325144,
          "sha512": "cc481a47c527855002701e606810882ae1a53d245e129418f55cef719d75503bddc34c61836e8815b76a31acba1476136f906fd69cd4c8822923b88c853e31f5",
          "sha256": "1d440ec053b186df9a005e8d8efada46cc39f8ceff475551c47344b9e5271e89",
          "sha1": "0619c5bca7323543cee50ce9b89606ae58186cef",
          "md5": "6387ec36465601901da49d641092db71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "v0.7.0-15-f2689b7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "kx",
          "version": {
            "requires": "v0.7.0-15-f2689b7"
          }
        }
      ],
      "files": [
        {
          "name": "commons-v0.7.0-15-f2689b7.jar",
          "url": "commons-v0.7.0-15-f2689b7.jar",
          "size": 325144,
          "sha512": "cc481a47c527855002701e606810882ae1a53d245e129418f55cef719d75503bddc34c61836e8815b76a31acba1476136f906fd69cd4c8822923b88c853e31f5",
          "sha256": "1d440ec053b186df9a005e8d8efada46cc39f8ceff475551c47344b9e5271e89",
          "sha1": "0619c5bca7323543cee50ce9b89606ae58186cef",
          "md5": "6387ec36465601901da49d641092db71"
        }
      ]
    }
  ]
}
