{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+89",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "j7nd6ix4sbbhxfkukaqbpxdunm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+89.jar",
          "url": "docs-0.7.0+89.jar",
          "size": 311941,
          "sha512": "5c56856f1e95426a84f9e363136078a5cc60d569a741d330b64c2bdb08892370752fcc8d951e9011e1b1dde8f1c979f84b3f2c84dac80cea2f48933bef4ce86a",
          "sha256": "3cd6785f10bd3467998fcd8931206b1b9d394f0d80229f99a4d690e53a4233ca",
          "sha1": "d5333fc7dc7a6a1870dbe188fc8e6e39669ad70b",
          "md5": "28af6cabc7e401e9f11be1bc59314645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+89.jar",
          "url": "docs-0.7.0+89.jar",
          "size": 311941,
          "sha512": "5c56856f1e95426a84f9e363136078a5cc60d569a741d330b64c2bdb08892370752fcc8d951e9011e1b1dde8f1c979f84b3f2c84dac80cea2f48933bef4ce86a",
          "sha256": "3cd6785f10bd3467998fcd8931206b1b9d394f0d80229f99a4d690e53a4233ca",
          "sha1": "d5333fc7dc7a6a1870dbe188fc8e6e39669ad70b",
          "md5": "28af6cabc7e401e9f11be1bc59314645"
        }
      ]
    }
  ]
}
