{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.2.jar",
          "url": "8-0.7.2.jar",
          "size": 27622,
          "sha512": "4a59acea173b1799b1a2f26b2d6218d70f72216aa2b56e43cf1350610ab51001166335a9138df4d275dfa55578e63f6923028c171f2c8de3af883297eb4ab231",
          "sha256": "9e3d02dca4db3fb78ba90bc5ee322d0f3471269904dd87ab2a52e2a29fd90cf9",
          "sha1": "1c1e14208337ae832c990230de83e7cf37ebbd4f",
          "md5": "43c3bc7e1fa419f1dd3e47fe67aedb47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.2.jar",
          "url": "8-0.7.2.jar",
          "size": 27622,
          "sha512": "4a59acea173b1799b1a2f26b2d6218d70f72216aa2b56e43cf1350610ab51001166335a9138df4d275dfa55578e63f6923028c171f2c8de3af883297eb4ab231",
          "sha256": "9e3d02dca4db3fb78ba90bc5ee322d0f3471269904dd87ab2a52e2a29fd90cf9",
          "sha1": "1c1e14208337ae832c990230de83e7cf37ebbd4f",
          "md5": "43c3bc7e1fa419f1dd3e47fe67aedb47"
        }
      ]
    }
  ]
}
