{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "11",
    "version": "0.7.0+33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "11-0.7.0+33.jar",
          "url": "11-0.7.0+33.jar",
          "size": 326123,
          "sha512": "5ebe8cc17bfd41017a3e35a4f7f970944e43e58179c48d5a7e36a77385b656592544dae3cdc1fdf2600661d3a9be53ffc24c1b64fd8f8b5ff470d35c8d196ffb",
          "sha256": "f3330db97283c7a4a7bee46ebf8f7ae3c981b6c6311d65eec70e3f98f372ea8b",
          "sha1": "fd043f925819b2862b90a80281c3d23f9588a76e",
          "md5": "4719d8fee14f70587bfbfa2244c270ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+33"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+33"
          }
        }
      ],
      "files": [
        {
          "name": "11-0.7.0+33.jar",
          "url": "11-0.7.0+33.jar",
          "size": 326123,
          "sha512": "5ebe8cc17bfd41017a3e35a4f7f970944e43e58179c48d5a7e36a77385b656592544dae3cdc1fdf2600661d3a9be53ffc24c1b64fd8f8b5ff470d35c8d196ffb",
          "sha256": "f3330db97283c7a4a7bee46ebf8f7ae3c981b6c6311d65eec70e3f98f372ea8b",
          "sha1": "fd043f925819b2862b90a80281c3d23f9588a76e",
          "md5": "4719d8fee14f70587bfbfa2244c270ba"
        }
      ]
    }
  ]
}
