{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+47.jar",
          "url": "8-0.7.0+47.jar",
          "size": 323595,
          "sha512": "96288b68d16f232d2df9a726f6813b341c3103f61b05e6545eaa3619f35cc458880ae2d0279ab7543a398149eee7978b8513fcb0a3ef50b218cb89945ef9d140",
          "sha256": "cb91375bda2e457614f21ce3963fbb7e16ca5c9aaeb326489f9ad39ae84b17a2",
          "sha1": "d4d3008094f21c3026cb218acb80b414a8e66435",
          "md5": "ed26cbddc067eb924242ebdbf8bad8f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+47"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+47.jar",
          "url": "8-0.7.0+47.jar",
          "size": 323595,
          "sha512": "96288b68d16f232d2df9a726f6813b341c3103f61b05e6545eaa3619f35cc458880ae2d0279ab7543a398149eee7978b8513fcb0a3ef50b218cb89945ef9d140",
          "sha256": "cb91375bda2e457614f21ce3963fbb7e16ca5c9aaeb326489f9ad39ae84b17a2",
          "sha1": "d4d3008094f21c3026cb218acb80b414a8e66435",
          "md5": "ed26cbddc067eb924242ebdbf8bad8f5"
        }
      ]
    }
  ]
}
