{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "docs",
    "version": "0.7.0+85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l6fgcibgjrfufokpdbegewhzmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docs-0.7.0+85.jar",
          "url": "docs-0.7.0+85.jar",
          "size": 311941,
          "sha512": "34f946fa980f4cddb9a0abf239431fe5eb82041d63c26fdbdef13b3c58bb18d84e7e09f07cc5ed82a8101361be696b8ae4f4301d513cc07b481d2b48256e02d6",
          "sha256": "a0587743ef06dfd42e9bbd2e5b76ce5443e711681afc6240373fdcdaf6824bc7",
          "sha1": "f52d523c800538d9d2a27d4e2f2ac8919eec0d3b",
          "md5": "06850c1a13d1ecbd28171d33d993b048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+42"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin"
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core"
        }
      ],
      "files": [
        {
          "name": "docs-0.7.0+85.jar",
          "url": "docs-0.7.0+85.jar",
          "size": 311941,
          "sha512": "34f946fa980f4cddb9a0abf239431fe5eb82041d63c26fdbdef13b3c58bb18d84e7e09f07cc5ed82a8101361be696b8ae4f4301d513cc07b481d2b48256e02d6",
          "sha256": "a0587743ef06dfd42e9bbd2e5b76ce5443e711681afc6240373fdcdaf6824bc7",
          "sha1": "f52d523c800538d9d2a27d4e2f2ac8919eec0d3b",
          "md5": "06850c1a13d1ecbd28171d33d993b048"
        }
      ]
    }
  ]
}
