{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+49.jar",
          "url": "8-0.7.0+49.jar",
          "size": 323585,
          "sha512": "d3c7d45c4e548f63b34fa16670ec7ee495ae20ec988164275ba508f6f6db57b7042b58c1ff0b93557d83a71bf1bfdb796ce4d359bf7d437234f62948f7c96c17",
          "sha256": "a7efbb948b32ce93b457633cb5fed77b2cbdaa4132ca480f9b5f241c08cffcc2",
          "sha1": "12d8ed56563de41276e44c111f8324a69f084b4d",
          "md5": "fc3c6ab68419f7e32b14467ebec02e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.2.8+25"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+49"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+49.jar",
          "url": "8-0.7.0+49.jar",
          "size": 323585,
          "sha512": "d3c7d45c4e548f63b34fa16670ec7ee495ae20ec988164275ba508f6f6db57b7042b58c1ff0b93557d83a71bf1bfdb796ce4d359bf7d437234f62948f7c96c17",
          "sha256": "a7efbb948b32ce93b457633cb5fed77b2cbdaa4132ca480f9b5f241c08cffcc2",
          "sha1": "12d8ed56563de41276e44c111f8324a69f084b4d",
          "md5": "fc3c6ab68419f7e32b14467ebec02e9a"
        }
      ]
    }
  ]
}
