{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics",
    "module": "imgui-gl",
    "version": "1.89.7-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.7-1.jar",
          "url": "imgui-gl-1.89.7-1.jar",
          "size": 51627,
          "sha512": "089e82d907022e16702769de391809d8bba28b2d540f784157df8b77f8f7a883b2d6be53b75ef4362c8504d2bc1b714f932d61d7686d98b2f8d583aee5da1a0f",
          "sha256": "398bc00350e12dbadbd0aeffb912a56710944fe47e64c7eafe07d185c6aec23c",
          "sha1": "c31fd042b226d29dd4b572c34b11f1fc8a82a084",
          "md5": "cb14fab5faab4918132bbafc02baa124"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-core",
          "version": {
            "requires": "1.89.7-1"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "imgui-glfw",
          "version": {
            "requires": "1.89.7-1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "kotlin.graphics",
          "module": "uno",
          "version": {
            "requires": "0.7.21"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-jemalloc",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-remotery",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-remotery",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-stb",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "imgui-gl-1.89.7-1.jar",
          "url": "imgui-gl-1.89.7-1.jar",
          "size": 51627,
          "sha512": "089e82d907022e16702769de391809d8bba28b2d540f784157df8b77f8f7a883b2d6be53b75ef4362c8504d2bc1b714f932d61d7686d98b2f8d583aee5da1a0f",
          "sha256": "398bc00350e12dbadbd0aeffb912a56710944fe47e64c7eafe07d185c6aec23c",
          "sha1": "c31fd042b226d29dd4b572c34b11f1fc8a82a084",
          "md5": "cb14fab5faab4918132bbafc02baa124"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-gl-1.89.7-1-sources.jar",
          "url": "imgui-gl-1.89.7-1-sources.jar",
          "size": 15801,
          "sha512": "b0fcc079d3825fb9a348fca53246ca62b2ae89fc472e7651ed0fa04dc6566d3a75b841552e491c922c5614aa6defe46b7d8a2f17c3647c2c9c22a2c4f69c43bf",
          "sha256": "0b642397e3beaeea1dd54143a371c0d359e2a734a1403a40eb7883ed9c373d2e",
          "sha1": "6b64cd57f59345933009956209d4ec90d09ebee5",
          "md5": "b0fbcaf51c26a64549b60000faef7bd4"
        }
      ]
    }
  ]
}
