{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "8",
    "version": "0.7.0+36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "8-0.7.0+36.jar",
          "url": "8-0.7.0+36.jar",
          "size": 323602,
          "sha512": "84f1adfbd8e8f845ce68a581ae76e6a6be3aa7276adb77baddb9046a2287b0bfcf6dbc9705357077d1bb5ec14abf616d642e395aae80c4bc0b2696db117eb194",
          "sha256": "36712b4ff8952cba60bbd108bb25364c4c237e43c42a0ee60732280a24c2063e",
          "sha1": "ddd460acda2b1a558e7471abf6802600033c28c8",
          "md5": "6f1a7149d8a12fdef7052b89efd09920"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.build-logic",
          "module": "platform-plugin",
          "version": {
            "requires": "0.7.0+36"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "kotlin.graphics.build-logic",
          "module": "commons",
          "version": {
            "requires": "0.7.0+36"
          }
        }
      ],
      "files": [
        {
          "name": "8-0.7.0+36.jar",
          "url": "8-0.7.0+36.jar",
          "size": 323602,
          "sha512": "84f1adfbd8e8f845ce68a581ae76e6a6be3aa7276adb77baddb9046a2287b0bfcf6dbc9705357077d1bb5ec14abf616d642e395aae80c4bc0b2696db117eb194",
          "sha256": "36712b4ff8952cba60bbd108bb25364c4c237e43c42a0ee60732280a24c2063e",
          "sha1": "ddd460acda2b1a558e7471abf6802600033c28c8",
          "md5": "6f1a7149d8a12fdef7052b89efd09920"
        }
      ]
    }
  ]
}
