{
  "formatVersion": "1.1",
  "component": {
    "group": "kotlin.graphics.build-logic",
    "module": "commons",
    "version": "0.7.3+4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-0.7.3+4.jar",
          "url": "commons-0.7.3+4.jar",
          "size": 385498,
          "sha512": "50a82f10b0e13eb6ef12313918ccb9ba5eec4356b7f8d21ee5ca13cd087ed484f474efd649f67808834448cbe3e4b2081074b1f4d0c3ced51a042ea18f302257",
          "sha256": "19d1d3601acf3be34ec37744f4c76f3914506f7e117990e9ab8e2b484f868dfa",
          "sha1": "63aed894ae1807fe5fb187246eba74eab3f2284d",
          "md5": "6e7496f86c41ecf41079df7ba34b8004"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "kotlin.graphics.platform",
          "module": "plugin",
          "version": {
            "requires": "0.3.3+12"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin"
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin"
        },
        {
          "group": "elect86.magik",
          "module": "elect86.magik.gradle.plugin"
        }
      ],
      "files": [
        {
          "name": "commons-0.7.3+4.jar",
          "url": "commons-0.7.3+4.jar",
          "size": 385498,
          "sha512": "50a82f10b0e13eb6ef12313918ccb9ba5eec4356b7f8d21ee5ca13cd087ed484f474efd649f67808834448cbe3e4b2081074b1f4d0c3ced51a042ea18f302257",
          "sha256": "19d1d3601acf3be34ec37744f4c76f3914506f7e117990e9ab8e2b484f868dfa",
          "sha1": "63aed894ae1807fe5fb187246eba74eab3f2284d",
          "md5": "6e7496f86c41ecf41079df7ba34b8004"
        }
      ]
    }
  ]
}
